README.md, docs/examples/config.rst
=> [doc] feat: fix typo and delete deprecated config element

docs/advance/fsdp_extension.rst, verl/third_party/vllm/vllm_v_0_4_2/llm_engine_sp.py, verl/third_party/vllm/vllm_v_0_5_4/llm_engine_sp.py, verl/trainer/ppo/workers/fsdp_workers.py
- [doc]fix: typo in fsdp dtensor weight loader extension
- [misc] fix: vllm gpu executor issue when world_size is 1
=> [misc] fix: vllm gpu executor issue when world_size is 1 and typo in doc

single_controller/ray/base.py
Currently, the loop will always iterate 120 times.
=> [chore] Break the loop after obtaining the register_center actor

single_controller/ray/base.py
It looks like that `self._worker_names` doesn't need to be updated.
https://github.com/volcengine/verl/blob/27b43eba2b8905fdf18237548e596819e1831fdb/single_controller/ray/base.py#L261
=> [chore] remove unnecessary updating of `_worker_names`

examples/ppo_trainer/run_gemma.sh, verl/trainer/ppo/critic/dp_critic.py
- Add eval() and train() in dp_critic.py to fix gradient checkpoint issue
- Add gemma 2b examples using only 2A100
=> [misc] feat: add gemma example for small scale debug and fix gradient checkpoint in critic

examples/ppo_trainer/run_deepseek7b_llm.sh, examples/ppo_trainer/run_deepseek_full_hh_rlhf.sh, examples/ppo_trainer/run_deepseek_math_gsm8k_megatron.sh, examples/ppo_trainer/run_deepseek_megatron.sh, examples/ppo_trainer/run_gemma.sh, examples/ppo_trainer/run_qwen2-7b.sh, examples/ppo_trainer/run_qwen2-7b_rm.sh, examples/ppo_trainer/run_qwen2.5-32b.sh, verl/utils/tracking.py
Example usage:
bash examples/ppo_trainer/run_deepseek7b_llm.sh +trainer.xxx=yyy
=> [example] fix: make wandb optional dependency. allow extra args in existing scripts

docs/examples/config.rst, docs/examples/gsm8k_example.rst, docs/start/quickstart.rst, examples/ppo_trainer/run_deepseek7b_llm.sh, examples/ppo_trainer/run_deepseek_full_hh_rlhf.sh, examples/ppo_trainer/run_deepseek_math_gsm8k_megatron.sh, examples/ppo_trainer/run_deepseek_megatron.sh, examples/ppo_trainer/run_gemma.sh, examples/ppo_trainer/run_qwen2-7b.sh, examples/ppo_trainer/run_qwen2-7b_rm.sh, examples/ppo_trainer/run_qwen2.5-32b.sh, examples/sft/gsm8k/run_deepseek_6b7.sh, examples/sft/gsm8k/run_gemma_2b.sh, examples/sft/gsm8k/run_gemma_7b.sh, examples/split_placement/config/ppo_trainer_split.yaml, examples/split_placement/run_deepseek7b_llm.sh, verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/config/ppo_trainer.yaml, verl/utils/tracking.py
The change is backward compatible. 
trainer.logger=`tracking` is deprecated. use `wandb` instead.
=> api: rename tracking logger to wandb logger type

verl/trainer/ppo/critic/dp_critic.py
The values need to be multiplied by the response mask; otherwise, the calculation of adv later will be incorrect. This is similar to the approach used in megatron_critic:
https://github.com/PanAndy/verl/blob/681dc00b78b90cda4288535ca9a6c1ec7a4b7c98/verl/trainer/ppo/critic/megatron_critic.py#L92
=> (fix): fix values response mask in dp critic.

verl/trainer/ppo/ray_trainer.py
Hello, and thank you for your hard work on this project! While using `verl`, I noticed a calculation error in the `compute_data_metric` function within `ray_trainer`. Specifically, the function uses a 2D **int** tensor instead of the expected **bool** tensor for indexing. This discrepancy, based on PyTorch's advanced indexing mechanism, results in a 3D array rather than the expected 1D array.
The core issue lies in the behavior of PyTorch advanced indexing when using non-boolean tensors:
1. **Incorrect Mask Behavior**:
* Advanced indexing treats the provided 2D tensor as integer-based indices instead of a mask.
* As a result, indexing operates row-by-row, failing to correctly mask elements in the same row that are not part of the desired response.
2. **Excessive Memory Usage**:
* The …
=> fix response_mask index

docker/Dockerfile.vemlp.vllm.te, docs/start/install.rst, docs/workers/ray_trainer.rst, pyproject.toml, requirements.txt, verl/trainer/ppo/ray_trainer.py
- Fixed WorkerDict reference issue since Ray >2.31 by storing worker_dict in RayTrainer
- Currently, our Ray version won't depend on Ray==2.10 but should work with any version >2.38
=> [misc] fix: weak reference of WorkerDict in RayTrainer

verl/trainer/config/ppo_trainer.yaml, verl/trainer/ppo/ray_trainer.py, verl/utils/tracking.py, verl/workers/fsdp_workers.py
Hi, this is a tiny PR to
* support mlflow in addition to existing wandb and console
* allow critic forward to have different batch size than critic update (if I understand correctly, usually forward can have larger one)
* expose more metrics, mainly the "timing per token"
Example outputs of mlflow:
Example outputs of the new metrics:
=> Support Mlflow, allow forward to have different batch size, compute more metrics

.github/workflows/e2e_gpu.yml, .github/workflows/model.yml, examples/ppo_trainer/run_deepseek7b_llm.sh, examples/ppo_trainer/run_gemma.sh, examples/ppo_trainer/run_qwen2-7b.sh, examples/ppo_trainer/run_qwen2-7b_rm.sh, examples/ppo_trainer/run_qwen2.5-32b.sh, pyproject.toml, requirements.txt, tests/e2e/arithmetic_sequence/rl/config/ray_trainer.yaml, tests/e2e/arithmetic_sequence/rl/main_trainer.py, tests/e2e/run_ray_trainer_rmpad.sh, tests/model/test_transformer.py, tests/rollout/run_fsdp_vllm.py, verl/models/registry.py, verl/trainer/config/ppo_trainer.yaml, verl/utils/torch_functional.py, verl/workers/actor/dp_actor.py, verl/workers/critic/dp_critic.py, verl/workers/fsdp_workers.py
- Use `actor_rollout_ref.model.use_rmpad=True` + `critic.model.use_rmpad=True \` + `reward_model.model.use_rmpad=True ` to enable rmpad for different models. Default set to False
- Using `AutoModelForTokenClassification` for Value and Reward Model. Instead of using SeqenceClassification
- Compute logprob convert to `log_probs_from_logits_response_rmpad`
Resolve: https://github.com/volcengine/verl/issues/53
**Comparison using DeepSeek7b and GSM8k:**
About 1.7x speedup compare to no rmpad (original cases)
=> [misc] feat: spport rmpad/data-packing in FSDP with transformers

verl/trainer/fsdp_sft_trainer.py
This PR mainly fixes the display loss value in the `fsdp_sft_trainer`. We should sum up the scaled values rather than directly use the scaled one. By the way, we also performed an all reduce operation to average the loss values among DP nodes.
- Python version: 3.10.12
- PyTorch version: 2.5.1+cu124 (GPU)
- Transformers version: 4.47.1
- GPU type: NVIDIA H100
- vLLM version: 0.6.6.post1
```bash
torchrun --standalone --nnodes=1 --nproc_per_node=4 \
-m verl.trainer.fsdp_sft_trainer \
data.train_files=$HOME/data/gsm8k/train.parquet \
data.val_files=$HOME/data/gsm8k/test.parquet \
data.prompt_key=prompt \
data.response_key=answer \
data.micro_batch_size=8 \
model.partial_pretrain=meta-llama/Meta-Llama-3-8B-Instruct \
trainer.project_name=gsm8k-sft \ …
```
=> Fix the displayed loss in the sft trainer for gradient accumulation > 1

.github/workflows/e2e_digit_completion.yml, .github/workflows/e2e_gsm8k.yml, .github/workflows/model.yml
=> [ci] fix: add force stop in ray e2e ci to clean env

scripts/format.sh, verl/trainer/config/ppo_trainer.yaml, verl/trainer/ppo/ray_trainer.py
- Add format script
- Move save_checkpoint to a separate function
- Add timing/step, response_length/clip_ratio, prompt_length/clip_ratio and critic/vf_explained_var metrics
- The training step starts from 1
=> [misc] chore: refactor and add several metrics

verl/trainer/ppo/ray_trainer.py, verl/workers/actor/dp_actor.py, verl/workers/fsdp_workers.py
- Set use_reentrant=False to avoid duplicate allgather in backward when gradient checkpointing is enabled.
- Optimize temperature computation by using inplace op
- Fix testing logics
=> [perf] fix: set use_reentrant=False when enable gradient checkpointing

verl/trainer/fsdp_sft_trainer.py
- Without multiproc
Train 1/2:   1%|▍                                                                             | 20/3934 [01:38<5:14:50,  4.83s/it
Avg GPU utilization: 55%
- With multiproc
Train 1/2:   1%|▍                                                                             | 20/3934 [01:00<2:57:09,  2.72s/it]
Avg GPU utilization: 95%
=> [perf] enable multiproc dataloader in sft trainer

verl/utils/fsdp_utils.py
This PR supports:
- meta device init (which keeps the shared parameters)
- parallel pre-trained weight init for FSDP from huggingface checkpoint
=> [perf] feat: support meta device init and parallel load for fsdp 

tests/utility/test_tensor_dict_utilities.py, verl/protocol.py
- In some cases, there would be a nan value in the np.array.
- We fix it using pandas as np fail to assert array when the type is object
=> [misc] fix nan in non_tensor_batch union

verl/workers/rollout/vllm_rollout/vllm_rollout.py
We set `max_num_batched_tokens` in config `.rollout`, but they weren't actually being passed to VLLM -- causing potential insufficient use of GPUs.
This PR:
- properly pass `max_num_batched_tokens` from config to vLLM
- set `disable_log_stats` to False, so vLLM performance information can be properly displayed (to spot issues)
=> [VLLM] Set max_num_batched_tokens for vllm rollout

.github/workflows/dataset.yml, .github/workflows/e2e_digit_completion.yml, .github/workflows/e2e_gsm8k.yml, .github/workflows/e2e_lora.yml, .github/workflows/e2e_sft.yml, .github/workflows/model.yml, .github/workflows/ray_test.yml, .github/workflows/vllm.yml, tests/e2e/arithmetic_sequence/rl/config/ray_trainer.yaml, tests/e2e/run_qwen_gsm8k_model_rm_seq_balance.sh, tests/e2e/run_ray_trainer.sh, verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/config/ppo_trainer.yaml, verl/workers/actor/dp_actor.py, verl/workers/critic/dp_critic.py, verl/workers/fsdp_workers.py, verl/workers/rollout/vllm_rollout/vllm_rollout.py
- Previous gradient accumulation value is computed by micro_batch_size, which is wrong when using dynamic_bsz
- Fix ci script to avoid overlooking this issue
- Change vLLM state log default value to True to disable log.
- We will check the `self.config.actor.ppo_mini_batch_size % self.config.actor.ppo_micro_batch_size_per_gpu == 0` after normalization in fsdp_workers instead of in dp_actor and dp_critic.
=> [misc] fix: gradient accumulation in seq balance and modify default vllm log level

tests/utility/test_tensor_dict_utilities.py, verl/protocol.py
- As titled
- Solved: #149 
Waiting for testing from @chujiezheng
=> [misc]fix: pad dataproto when pad size is larger than len(dataproto)

verl/trainer/ppo/core_algos.py
`token_level_rewards == (token_level_rewards * non_zero_mask)`
=> fix: redundant non_zero_mask

.github/workflows/e2e_gsm8k.yml, pyproject.toml, requirements.txt, tests/e2e/run_qwen_gsm8k_model_rm_liger_kernel.sh, verl/workers/fsdp_workers.py
This PR enables to use Liger Kernel's `_apply_liger_kernel_to_instance` to init a fsdp worker model.
1. Adding an option of using `liger_kernel.transformers.AutoLigerKernelForCausalLM` to load a model from pretained, instead of the default `transformers.AutoModelForCausalLM`
2. Added a test case using configuration file `tests/e2e/run_qwen_gsm8k_model_rm_liger_kernel.sh`
#96 
#97 optimize the memory usage when computing entropy & log_probs
https://github.com/volcengine/verl/blob/6d96fda3d47f057caaa8f494ca7804181903e911/verl/workers/actor/dp_actor.py#L94-L106
=> [Liger-kernel] Add an option to use `_apply_liger_kernel_to_instance()` to load model

.github/workflows/e2e_sft.yml, examples/sft/gsm8k/run_qwen_05_sp2_liger.sh, tests/sft/run_sft_qwen05_sp2_liger.sh, verl/trainer/config/sft_trainer.yaml, verl/trainer/fsdp_sft_trainer.py
This PR adds support for LigerKernel for SFT and add a test to CI for this feature.
=> [feat, SFT] Support LigerKernel for SFT

examples/data_preprocess/math_dataset.py, examples/ppo_trainer/run_qwen2-7b_rm.sh, requirements.txt, verl/trainer/main_ppo.py, verl/workers/megatron_workers.py
since 'lighteval/MATH' is no longer available on huggingface.
=> data: fix the math dataset source

verl/workers/fsdp_workers.py
To avoid cases where the prompt_num is smaller than dp_size (i.e., gpu_num // sp_size) but prompt_num * rollout.n is still larger than dp_size
=> exchange the mini_batch_size calculation logic

verl/utils/tracking.py
runs always show "crashed" on my wandb, despite finishing successfully. "Crashed" indicates that wandb did not finish sending the "success" signal to the server so the server believes the client was terminated unexpectedly.  Furthermore, wandb log is incomplete (last lines missing).
This PR adds a call to `wandb.finish` when the Tracker was destructed (oftentimes when `trainer.fit` finished) so that signals are sent to the server and a data sync is performed.
Without this change:
With this change:
=> Call wandb.finish when the tracker is destructed if wandb is in use

verl/utils/torch_functional.py
https://github.com/volcengine/verl/pull/182
add a assert statement to make sure flash-attn>=2.4.3 where cross_entropy_loss returns Tuple[losses, z_losses]🤯
=> assert to make sure flash-attn>=2.4.3

README.md, verl/utils/tracking.py
---
This PR introduces **SwanLab**, a lightweight open-source experiment tracking tool, as a new logging option for the training framework. The integration provides both online and offline tracking capabilities, along with a local dashboard for visualizing results. Below is a detailed overview of the changes and usage instructions:
---
1. **Online and Offline Tracking**:
- **Online Mode**: Track experiments remotely and store data on SwanLab's cloud platform.
- **Offline Mode**: Use a local dashboard to visualize training logs without an internet connection.
2. **Hardware Monitoring**:
- Automatically tracks GPU usage, power consumption, temperature, and other hardware metrics.
- Supports NVIDIA GPUs and Huawei Ascend NPUs.
3. **Remote Access**:
- View training progress remotely via the …
=> [TRACKING] feat: Integrate SwanLab for experiment tracking with online/offline mode and local dashboard support

tests/gpu_utility/test_torch_functional.py, verl/utils/torch_functional.py
Existing `logprobs_from_logits_v2` doesnt achieve the memory savings it claims. This is because `logsumexp` still allocates a `bs*seqlen*vocab` tensor internally to hold the element-wise application of `exp`. However, by applying a loop over `logsumexp`, we can iteratively compute logsumexp outputs.
Benchmarks show this uses significantly less memory to compute logprobs.
Fix provided, as well as a separate memory-efficient approach for bfloat16 case.
=> Memory efficiency improvement to logprobs_from_logits_v2

.github/workflows/e2e_gsm8k.yml, tests/checkpoint/test_fsdp_ckpt.py, tests/e2e/run_qwen_gsm8k_function_rm.sh, tests/e2e/run_qwen_gsm8k_function_rm_no_rmpad.sh, tests/e2e/run_ray_trainer.sh, verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/config/ppo_trainer.yaml, verl/trainer/ppo/ray_trainer.py, verl/utils/checkpoint/checkpoint_manager.py, verl/utils/checkpoint/fsdp_checkpoint_manager.py, verl/utils/dataset/rl_dataset.py, verl/workers/fsdp_workers.py
**Features:**
- Save actor and critic checkpoint:
- Model
- Optimizer
- lr_scheduler
- rng_state
- dataloader
- A complete checkpoint represents that dataloader, actor and critic (if any) state are properly saved
- By default, we will not save the dataset but only store the dataloader (with sampler) state
**Usage:**
- Support resume mode: auto, disable and resume_from_path
- auto: veRL will automatically check the latest checkpoint from `trainer.default_local_dir`
- disable: veRL will always train from scratch
- resume_from_path: When setting `resume_from_path`=True, then user only need to set the resume_mode to the checkpoint path that you want to load.
**TODO:**
- Support SFT resume in the next PR
- Support uploader
**Relevant issue:**
- https://github.com/volcengine/verl/issues/76
- …
=> [ckpt] feat: integrate checkpoint resume in RL ray trainer

docs/examples/config.rst, verl/trainer/ppo/core_algos.py, verl/trainer/ppo/ray_trainer.py
We have implemented the REINFORCE++ algorithm.
To use it, specify the parameter `algorithm.adv_estimator=reinforce_plus_plus`.
Preliminary performance evaluations were conducted within the [Unakar/Logic-RL](https://github.com/Unakar/Logic-RL) project, a reproduction of DeepSeek R1 Zero on the 2K Tiny Logic Puzzle Dataset. Results indicate that our REINFORCE++ implementation exhibits performance and training stability comparable to, or potentially exceeding, that of PPO and GRPO.
Related issue: #68
=> implement REINFORCE++ algorithm

verl/trainer/config/ppo_trainer.yaml, verl/trainer/ppo/ray_trainer.py
Often the summary of average/max/min reward is not enough information, and it's helpful to look at some real-world generations to see how the model's actual behavior is changing over time. This can be particularly helpful for debugging issues like the generation being cut off before reasoning finishes.
This PR introduces a new `trainer.val_generations_to_log_to_wandb` config value, with a default of 0. If set to a number larger than 0, it logs that number of inputs/outputs/scores each time the validation set is generated and scored. It uses a [wandb Table](https://docs.wandb.ai/guides/track/log/log-tables/) to do so, adding a single row for each validation set run.
I choose to log the data in this format because it allows a user to easily see how the outputs for a given input change over …
=> Add option to log validation generations to wandb

verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/ppo/ray_trainer.py
=> [misc]: fix ci and add warning to make sure wandb is used when logging val results

verl/models/transformers/llama.py
**Fix: Compatibility Issue with Python 3.9 in FSDP Worker for LLaMA Model**
When running the LLaMA model in the FSDP worker, an ImportError occurs due to the use of the Unpack type from the typing module. This type is only available in Python 3.11 and later, but the current environment uses Python 3.9, which does not support it.
**Error Details:**
```
File "/project/Logic-RL-main/verl/models/transformers/llama.py", line 17, in <module>
from typing import Optional, List, Union, Tuple, Unpack, Callable
ImportError: cannot import name 'Unpack' from 'typing' (/opt/miniconda3/envs/verl/lib/python3.9/typing.py)
```
**Solution:**
To resolve this issue, I added conditional imports to handle different Python versions. For Python versions lower than 3.11, the code now uses a fallback or alternative …
=> [misc] Compatibility Issue with Python 3.9 in FSDP Worker for LLaMA Model

verl/utils/checkpoint/checkpoint_manager.py
Previous FileLock in 
https://github.com/volcengine/verl/blob/c46f403479db5d7afca6388800503a3bfe393bf5/verl/utils/checkpoint/checkpoint_manager.py#L75
may cause some errors when the given path is too long. To fix this issue, use the hash value to replace the original path to avoid the conflict.
For instance, FileExistsEror: lErmno 17] File exists or BlockingIOError: [Errno 11] Resource temporarily unavailable.
After modifying this part, the issue could be avoided.
```
@staticmethod
def local_mkdir(path):
if not os.path.isabs(path):
working_dir = os.getcwd()
path = os.path.join(working_dir, path)
lock_filename = f"ckpt_{hash(path) & 0xFFFFFFFF:08x}.lock"
lock_path = os.path.join(tempfile.gettempdir(), lock_filename)
try:
with FileLock(lock_path, timeout=60):  # Add timeout …
```
=> fix the file lock issue

verl/trainer/ppo/ray_trainer.py
Currently, checkpoints will not be saved until the training steps satisfy the saving frequency.  This PR adds an auto-save ckpt function at the end of training.
=> Add auto save ckpt at the end of training

.github/workflows/sandbox.yml, pyproject.toml, requirements.txt, setup.py
- Rollout back vllm version (vllm > 0.7.0 only for testing)
- pyext as an extra requirement
=> [misc] fix install requirement

examples/split_placement/README.md, examples/split_placement/config/ppo_trainer_split.yaml, examples/split_placement/split_monkey_patch.py
The split placement example is outdated, I tried it and encountered some errors. To address this, the following changes were made in this PR
1. Copied the content from `verl/trainer/config/ppo_trainer.yaml` to `examples/split_placement/config/ppo_trainer_split.yaml`
2. Copied `RayPPOTrainer.fit` method into the `fit` func in `examples/split_placement/split_monkey_patch.py` and modified it to get the futures of `critic_output` and `actor_output`
=> fix the split placement example

verl/utils/reward_score/__init__.py, verl/workers/reward_manager/naive.py
This update enhances the reward computation process by introducing an additional `extra_info` parameter. This allows users to pass in more contextual information when calculating rewards, improving flexibility for different datasets.  
- **Updated `_default_compute_score`** to accept an `extra_info` argument:  
```python
def _default_compute_score(data_source, solution_str, ground_truth, extra_info):
```
- **Modified the reward manager (`naive.py`)** to pass `extra_info` from `data_item.non_tensor_batch` to `compute_score`:  
```python
extra_info = data_item.non_tensor_batch['extra_info']
score = self.compute_score(
data_source=data_source,
solution_str=sequences_str,
ground_truth=ground_truth,
extra_info=extra_info,
)
```
- Some datasets require additional context beyond `data_source`, …
=> Enhancement: Support for `extra_info` in Reward Calculation

docs/examples/config.rst, docs/examples/gsm8k_example.rst, examples/grpo_trainer/run_deepseek7b_llm.sh, examples/grpo_trainer/run_deepseek7b_llm_seq_balance.sh, examples/grpo_trainer/run_qwen2-7b.sh, examples/grpo_trainer/run_qwen2-7b_seq_balance.sh, examples/ppo_trainer/run_deepseek7b_llm.sh, examples/ppo_trainer/run_deepseek7b_llm_sp2.sh, examples/ppo_trainer/run_gemma.sh, examples/ppo_trainer/run_qwen2-7b.sh, examples/ppo_trainer/run_qwen2-7b_rm.sh, examples/ppo_trainer/run_qwen2-7b_rm_seq_balance.sh, examples/ppo_trainer/run_qwen2-7b_seq_balance.sh, examples/ppo_trainer/run_qwen2.5-32b.sh, examples/remax_trainer/run_qwen2.5-3b_seq_balance.sh, examples/remax_trainer/run_qwen2.5-7b_seq_balance.sh, examples/split_placement/config/ppo_trainer_split.yaml, examples/split_placement/run_deepseek7b_llm.sh, tests/e2e/run_qwen_gsm8k_function_rm.sh, tests/e2e/run_qwen_gsm8k_function_rm_grpo.sh, tests/e2e/run_qwen_gsm8k_function_rm_no_rmpad.sh, tests/e2e/run_qwen_gsm8k_function_rm_remax.sh, tests/e2e/run_qwen_gsm8k_model_rm.sh, tests/e2e/run_qwen_gsm8k_model_rm_liger_kernel.sh, tests/e2e/run_qwen_gsm8k_model_rm_no_rmpad.sh, tests/e2e/run_qwen_gsm8k_model_rm_seq_balance.sh, tests/e2e/run_qwen_gsm8k_model_rm_ulysses.sh, verl/trainer/config/ppo_trainer.yaml, verl/utils/fsdp_utils.py, verl/workers/fsdp_workers.py
- Fixed FSDP1 model offload
- With `actor_rollout_ref.actor.fsdp_config.param_offload=True \` and `actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \ `. The GPU memory utilization can increase to 0.9
- With actor, critic and reference offload all enabled, there will only be one model copy at a time in the GPU memory. Therefore, we can further increase the `micro_batch_size_per_gpu` or `max_token_per_gpu`
**Specifically:**
- During rollout, only rollout model and KVCache are in the GPU memory.
- During critic compute values, only the critic model will stay in the GPU memory while its optimizer and other model states are in CPU main memory
- During actor update, the actor model, optimizer are stored on GPU while the reference model and critic model, critic optimizer are offloaded …
=> [misc] feat: support offload parameter and optimizer during rollout

verl/utils/fsdp_utils.py
Avoid CPU-to-device loading or offloading when the optimizer is not initialized to prevent the incorrect creation of the optimizer.state
=> fix: fix offload/load optimizer impl

requirements.txt
This PR adds Ray Serve to the requirements to enable support for multi-node training. It addresses the issue described here:  https://github.com/volcengine/verl/issues/87#issuecomment-2659493418
=> [misc] Add Ray Serve to requirements to support multi-node training

.github/workflows/vllm.yml, tests/generation/run_gen_qwen05.sh, verl/trainer/config/generation.yaml, verl/trainer/main_generation.py
fix the issue[#331](https://github.com/volcengine/verl/issues/331)
=> [fix] Improve the params template for generation

.github/workflows/model.yml, tests/model/test_transformers_ulysses.py, verl/models/transformers/llama.py, verl/models/transformers/monkey_patch.py, verl/models/transformers/qwen2.py
close #312 
Add support for ulysses sp for transformers >= 0.48
I've tested transformers 0.45.0, 0.46.0, 0.47.0, 0.48.0 and 0.49.0, using sp=2 with the following script in my local env
```bash
#!/bin/bash
set -ex
VERSIONS=("4.45.0" "4.46.0" "4.47.0" "4.48.0" "4.49.0")
for version in "${VERSIONS[@]}"; do
echo "Testing with Transformers version ${version}"
echo "----------------------------------------"
pip install "transformers==${version}"
PYTHONPATH=./ torchrun --nproc_per_node=2 tests/model/test_transformers_ulysses.py
echo "----------------------------------------"
echo "Completed testing for version ${version}"
echo ""
done
```
=> feat: add support for ulysses sequence parallel for transformers >= 0.48

pyproject.toml, requirements.txt, setup.py, verl/trainer/ppo/ray_trainer.py
Try to resolve this [issue](https://github.com/volcengine/verl/issues/356).
As suggested by this issue discussion, I replace default DataLoader with StatefulDataloader, which provides state_dict and load_state_dict methods that may support resuming the iterator position of mid-epoch checkpointing.
=> [ckpt] replace DataLoader with StatefulDataLoader to support resume training for SequentialSampler 

examples/remax_trainer/run_qwen2.5-3b_seq_balance.sh, examples/remax_trainer/run_qwen2.5-7b_seq_balance.sh
The current training script utilizes the same file during training and evaluation. It is surmised that this may be incorrect.
=> [fix] Fix evaluation file path in remax training scripts.

docs/README_vllm0.7.md, verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
Because of the ongoing updates in vLLM, I noticed that veRL currently cannot integrate with the nightly build of vLLM directly. The new DP feature in the nightly version can no longer be bypassed by simply adjusting the `data_parallel_size` parameter, and resolving this requires further investigation.
As a temporary workaround, I recommend a customized installation of vLLM if the V1 engine is required. I have updated the relevant documentation accordingly to reflect this guidance.
=> Update vLLM>=0.7 doc

.readthedocs.yaml, README.md, docs/faq/faq.rst, docs/requirements-docs.txt, verl/protocol.py
=> docs: add hf ckpt to faq, and include verl apis in the website

verl/single_controller/base/worker.py
Specify the IP address when calling the bind method.
=> fix: bind the port with IP address

.github/workflows/e2e_vlm_geo3k.yml, .gitignore, examples/data_preprocess/geo3k.py, examples/grpo_trainer/run_qwen2_5_vl-7b.sh, scripts/model_merger.py, setup.py, tests/e2e/run_qwen2vl_geo3k_function_rm.sh, verl/models/registry.py, verl/models/transformers/qwen2_vl.py, verl/third_party/vllm/vllm_spmd/dtensor_weight_loaders.py, verl/trainer/config/ppo_trainer.yaml, verl/trainer/main_ppo.py, verl/trainer/ppo/ray_trainer.py, verl/utils/checkpoint/checkpoint_manager.py, verl/utils/checkpoint/fsdp_checkpoint_manager.py, verl/utils/dataset/rl_dataset.py, verl/utils/flops_counter.py, verl/utils/reward_score/__init__.py, verl/utils/reward_score/geo3k.py, verl/utils/tokenizer.py, verl/workers/actor/dp_actor.py, verl/workers/critic/dp_critic.py, verl/workers/fsdp_workers.py, verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py, verl/workers/sharding_manager/fsdp_vllm.py
This PR migrates the feature of RL on VLMs in our implementation in [EasyR1](https://github.com/hiyouga/EasyR1) fork back to veRL. We have validated this feature using Qwen2.5-VL 7B model on 8*H100 GPUs. The configuration and data processing script are provided along this PR for easy reproducing.
1. Download and preprocess the dataset
```bash
python3 examples/data_preprocess/geo3k.py --local_dir ~/data/geo3k
```
2. Start GRPO training
```bash
bash examples/grpo_trainer/run_qwen2_5_vl-7b.sh
```
- vllm>=0.7.3
- transformers>=4.49.0
- [qwen-vl-utils](https://pypi.org/project/qwen-vl-utils/)
- [mathruler](https://pypi.org/project/mathruler/)
In this PR, we introduce two new concepts in the dataflow, `multi_modal_data` and `multi_modal_inputs`. The former means the multi-modal features …
=> [feat] Initial support for VLMs, add Qwen2.5VL GRPO example

verl/utils/dataset/rl_dataset.py, verl/utils/reward_score/geo3k.py
Similar to https://github.com/hiyouga/LLaMA-Factory/issues/7125
Change the downsample strategy from nearest to bicubic
=> [fix] use bicubic resampler for resizing image

verl/workers/reward_manager/prime.py
In the `naive` mode, passing `extra_info` information for reward function calculation is supported(https://github.com/volcengine/verl/pull/266), but the support for the `prime` mode is missing. This will cause the reward functions that use `extra_info` to fail to produce correct results in the `prime` mode. This commit fixes this issue.
@PeterSH6 @vermouth1992 @hiyouga or other people who have the authority?
=> [fix] support for extra_info in prime mode

examples/split_placement/split_monkey_patch.py, scripts/format.sh, verl/trainer/fsdp_sft_trainer.py, verl/trainer/ppo/ray_trainer.py
This PR solves these 2 following problems.
1. Last step skipped
`self.global_steps += 1` before if `self.global_steps >= self.total_training_steps` makes the last step skipped.
We start from step 1, and we expect `self.total_training_steps` in total. 
https://github.com/volcengine/verl/blob/82b38e25c72e1b6de7d7d2092af6e1ed5dd2a400/verl/trainer/ppo/ray_trainer.py#L999-L1001 
When `self.global_steps == self.total_training_steps-1`:
* we have only executed `self.total_training_steps-1` steps
* `self.global_steps` is updated to `self.total_training_steps`
* `self.global_steps >= self.total_training_steps` is satisfied, and the training ends.
Therefore, we should put `self.global_steps += 1` at last
2. redundant validation and logging
If  `self.total_training_steps % …
=> fix: (1) skipped last step (2) redundant validation and logging

verl/utils/reward_score/prime_math/__init__.py
Since searching for an appropriate `simplify` algorithm may cause `sympy.simplify` to timeout, and `ProcessPool` may get stuck due to excessive concurrency, the timeout mechanism in `verl/verl/workers/reward_manager/prime.py` cannot capture the timeout. To address this issue, a timeout detection mechanism is added to `verl/verl/utils/reward_score/prime_math/__init__.py` for `sympy.simplify` to solve it easily.
=> Resolve the issue of PRIME getting stuck during math verification.

.github/workflows/dataset.yml, .github/workflows/e2e_digit_completion.yml, .github/workflows/e2e_gsm8k.yml, .github/workflows/e2e_gsm8k_megatron.yml, .github/workflows/e2e_lora.yml, .github/workflows/e2e_sft.yml, .github/workflows/ray_test.yml, .github/workflows/sandbox.yml, .github/workflows/sanity.yml, .github/workflows/vllm.yml, .github/workflows/yapf_format.yml
Note: we leave out `secrets_scan.yml` and `scorecard.yml` to avoid any possible leakage or security risk, which also cost little.
=> [CI] feat: auto cancel previous CI in the same PR

.github/workflows/e2e_gsm8k.yml, docs/examples/config.rst, docs/preparation/reward_function.rst, tests/e2e/check_custom_rwd_fn.py, tests/e2e/run_qwen_gsm8k_custom_function_rm.sh, verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/config/ppo_trainer.yaml, verl/trainer/main_ppo.py
This PR is inspired by https://github.com/volcengine/verl/issues/446 and https://github.com/volcengine/verl/pull/162.
Though https://github.com/volcengine/verl/pull/162 tried to enable users to directly pass in a customized reward function, https://github.com/volcengine/verl/issues/446 thought *the `compute_score` parameter in the file `main_ppo.py` is always set to None and cannot be revised other than editing the source code*. 
https://github.com/volcengine/verl/blob/65cceb3c9dbe6e18230bc3dc045af6e3280c9752/verl/trainer/main_ppo.py#L23-L39
I found that in `main` we cannot specify our customized reward function, so the parameter `compute_score` in both `run_ppo` and `main_task` cannot take effect because `main` doesn't pass `compute_score` to `run_ppo`.
In order to enable users to try …
=> feat: support loading reward function from an external file

verl/workers/fsdp_workers.py
When running `main_generation.py`, `ActorRolloutRefWorker` is initialized with `role='rollout'` and its `optim_config` would be set to None in `init_model`.
`_build_model_optimizer` should handle this.
=> fix `_build_model_optimizer` when role is rollout, whose `optim_config` is None

verl/utils/dataset/rl_dataset.py
[bugfix] Fix position embedding processing for Qwen2.5-VL
In the `RLHFDataset.__getitem__` method, a bug was identified in how multimodal position IDs (3D in Qwen2.5-VL) are determined. Previously, the code checked for `self.image_key in row_dict` to decide whether to use multimodal position IDs. However, since `self.image_key` is popped from `row_dict` during image token expansion, this check incorrectly fails for subsequent operations.
This causes the VL model to use incorrect position IDs, resulting in significant performance degradation. 
The fix introduces an explicit `is_multi_modal` flag to properly track multimodal content throughout the processing pipeline.
=> [bugfix] Fix position embedding processing for Qwen2.5-VL

verl/workers/fsdp_workers.py
assert ppo_mini_batch_size > 0 after normalized, could avoid batch.split(self.config.ppo_mini_batch_size) endless loop when ppo_mini_batch_size is 0. It may cause update policy model stuck when pre process data.
loop in tensor_dict.split: 
```
while idx1 < max_size:
idx0 = idx1
idx1 = min(max_size, idx1 + split_size)  # will always be 0 when split_size is 0
split_sizes.append(slice(idx0, idx1))
batch_sizes.append(
torch.Size(
tuple(
d if i != dim else idx1 - idx0
for i, d in enumerate(batch_size)
)
)
)
```
=> [misc] add assertion for normalized ppo_mini_batch_size

verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/config/ppo_trainer.yaml, verl/trainer/ppo/ray_trainer.py, verl/workers/rollout/vllm_rollout/vllm_rollout.py, verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
Currently, eager mode is applied in the validation stage. However, in some reasoning tasks, we may need to generate n times and average the scores.
In this PR, we support using non-eager sampling parameters during validation by specifying the `val_kwargs` in `actor_rollout_ref.rollout` config field.
**Future work**
=> [rollout] feat: support sampling in validation stage

recipe/prime/prime_fsdp_workers.py, verl/workers/fsdp_workers.py, verl/workers/sharding_manager/fsdp_vllm.py
#556 take effort to remove remove unnecessary empty_cache, but will cause CUDA oom at vllm wake_up.
```text
File "/opt/tiger/ray/session_2025-03-13_12-11-30_408315_2895/runtime_resources/working_dir_files/_ray_pkg_a64b690733067c5c/verl/workers/fsdp_workers.py", line 481, in generate_sequences
with self.rollout_sharding_manager:
File "/opt/tiger/ray/session_2025-03-13_12-11-30_408315_2895/runtime_resources/working_dir_files/_ray_pkg_a64b690733067c5c/verl/workers/sharding_manager/fsdp_vllm.py", line 82, in __enter__
self.inference_engine.wake_up()
File "/usr/local/lib/python3.11/dist-packages/vllm/entrypoints/llm.py", line 1244, in wake_up
self.llm_engine.wake_up()
File "/usr/local/lib/python3.11/dist-packages/vllm/engine/llm_engine.py", line 1859, in wake_up
self.model_executor.wake_up() …
```
=> fix: remove redundant torch.cuda.empty_cache()

docs/examples/config.rst, verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/config/ppo_trainer.yaml, verl/workers/actor/dp_actor.py
Providing an option in the config to turn off the `torch.compile` used in `dp_actor.py`
Adding the following line to the driver or cli scripts to turn off `torch.compile`.
```python
+actor_rollout_ref.actor.use_torch_compile=False
```
Otherwise, `torch.compile` will be used by default
#354 #245
=> [Config] Providing an option to turn off `torch.compile` in actor

verl/trainer/config/generation.yaml
I try to delete some params base on #542 and #322.
Theoretically speaking, the actor parameters should be unnecessary. However, I've found that when initializing the `actor_rollout`, some parameters are required. It should be possible to solve this problem by adding more judgment conditions. I'm not sure if there are any more suggestions or if we should just keep the current situation.
=> [update] delete useless config params

verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/config/ppo_trainer.yaml
=> [misc] feat: add weight decay option in config

verl/trainer/ppo/ray_trainer.py, verl/workers/rollout/vllm_rollout/vllm_rollout.py, verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
**Summary**
- During validation, when the validation rollout response num is larger than 1, we should first repeat it and then feed them into the rollout.
- If we only set the `n` in sampling_params of the rollout engine, some padding data will generate `n` responses. This overhead is unnecessary. So, we repeat the test_batch first before rollout.
**Future work**
=> [misc] fix: validation batch repeat before feed into rollout

pyproject.toml, requirements.txt, setup.py, verl/utils/reward_score/__init__.py, verl/utils/reward_score/math_verify.py
https://github.com/volcengine/verl/issues/680
Changes:
- Move math-verify to the optional dependencies. Now it can be installed via `cd verl && pip install -e .[math]`
- Revert using naive verifier for math dataset. Users can switch to math-verify or custom a new `compute_score` function.
=> Make Math-Verify Optional

verl/utils/tracking.py
Add `verl` as the `framework` parameter to the SwanLab config table, so more developers can see that this training comes from `verl`.
=> [tracking] swanlab add `verl` config

verl/models/transformers/llama.py, verl/models/transformers/qwen2.py, verl/models/transformers/qwen2_vl.py, verl/utils/ulysses.py
Prevents training hangs by validating `num_key_value_heads % ulysses_sequence_parallel_size == 0` before training.
=> [misc] Add Ulysses parallel config precheck

verl/trainer/ppo/ray_trainer.py, verl/utils/checkpoint/fsdp_checkpoint_manager.py
This PR addresses an issue with checkpoint loading by explicitly setting `weights_only=False` in the `torch.load` function calls. This change is necessary because torch 2.6 changed the default value of the `weights_only` parameter from `False` to `True`, causing unpickling errors when loading checkpoints containing numpy arrays.
Changes:
- Modified `torch.load` call in `fsdp_checkpoint_manager.py` to explicitly set `weights_only=False`
- Modified `torch.load` call in `ray_trainer.py` line 739 to explicitly set `weights_only=False` for dataloader state loading
The fix is minimal and only affects the checkpoint loading functionality while ensuring compatibility with torch 2.6.
=> Fix checkpoint loading in fsdp_checkpoint_manager.py and ray_trainer.py

verl/workers/reward_manager/naive.py
it should skip special tokens here. just like trl do https://github.com/huggingface/trl/blob/fc2b041b58f6fbe766dceaec819bc5a8f9d209da/trl/trainer/grpo_trainer.py#L597
if `skip_special_tokens=False`,  completion 
```
<think>...</think><answer>....</answer>
```
will be decoded as things such as
```
<think>...</think><answer>....</answer><|im_end|><|endoftext|>
```
which will render typical `format_reward_func` mismatch
```python
r"^<think>.*?</think>\s*<answer>.*?</answer>$"
```
=> skip special tokens

verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
Related to this issue https://github.com/volcengine/verl/issues/673
Make vllm_rollout_spmd.py (https://github.com/volcengine/verl/blob/main/verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py#L110) behavior on max_model_len configuration to be consistent with vllm_rollout.py (https://github.com/volcengine/verl/blob/main/verl/workers/rollout/vllm_rollout/vllm_rollout.py#L110).
=> [Bug fix] change max_model_len to be configurable in vllm_rollout_spmd

verl/utils/checkpoint/megatron_checkpoint_manager.py, verl/utils/model.py
As transformers `from_pretrained()`  automatically load ckpt in the default torch.dtype (here, fp32) and not follow the  dtype of the weights themselve, it often causes high CPU memory usage even OOM, which crushes the training. 
Follow by  https://github.com/huggingface/transformers/issues/34743 and tested on loading Llama-3.1-405B-Instruct. 
```
- model = AutoModelForCausalLM.from_pretrained(model_file)
+ model = AutoModelForCausalLM.from_pretrained(model_file, torch_dtype="auto")
```
Some CPUs can not support `bfloat16` and it might take some time to convert back to `float32`.
=> fix: set torch dtype to auto

examples/grpo_trainer/run_deepseek7b_llm.sh, examples/grpo_trainer/run_deepseek7b_llm_math.sh, examples/grpo_trainer/run_deepseek7b_llm_math_megatron.sh, examples/grpo_trainer/run_deepseek7b_llm_megatron.sh, examples/grpo_trainer/run_deepseek7b_llm_seq_balance.sh, examples/grpo_trainer/run_qwen2-7b.sh, examples/grpo_trainer/run_qwen2-7b_math.sh, examples/grpo_trainer/run_qwen2-7b_math_megatron.sh, examples/grpo_trainer/run_qwen2-7b_megatron.sh, examples/grpo_trainer/run_qwen2-7b_seq_balance.sh, examples/grpo_trainer/run_qwen2_5_vl-7b.sh
The existing example GRPO scripts rely on the default configuration in `verl/trainer/config/ppo_trainer.yaml` and set the entropy_coeff to 0.001. This behavior doesn't match what's described in the GRPO paper and is quite hard to notice. In my experiments, it might be causing an entropy explosion, which results in poor performance.
=> In the GRPO example scripts, modify the `entropy_coeff` to 0 to ensure consistency with the GRPO paper.

verl/workers/rollout/sglang_rollout/sglang_rollout.py
Fixed a portion of the issues encountered during VLM GPTO training as mentioned in the article. 
https://github.com/zhaochenyang20/Awesome-ML-SYS-Tutorial/blob/main/rlhf/verl/veRL-VLM.md
When do_sample=False, different models under DP output sequences of inconsistent lengths, which may be padded to different lengths, ultimately causing shape inconsistencies during output and resulting in errors in collect_dp_compute_data_proto. The following situation occurred: 
```
DataProto(batch=TensorDict(
fields={
attention_mask: Tensor(shape=torch.Size([151, 5120]), device=cpu, dtype=torch.int64, is_shared=False),
input_ids: Tensor(shape=torch.Size([151, 5120]), device=cpu, dtype=torch.int64, is_shared=False),
position_ids: Tensor(shape=torch.Size([151, 5120]), device=cpu, dtype=torch.int64, …
```
=> Fix padding length for sglang rollout in veRL

docs/start/install.rst
Modify the version number of Megatron-llm from ``core_v0.11.0`` to ``core_r0.11.0``
=> Fix typo on installation guide

examples/split_placement/config/ppo_trainer_split.yaml, verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/config/ppo_trainer.yaml, verl/trainer/ppo/ray_trainer.py, verl/utils/tracking.py
- Add mlflow validation generation in `ValidationGenerationsLogger` in the form of MLFlow artifact files.
- Add the config of `MLFLOW_TRACKING_URI` in mlflow tracking. 
- rename `val_generations_to_log_to_wandb` to `log_val_generations`
Tested in the self-host mlflow servers.
=> [BREAKING config] feat: add mlflow val generation log and uri config

docs/examples/config.rst, tests/e2e/check_results.py, tests/e2e/run_ray_trainer_fire_sampling.sh, tests/verl/utils/dataset/test_sft_dataset.py, verl/trainer/config/sft_trainer.yaml, verl/trainer/fsdp_sft_trainer.py, verl/utils/dataset/sft_dataset.py, verl/utils/import_utils.py
This PR breaks the SFTDataset interface, but provides more flexibility on dataset type and arguments passed in.
Usage:
```
--data.custom_cls.path=/path/to/dataset.py --data.custom_cls.name=MyDataset
```
=> [BREAKING] feat: support custom datasets for SFT trainer

verl/trainer/main_generation.py, verl/trainer/main_ppo.py
This parameter is required during the custom tokenizer loading phase, for example, when using `moonshotai/Moonlight-16B-A3B-Instruct`. And since the tokenizer falls under the configuration of data, I placed it under `config.data`.
=> [misc] add trust_remote_code param for loading custom tokenizer

verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/config/ppo_trainer.yaml, verl/trainer/ppo/core_algos.py, verl/workers/actor/dp_actor.py, verl/workers/actor/megatron_actor.py
Add the [Dual-Clip PPO](https://arxiv.org/pdf/1912.09729) algorithm to enhance the current PPO implementations. The Dual-Clip PPO introduces a approach by applying a lower bound to the policy ratio when the advantage is less than zero, when multiplied by a huge raito, does not exceed a specified lower bound. The concept is illustrated in the figure below:
So, the finall loss of the ppo is 
This adjustment leads to a modified final loss calculation for the PPO, which could potentially improve training stability and performance in certain scenarios. I believe integrating this feature could provide significant benefits, and I look forward to feedback on this suggestion.
=>  Implement Dual-Clip PPO Algorithm

verl/utils/flops_counter.py
The MFU has been tested with the relevant model and can be calculated normally.
=> [fix] add dpsk v3 type in config for mfu compute

verl/workers/megatron_workers.py
Hi there, when using both megatron and `actor_rollout_ref.rollout.name=hf`, the NotImplementedError is not raised. The PR fixes it.
```
(TaskRunner pid=229016)   File "/root/verl/verl/workers/megatron_workers.py", line 285, in _build_rollout                                                                            
(TaskRunner pid=229016)     return rollout, sharding_manager                                                                                                                         
(TaskRunner pid=229016) UnboundLocalError: local variable 'rollout' referenced before assignment 
```
=> fix: the error is not raised when using both megatron and hf inference

tests/rollout/test_vllm_spmd.py
I tested the `Deepseek-7B-chat` and `Qwen2-7B` these two models, the former showed a 0% difference in output, while the latter exhibited a 10.25% difference in output, with no significant issues in the output. So I manually adjusted the error tolerance to 15%. I’m not sure if this will work.
=> [test]: update vllm_spmd test for > 0.7.3

.vscode/settings.json
This PR adds default VSCode repo settings to help keep consistent with the CI, which:
1. enable the `pylint` linter extension
2. set the default formatter as `yapf`
3. but don't organize imports for now (since we haven't got a functionality for this)
=> [dev] feat: default VSCode repo settings to help consistency with CI

docs/amd_tutorial/amd_build_dockerfile_page.rst, docs/start/install.rst, recipe/prime/prime_ray_trainer.py, requirements.txt, requirements_sglang.txt, setup.py, verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/config/ppo_trainer.yaml, verl/trainer/ppo/ray_trainer.py, verl/utils/dataset/rl_dataset.py
HF Dataset provides better memory management and can handle larger datasets. It also supports multi-process acceleration during map/filter operations (while pandas requires version >2.0).
Now we can specify `filter_overlong_prompts` on large-scale datasets when set `filter_overlong_prompts_workers` to a appreciate num.
=> refactor: use hf Dataset instead of pandas DataFrame in RLHFDataset

docs/workers/ray_trainer.rst, recipe/prime/prime_ray_trainer.py, verl/trainer/ppo/ray_trainer.py, verl/utils/dataset/rl_dataset.py
`filter_prompts` has never been used, I think this parameter has been replaced by `filter_overlong_prompts` so we can simply remove this.
=> refactor: remove unused filter_prompts parameter from RLHFDataset

verl/utils/reward_score/math_verify.py
`math_verify.errors.TimeoutException` can not be caught as `Exception`.
```python
In [1]: import math_verify
In [2]: issubclass(math_verify.errors.TimeoutException, Exception)
False
In [3]: issubclass(math_verify.errors.TimeoutException, BaseException)
True
```
=> [math-verify] fix: TimeoutException

scripts/diagnose.py, verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
In version 0.8.2, forgetting to add `dummy` parameter resulted in repeated loading.  And it also needs to be compatible with the default parameter `dummy_dtensor`.
=> [fix] Skip vllm initialization with weight loading

tests/rollout/test_vllm_spmd.py, verl/workers/sharding_manager/fsdp_vllm.py, verl/workers/sharding_manager/patch/__init__.py, verl/workers/sharding_manager/patch/fsdp_vllm_patch.py
This is a solution to an error that occurs when vLLM 0.8.2 loads models in the ds_v3 MoE format. For MoE models, directly calling vLLM's `load_weights· function will result in an error, primarily because the model params lose the related methods of the `FusedMoe` class. Therefore, it is necessary to identify and call the specific parameter loading method based on the model parameter names at runtime. However, the current version is a dirty implementation because, in reality, if invasive changes were made to vLLM, it would only require modifying 2 lines of code and adding a new function to identify the layer count (I have already marked comments in the code). I’m not sure if there’s a better implementation and would like some suggestions.
=> [feat] enable FSDP and vLLM 0.8.2 to support DPSK v3 training.

verl/trainer/config/ppo_megatron_trainer.yaml, verl/workers/megatron_workers.py
Add gradient checkpointing (aka `activation recomputation`) config and support from Megatron core (https://github.com/NVIDIA/Megatron-LM/blob/b7ec711cf66cf500b98d8783f2c7f3c3a7d5ba31/megatron/core/transformer/transformer_config.py#L208-L233) to make activation checkpointing more efficient for LLMs with 20B+ parameters.
```
gradient_checkpointing_kwargs:
activations_checkpoint_method: null
activations_checkpoint_granularity: null
activations_checkpoint_num_layers: null
```
Tested on loading Qwen7b/32b of 16k input prompts and bypass the OOM issues after adding gradient checkpointing. 
Add one `ppo_trainer for megatron` doc to explain the config details in  https://verl.readthedocs.io/en/latest/examples/config.html
=> feat: add gradient checkpointing in megatron backend

scripts/model_merger.py
As mentioned in https://github.com/volcengine/verl/issues/903, the model_merger script has some problem when dealing with saved fsdp checkpoint trained with `trainer.n_gpus_per_node=1`.  The loaded `weight` is of type `Tensor` instead of `DTensor`. This PR supported this situation.
=> fix: support non-DTensor when converting fsdp checkpoints to hf model

docs/examples/config.rst, verl/single_controller/ray/base.py, verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/config/ppo_trainer.yaml, verl/trainer/ppo/ray_trainer.py
As mentioned in #491, the `register_center` named actor could be `None` after 2mins waiting time and crash the job for some verl users. 
This might be due to (1) uncleaned ray resources from previous runs; or (2) too short waiting time of 120s if the `named_actor` launching task is delayed in the cluster.
This PR makes the `register_cetner` named actor waiting time configurable and longer by default . This PR also provides better error info to help users to self debug the issue.
#491
=> [Enhancement] Make `register_center` named actor waiting time configurable & providing better error info

verl/trainer/ppo/core_algos.py
Currently, `pg_clipfrac_lower` is always 0 by mistake.
=> fix: wrong pg_clipfrac_lower

verl/workers/fsdp_workers.py
This PR suggest a fix on a bug that when `_switch_chat_template()` method is called. 
According to
https://github.com/volcengine/verl/blob/main/verl/utils/dataset/rl_dataset.py#L222 
`data.non_tensor_batch['raw_prompt'][i]` is already a list if `data.return_raw_chat=True`.
Calling `.tolist()` again will result an error. Now we check if it is a list before run this method.
=> Change behaviour during raw prompt extraction

scripts/model_merger.py, verl/workers/sharding_manager/fsdp_vllm.py
This is a memory optimization method implemented based on this [fix](https://github.com/vllm-project/vllm/pull/15500). I just successfully ran a 72B model on 8*H800 cards. Before the fix, I would encounter an OOM issue. Please note that this fix is only effective for vLLM >= 0.8.3.
=> [vllm] fix oom when vllm wakeup (vllm >=0.8.3)

verl/protocol.py
Use `packaging.version` to compare tensordict's version instead of string comparing, string comparing sometimes will fail, for example, "0.10.0" < "0.5.0" when using string comparing.
Also remove a unnecessary return_type since this return_type will always be `DataProtoItem`.
=> fix: use packaging to compre versions instead of str comparing

verl/trainer/ppo/ray_trainer.py
This PR
1. fixes the problem that important metrics like `"mean@{n}"` can not be recognized as `val-core` due to lack to `/...` at the end
2. removes `"std@{n}"` from `val-core`
=> [log] fix: val-core pattern

verl/utils/checkpoint/megatron_checkpoint_manager.py, verl/utils/megatron_utils.py
Only 1 node in a machine save rng_states to avoid conflicts and read properly
New version of torch.save can cause races here.
FSDP also split the rng_states in extra states
=> fix checkpoint rng_states confliction

verl/utils/tracking.py
Fix MLflow metric name errors by replacing '@' with '_at_' during MLflow logging
MLflow rejects metric names with '@' as below
`mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Invalid metric name: 'val-aux/semantic_matching/reward/mean@1'. Names may only contain alphanumerics, underscores (_), dashes (-), periods (.), spaces ( ), and slashes (/).`
=> fix: replace '@' with '_at_' in metric names to comply with MLflow naming constraints

verl/single_controller/base/worker_group.py, verl/single_controller/ray/base.py
- Force both usages of `colocate` and `collocate` to `colocate`, to be consistent with [vllm terminology](https://docs.vllm.ai/en/latest/getting_started/examples/rlhf_colocate.html).
- both `ResourcePool` and `RayResourcePool` use the same default value for `max_colocate_count` to avoid surprises.
=> [misc] Fix typo in colocate

docs/examples/config.rst, verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/config/ppo_trainer.yaml, verl/workers/rollout/vllm_rollout/vllm_rollout.py
When training big model and/or super-long seq len using vLLM rollout, you may encounter the error
```
...
in _swap_out raise RuntimeError( RuntimeError: Aborted due to the lack of CPU swap space. Please increase the swap space to avoid this error
``` 
(updated)This can be fixed by setting bigger `swap_space` for vLLM.  E.g., in your training bash you can do the
```
...
actor_rollout_ref.rollout.engine_kwargs.swap_space=32 \
...
```
which sets the swap_space to 32GB. Note in most vLLM releases the default value is 4GB.
=> add rollout config swap_space for vllm_rollout

.github/workflows/dataset.yml, tests/rollout/test_vllm_spmd.py, tests/verl/utils/dataset/test_rl_dataset.py, verl/utils/dataset/rl_dataset.py, verl/utils/torch_functional.py, verl/workers/fsdp_workers.py, verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
In this PR, we use huggingface's chat template (i.e., `processor.apply_chat_template`) to compute input ids for VLMs, it could be generalized to more model architectures compared with the earlier implementation.
@vermouth1992 @eric-haibin-lin
=> data: use hf template for vlm models

recipe/dapo/src/config/dapo_trainer.yaml, verl/trainer/config/ppo_trainer.yaml, verl/utils/dataset/rl_dataset.py, verl/utils/dataset/vision_utils.py, verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
Adds video input support for qwen2 vl models
- process_image function is moved to vision_utils.py
- switch process_image & process_video to both use fetch_image and fetch_video functions from qwen-vl-utils
- fixed a mrope bug in vllm rollout
=> [feat] video inputs

docs/examples/config.rst, verl/trainer/config/sft_trainer.yaml, verl/trainer/fsdp_sft_trainer.py, verl/utils/torch_functional.py
This PR adds a new learning rate scheduler called WSD (Warmup-Stable-Decay) that provides more control over the learning rate schedule during training. The WSD scheduler extends the traditional cosine scheduler by adding a stable phase where the learning rate remains constant.
- **Three-phase schedule**: Warmup → Stable → Decay
- **Configurable stable phase**: Control what percentage of training maintains a constant learning rate
- **Compatible with existing code**: Minimal changes to the trainer infrastructure
- **Default to cosine**: Maintains backward compatibility with existing configurations
1. Added `get_wsd_schedule_with_warmup` function to `verl/utils/torch_functional.py`
2. Updated the SFT trainer to support the new scheduler type
3. Added `lr_scheduler: cosine` as the default in …
=> Add WSD (Warmup-Stable-Decay) scheduler for SFT

docs/workers/sglang_worker.rst
if we use sglang as the rollout engine, we should export SGL_DISABLE_TP_MEMORY_INBALANCE_CHECK to avoid that the memory capacity is unbalanced, please refer to [#5426 in sglang](https://github.com/sgl-project/sglang/pull/5426)
1. verl initializes a SGlangRollout module during rollout, which is used to evaluate/generate samples.
2. SGLangRollout will initialize VerlEngine, further initialize a torch. Distributed. DeviceMesh, used to support the TP.
3. DeviceMesh.init () internally checks the free video memory of all participating devices, and if the difference is too large (more than about 10%), it directly reports an error, preventing initialization failures or communication deadlock.
verl uses ray multi-process multi-gpu concurrent training, and each `WorkerDict` may be called at …
=> Doc: add a environment to fix that the memory capacity is unbalanced

verl/utils/ulysses.py
DeepSpeed has moved to `deepspeedai` repo.
=> change deepspeedai url site.

verl/trainer/main_ppo.py
Use the 'from e' inside the try-except statement to keep the stack trace of the error
=> refactor: use 'from e' for exception stack trace

README.md, docs/index.rst, examples/split_placement/split_monkey_patch.py, recipe/dapo/src/dapo_ray_trainer.py, verl/models/mcore/model_initializer.py, verl/trainer/ppo/core_algos.py, verl/trainer/ppo/ray_trainer.py, verl/utils/megatron_utils.py, verl/workers/megatron_workers.py
Our pre-commit hook and CI action only check the changes for now.
In this PR,
1. We apply `ruff check --fix` and `ruff format`.
2. We remove the unnecessary pipeline from the immigration warning, since directly merging without applying `ruff`, which might cause extra conflicts, is the best way to avoid introducing extra file changes.
=> [dev] fix: instructions about merging from before using ruff

recipe/prime/prime_fsdp_workers.py, verl/utils/debug/__init__.py, verl/utils/debug/performance.py, verl/utils/logger/aggregate_logger.py, verl/workers/actor/dp_actor.py, verl/workers/actor/megatron_actor.py, verl/workers/critic/dp_critic.py, verl/workers/critic/megatron_critic.py, verl/workers/fsdp_workers.py, verl/workers/megatron_workers.py, verl/workers/rollout/sglang_rollout/sglang_rollout.py, verl/workers/rollout/vllm_rollout/vllm_rollout.py, verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py, verl/workers/sharding_manager/fsdp_sglang.py, verl/workers/sharding_manager/fsdp_vllm.py, verl/workers/sharding_manager/megatron_vllm.py
Use wrapper to refactor logging GPU memory enter or exit a function.
Simply use `VERL_LOGGING_LEVEL=DEBUG` to open current implemented memory logger wrapped around common functions.
=> Log gpu mem refactor

tests/e2e/run_ray_trainer.sh, tests/e2e/run_ray_trainer_fire_sampling.sh, verl/workers/fsdp_workers.py
original assertion is inside `if`, only executed when `ppo_micro_batch_size` is not None, and otherwise may results in NaN when training
Related to [Issue #405](https://github.com/volcengine/verl/issues/405) and [PR #382](https://github.com/volcengine/verl/pull/382).
=> fix: update assertion of ppo_mini_batch_size and ppo_micro_batch_size_per_gpu

README.md, docs/amd_tutorial/amd_vllm_page.rst
Add AMD performance tuning documentation including:
1. vLLM patch for sleep mode on AMD GPUs
2. Workarounds for CUDA graph capture issues in ROCm
=> [AMD] Add AMD performance tuning documentation

tests/utility/test_tensor_dict_utilities.py, verl/protocol.py
After the last change, current DataProto cannot use bool-type index due to hard-coded batch_size equal to idxs.shape[0]. 
This patch changes the new batch_size for bool-type idx to idxs.sum(). It's useful when users filter the batch with bool-type masks.
=> Add bool-type index selection for DataProto

tests/rollout/test_hf_rollout.py, verl/workers/rollout/hf_rollout.py
Currently, the hf rollout backend only support `rollout.n == 1`, when `rollout.n > 1` it will lead to an error (https://github.com/volcengine/verl/issues/1134)
This PR make hf rollout support `do_sample` and `is_validate` to make it consistent with vllm and sglang backend, and correctly support `rollout.n > 1`.
=> feat: support rollout.n > 1 in hf_rollout

scripts/model_merger.py
https://github.com/volcengine/verl/blob/afeac9a0230a0980e990a3c59e08e8e0890baaa4/scripts/model_merger.py#L195-L200
Model created by `from_config` won't load the `generation_config.json` from `args.hf_model_path`, instead it create a generation config separately.
This inconsistency will lead to strange generating error when user using vllm/hf rollout without carefully override sampling_params/generation_config, see issue here: https://github.com/volcengine/verl/issues/1246
This PR introduce a `patch_model_generation_config` function which patch the model from config to correctly use the pretrained generation config. Fix https://github.com/volcengine/verl/issues/1246.
=> [merger] fix: merged generation config is inconsistent with hf pre-trained model 

verl/utils/reward_score/math.py, verl/utils/reward_score/prime_math/math_normalize.py
This PR fixes collapse in the math reward function by catch any possible errors.
- **Issue Number**: None
- **Training**: None
- **Inference**: None
=> fix: catch any error in math reward function

verl/utils/vllm_utils.py
Add moe patch for qwen3-moe. Fix the weight loader issue in vLLM MoE models. This isn’t a permanent solution, and we may need to contribute code to vLLM to address the problem caused by FusedMoE. I’m already seeking suggestions for this.
- Add Qwen3MoeForCausalLM class for moe_patch
=> [vllm] add moe patch for qwen3-moe

examples/rloo_trainer/run_qwen2-7b.sh
`grad_offload` option was removed in #284 for fsdp backend, current script will error out due to this.
- Remove grad_offload in rloo example script
- Run the changed script
- **Issue Number**: N/A
- **Training**: FSDP
- **Inference**: None
=> [fix] Remove grad_offload in rloo example script

tests/e2e/arithmetic_sequence/rl/README.md, tests/e2e/arithmetic_sequence/rl/main_trainer.py, verl/utils/vllm_utils.py
e2e test `arithmetic_sequence` is currently broken, with error `TypeError: not a string` thrown on code `tokenizer = AutoTokenizer.from_pretrained(local_path)` when running `tests/e2e/run_ray_trainer.sh`. This PR aims to fix it.
In the `arithmetic_sequence` task, `tests.e2e.envs.digit_completion` module was imported in the beginning but not used. This import seems meaningless. However, when this library is imported, `AutoTokenizer.register()` will be called to set configurations for `AutoTokenizer`. Only after that can `AutoTokenizer` be successfully initialized in test code to perform subsequent tasks.
- In #934 , to improve CI efficiency, the CI corresponding to `arithmetic_sequence` was removed.
- In #1010 , according to the `unused_import` rule, this import was deleted, triggering the …
=> [test] fix: test arithmetic_sequence failed to run

docs/start/install.rst
There should be no space between `.` and `[vllm]` or `[sglang]`, or it will result in error:
```logs
ERROR: Invalid requirement: '[vllm]': Expected package name at the start of dependency specifier
[vllm]
```
In addition, I rewrite this part to make the instructions more clear (as `.. or ..` can't be executed by bash directly)
- **Issue Number**: none
=> [docs] Fix pip install instructions

docs/experiment/ppo.rst, tests/checkpoint/test_fsdp_ckpt.py, verl/trainer/config/ppo_trainer.yaml, verl/trainer/main_ppo.py, verl/utils/checkpoint/fsdp_checkpoint_manager.py, verl/utils/fsdp_utils.py, verl/workers/actor/dp_actor.py, verl/workers/critic/dp_critic.py, verl/workers/fsdp_workers.py, verl/workers/sharding_manager/fsdp_sglang.py, verl/workers/sharding_manager/fsdp_vllm.py
This PR supports fsdp2 for fsdp_worker. Torch version 2.4 or higher is required.
```
sh examples/grpo_trainer/run_qwen2-7b.sh \
actor_rollout_ref.ref.strategy=fsdp2 \
actor_rollout_ref.actor.strategy=fsdp2 
```
To save more memory, you can add the parameter below to enable the fsdp2 OffloadPolicy:
``` 
actor_rollout_ref.actor.offload_policy=True  
```
You can see the profile comparison between fsdp1 and fsdp2 here:  https://github.com/volcengine/verl/pull/1026#issuecomment-2824343860
=> [fsdp] feat: support fsdp2 training and inference in fsdp_workers

docs/index.rst
Arxiv link is not rendering on github or https://verl.readthedocs.io/en/latest/index.html#
- [x ] Search for similar PR(s).
Makes external link to arxiv paper resolve properly.
N/A
Single line doc change
N/A
N/A
N/A
All N/A
=> Fix Arxiv Link

tests/ray/test_decorator.py, verl/single_controller/base/decorator.py
This PR enables the decorators to be able to be applied onto async functions.
* Simply added a inner wrapper function available for async func inside the `register` function.
```python
@register(dispatch_mode=Dispatch.ONE_TO_ALL, blocking=False)
async def async_fn(self, sleep_time):
return await asyncio.sleep(sleep_time * 0.1)
```
* `tests/ray/test_decorator.py`
=> [feat] Making decorator register available for async function

.github/workflows/dataset.yml, .github/workflows/ray_cpu_test.yml
There are two pipelines fail on the main branch right now, which are `dataset` and `ray_cpu`. This PR tries to recover the two failed ci pipelines.
=> [fix][ci] fix two pipelines that fails on the main branch

.github/workflows/e2e_ppo_trainer.yml, .github/workflows/sgl.yml, docker/Dockerfile.sglang, docs/start/install.rst, docs/workers/sglang_worker.rst, recipe/dapo/src/main_dapo.py, setup.py, verl/trainer/main_ppo.py, verl/workers/rollout/sglang_rollout/sglang_rollout.py
=> [sglang] Upgrade sglang to 0.4.6.post1 & misc fixes

docs/examples/config.rst
This PR update some outdated docs on config:
- Add `filter_overlong_prompts_workers` configuration option, which introduced in #890
- Add documentation for `actor_rollout_ref.rollout.val_kwargs` parameters, fix #1352
- Fix attribution of several configuration options to their proper namespaces
```python
```
- **Training**: [Note which backend this PR will affect: FSDP, …
=> docs: update config documentation with validation parameters

tests/verl/test_decorator.py, verl/single_controller/base/decorator.py, verl/single_controller/base/worker_group.py, verl/utils/py_functional.py
Today, extending `verl` in proprietary usage large requires forking it, and padding code changes in the private fork. 
For example, the current `verl` API doesn't support adding new `Dispatch` and `Execute` mode in runtime. The only way to achieve it is to make a new private fork.
This PR replace the static `Enum` type of `Dispatch` and `Execute` into a new `"DynamicEnum"` type, that the users can use new APIs `register_dispatch_mode` and `update_dispatch_mode` to adding and define new distributed mode at runtime using native `verl` API, instead of making a fork.
* Defined `DynamicEnum` class in `utils.py_functional.py`;
* Re-defined `Dispatch` and `Execute` classes, all existing Enum API and usage are still usbale;
* Added `register_dispatch_mode` and `update_dispatch_mode` for users to …
=> [single_controller][decorator] Define a `DynamicEnum` class to make `Dispatch` and `Execute` extensible.

docs/examples/config.rst, verl/trainer/config/ppo_trainer.yaml, verl/workers/fsdp_workers.py, verl/workers/rollout/sglang_rollout/async_sglang_rollout.py, verl/workers/rollout/sglang_rollout/sglang_rollout.py
Add missing `trust_remote_code` option in customized vllm rollout and sglang rollout, fix https://github.com/volcengine/verl/issues/1412.
- **Issue Number**: https://github.com/volcengine/verl/issues/1412
- **Training**: FSDP
- **Inference**: both
=> [rollout] fix: missing trust_remote_code option in rollout initialization

verl/utils/tracking.py
When user choose swanlab logger and not set config, original code `config={"FRAMEWORK": "verl", **config}` would raise error. This PR try to fix this by init config as an empty dict if it is None
```
if config is None:
config = {} # make sure config is not None, otherwise **config will raise error
swanlab.init(
project=project_name,
experiment_name=experiment_name,
config={"FRAMEWORK": "verl", **config}, # this is the cause of error when config is None
logdir=SWANLAB_LOG_DIR,
mode=SWANLAB_MODE,
)
```
```python
```
> For changes that can not be …
=> [BUG] fix swanlab init bug when config is None

tests/rollout/async_rollout_utils.py, tests/rollout/test_vllm_multi_turn.py, tests/rollout/test_vllm_tool_calling.py, verl/single_controller/ray/base.py, verl/trainer/ppo/ray_trainer.py
Spawned RayWorkerGroup get actors by name, which holds a weak reference to the actor and causes actors garbage collected unexpectedly. Pass actor handle explicitly in spawn to make RayWorkerGroup have strong reference to these actors. close #1365 https://github.com/volcengine/verl/pull/1138#issuecomment-2862087324
```python
```
- **Training**: [Note which backend this PR …
=> [ray] fix: make spawn worker group hold strong reference to actors

.github/workflows/verl_unit_test.yml, .github/workflows/verl_unit_test_gpu.yml, tests/verl/utils/test_fs.py, tests/verl/utils/test_torch_functional.py, verl/utils/fs.py, verl/utils/torch_functional.py
1. In `verl/utils/fs.py`: adding a `always_recopy` kwarg to `copy_to_local` function, so that the file copied will always be triggered regardless of the local cache, which could be useful in certain cases.
2. In `verl/utils/torch_funcitonal`.py: adding two utilities `distributed_mean_max_min_std` and `distributed_masked_mean` to distributed torch tensor stats collection.
1. Added `tests/verl/utils/test_fs.py` and ``tests/verl/utils/test_torch_functional.py` to unit test the corresponding utility functions.
2. Changing `verl_unit_test` to run a [8*L20] to run torch tests, which uses cuda and nccl.
=> [utils] Enrich features to a few `verl` utilities

verl/workers/critic/dp_critic.py
When critic.use_dynamic_size is enabled, values rearrange indices but attention_mask does not, causing values * attention_mask to produce unpredictable bugs. This bug may have affected nearly all previous PPO-based experiments if critic.use_dynamic_size was turned on.
```python
```
- **Training**: …
=> [BUG] fix value mask bug in dp_critic

examples/sglang_multiturn/config/tool_config/gsm8k_tool_config.yaml, verl/tools/base_tool.py, verl/tools/gsm8k_tool.py, verl/tools/schemas.py, verl/workers/rollout/sglang_rollout/async_sglang_rollout.py
Resolved the tool formatting issue: Previously, arguments were stored as strings, causing iterative addition of `\\` due to multiple calls to `json.dumps`.
Fixed the `response_position_ids` mismatch between `generate_sequences` and `generate_sequences_with_tools`: In the earlier implementation, `generate_sequences_with_tools` used zero padding for positions where `attention mask == 0`, which resulted in NaN values during the training phase.
- Introduced a new schema, `OpenAIFunctionCallSchema`, to store converted tool calls.  
- Updated the `AsyncSGLangRollout` tool to skip non-dict type arguments instead of handling any string at the arguments position.  
- Aligned `response_position_ids` …
=> [sglang] Fix tool format and response position ids padding in AsyncSGLangRollout

verl/workers/rollout/async_server.py
In Async rollout, `AsyncOpenAI` has a default 600-second timeout, which can lead to timeouts during longer inference. See details at https://github.com/volcengine/verl/pull/1138#issuecomment-2869686490.
See details at https://github.com/volcengine/verl/pull/1138#issuecomment-2869686490.
See details at https://github.com/volcengine/verl/pull/1138#issuecomment-2869686490.
```python
```
- **Training**: [Note which backend this PR will affect: FSDP, Megatron, …
=> [Bug] Fix the problem of long inference timeouts when using Async rollout

tests/test_protocol.py, verl/protocol.py
`from_single_dict` is a classmethod, right now, it directly returns `DataProto.from_dict(.....)`. This PR changes it to `cls.from_dict(.....)`, In this way any subclass of `DataProto` may reuse this classmethod to instantiate a subclass.
In the current implementation, when subclass, i.e., `MyDataProto.from_single_dict()` is called, it returns a parent class instance, i.e., a `DataProto`, but not a `MyDataProto` instance.
=> [fix][DataProto] Make classmethod  `from_single_dict` return a cls not the class name

docs/advance/rope.rst, docs/index.rst, verl/workers/rollout/vllm_rollout/vllm_rollout.py, verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
Allow usage of sequence lengths longer than model's `max_position_embeddings` when RoPE scaling is used.
Added documentation on how to override RoPE scaling config for models that support RoPE scaling, but don't have it in its config.json file.
Skip context length greater than sequence length check for vLLM rollouts if RoPE scaling is used.
No API changes
Please see the updated docs for example usage.
I didn't capture any metrics, but I verified this works for my own training run with Qwen/Qwen2.5-7B-Instruct with long contexts.
- **Inference**:  This affects vLLM, but I can also update SGLang. I've only tested vLLM for my use case
=> Skip max_position_embeddings > sequence length check for vLLM rollouts if RoPE scaling is used

verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
> For some models like `internvl-chat`, the `max_position_embeddings` attribute is located in `config.llm_config` rather than directly in the config. This PR corrects the logic to retrieve it properly.
- **Issue Number**: none
- **Inference**: vLLM
=> [bugfix] correct retrieval of `max_position_embeddings` from config

docs/examples/config.rst, verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/config/ppo_trainer.yaml, verl/utils/torch_functional.py, verl/workers/fsdp_workers.py
Fix the cosine learning rate scheduler to properly respect `min_lr_ratio` parameter during both warmup and decay phases.
Update warmup phase to start from `min_lr_ratio` instead of 0, ensure decay phase never goes below `min_lr_ratio`, and add explicit `num_cycles` parameter to scheduler config.
Set default values in configuration files and handle `null` values since in some example yaml config, the `min_lr_ratio` is set to `null`.
```python
```
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by experiment(s) and show results like training curve plots, …
=> [lr_schedular] fix: implement proper min_lr_ratio support in cosine scheduler

verl/workers/sharding_manager/fsdp_vllm.py
[misc] fix: no need to use world_size to decide whether to use full_tensor() for FSDP2 state_dict() when world_size==1
This PR simplifies the parameter loading logic within the `FSDPVLLMShardingManager` by removing an unnecessary `world_size` check when determining whether to call `full_tensor()` on parameters obtained from an FSDP2 model's `state_dict()`. As the FSDP2 parameters are all `DTensor`.
The change modifies the update_params method. When loading weights into the vLLM model, parameters from the FSDP state_dict() (which might be ShardedTensor or DTensor instances under FSDP2 when world_size == 1) are converted to full tensors using param.full_tensor(). This PR ensures this conversion happens if the full_tensor() method is available on the parameter, without an additional, …
=> [misc] fix: no need to use world_size to decide whether to use full_tensor in FSDP2

verl/utils/dataset/rl_dataset.py, verl/utils/torch_functional.py
This PR adds support for a new truncation mode, **middle**, for loading datasets. It enables data that exceed the `max_prompt_length` to retain both the beginning and the end of the prompt, instead of truncating content only from the left or only from the right.
The implementation introduces a `"middle"` option, alongside the existing truncation modes, making changes in both `rl_dataset.py` and `torch_functional.py`. When selected, the logic splits the allowed max length roughly in half and keeps the head and tail of the sequence, effectively discarding the middle section.
**In `verl/utils/dataset/rl_dataset.py`:**  
- Added support for `self.truncation == "middle"` at line ~233.
- Performs symmetric truncation from both ends of the prompt:
```python
elif self.truncation == "middle": …
```
=> [Refactor] Add middle truncation

verl/utils/memory_buffer.py
This pull request includes a minor fix in the `build_memory_reference_from_module` function within `verl/utils/memory_buffer.py`. The change ensures that the correct data type is passed when calculating the padded number of elements.
* **Bug Fix**:
- Updated the `calc_padded_numel` function call to use `param.dtype` instead of `dtype`, ensuring compatibility with the parameter's actual data type. (`[verl/utils/memory_buffer.pyL107-R107](diffhunk://#diff-77d53102508293685e0b9a1281dbacf7720fb8070db73157aa90157d516004a4L107-R107)`)
```python
```
> …
=> [BUG] Fix silent bug of using dtype from previous loop scope in build_memory_reference_from_module()

scripts/model_merger.py
This PR fixes several issues (https://github.com/volcengine/verl/issues/1484, https://github.com/volcengine/verl/issues/1255) that cause the error: "Cannot copy out of meta tensor; no data!".
The related code in our part is:
https://github.com/volcengine/verl/blob/d36b5e81d6de598a87eecc6edf658ece0eb43582/scripts/model_merger.py#L131-L132
The `torch.device("meta")` context manager sets the current global torch device to "meta". During `auto_model_class.from_config`, various import statements load third-party libraries, whose `__init__.py` files may contain global statements that use torch for calculations.
For example, transformers imports [[torchao](https://github.com/pytorch/ao/blob/5549da8af975be6ff14330feb56c4abe3405b6f9/torchao/optim/subclass_4bit.py#L33)](https://github.com/pytorch/ao …
=> [merger] fix: avoid setting torch's global device to meta

verl/trainer/config/ppo_trainer.yaml
Disable fused kernels by default. #1565 
Not needed
- Default use_fused_kernels = False
Not needed
Not needed
Not needed
Not needed
=> disable fused kernels by default

docs/examples/config.rst, examples/split_placement/config/ppo_trainer_split.yaml, verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/config/ppo_trainer.yaml, verl/utils/dataset/rl_dataset.py
[misc] feat: support return full prompt with chat template in RLHFDataset
Currently, RLHFDataset can return raw prompt (without chat_template). However, in some scenarios (like multi-turn and agent env), we may need full prompts with chat_template. So that the rollout engine can utilize the full prompt for generation.
No
No
Add a field: `data.return_full_prompt`: False
Set the `data.return_full_prompt` to True
No
- **Training**: None
- **Inference**: None
=> [misc] feat: support return full prompt with chat template in RLHFDataset

verl/utils/megatron/tensor_parallel.py
This PR moves the `from megatron.core import ModelParallelConfig, tensor_parallel` into lazy import, so that when utilities who don't use these modules are imported, we don't always import `megatron.core.xxx` by default.
=> [misc] use lazy import on megatron utils components

README.md, recipe/README.md
- [✅ ] Search for similar PR(s).
> (1) Add back DeepRetrieval (the **first** search agent framework interacting with search engine) to the "awesome work" of main page, and (2) add a new work s3 (much more efficient way (70x less data) to train an powerful search agent!)
> Only updates two readme files.
> (1) Added "- [DeepRetrieval](https://github.com/pat-jj/DeepRetrieval): RL Training of **Search Agent** with **Search/Retrieval Outcome** ![GitHub Repo stars](https://img.shields.io/github/stars/pat-jj/DeepRetrieval)" to the main page's README.md. (2) Added "- [s3](https://github.com/pat-jj/s3) **Efficient Yet Effective** Search Agent Training via RL ![GitHub Repo stars](https://img.shields.io/github/stars/pat-jj/s3)" to the recipe/README.md
> N/A
> N/A
> N/A
N/A
- [✅] Read the [Contribute …
=> add back DeepRetrieval and add a new work s3

.github/workflows/e2e_ppo_trainer.yml, .github/workflows/sgl.yml, docker/Dockerfile.rocm, docker/Dockerfile.sglang, docker/Dockerfile.vllm.sglang.megatron, docs/amd_tutorial/amd_build_dockerfile_page.rst, docs/start/install.rst, docs/workers/sglang_worker.rst, requirements_sglang.txt, setup.py, verl/workers/fsdp_workers.py, verl/workers/rollout/sglang_rollout/async_sglang_rollout.py, verl/workers/rollout/sglang_rollout/sglang_rollout.py, verl/workers/rollout/sglang_rollout/utils.py, verl/workers/sharding_manager/fsdp_sglang.py
- Thanks to:
- close #1558 due to mix of prs
- close #1449 due to partial fix sgl new version issue
- close #1300 which is part of current pr
- This pr is co-authored with @ocss884 
- bump sglang to 0.4.6.post4
- unified sglang and sglang_async `generate_sequences` api behavior, e.g. image support
- fix warning for cuda barrier at start of fsdp_workers
=> Bump to sglang 0.4.6.post4 & unified generate sequences ability between sgl and sgl async

examples/ppo_trainer/naive_chat_scheduler.py, tests/workers/rollout/test_vllm_tool_calling.py, verl/workers/rollout/async_server.py, verl/workers/rollout/vllm_rollout/vllm_async_server.py
AsyncOpenAI has very severe performance issue due to httpx, replace it to aiohttp client. For train_batch_size=1024, AsyncOpenAI introduces ~25s per generation phase.
```python
```
=> [rollout] perf: replace AsyncOpenAI to aiohttp client in ChatCompletionScheduler

recipe/prime/config/prime_trainer.yaml
Currently, the `e2e_prime` test encounters the error` AttributeError: 'NoneType' object has no attribute 'squeeze'`, which is caused by [ #1212].
In PR [#1568], the parameter `use_fused_kernel` in `ppo_trainer.yaml` was set to `false`, but the corresponding parameter in `prime_trainer.yaml` was not updated. This is preventing the CI from passing.  Before the root cause of `use_fused_kernel` is fully resolved , I guess we should temporarily set `use_fused_kernel` to `false` in `prime_trainer.yaml`
Not needed
- Default use_fused_kernels = False
Not needed
Not needed
Not needed
Not needed
=> Disable fused kernels in prime

examples/sglang_multiturn/config/gsm8k_multiturn_grpo.yaml, verl/workers/rollout/schemas.py, verl/workers/rollout/sglang_rollout/async_sglang_rollout.py
Support multi-turn rollout with Qwen chat template
Currently, Verl's multi-turn rollout only supports ChatML-style messages. However, Qwen uses a different chat formatting template with the following key differences:
1. Qwen uses the `user` role tag to wrap tool responses.
2. Qwen merges consecutive tool responses into a single message.
**For example**, for parallel tool calls, ChatML renders consecutive tool responses like this:
```
<|im_start|>tool
tool response content 1<|im_end|>
<|im_start|>tool
tool response content 2<|im_end|>
```
In contrast, the Qwen chat template renders them as:
```
<|im_start|>user
<tool_response>
tool response content 1
</tool_response>
<tool_response>
tool response content 2
</tool_response><|im_end|>
```
This PR introduces a new `qwen` format option in the …
=> Support multi-turn rollout with Qwen chat template

verl/utils/checkpoint/fsdp_checkpoint_manager.py
A very minor fix as https://github.com/volcengine/verl/pull/1564, forgot to also update fsdp checkpoint manager to use init_empty_weights.
- **Training**: FSDP
=> [minor] fix: use init_empty_weights instead of torch.device("meta")

docs/examples/config.rst, verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/config/ppo_trainer.yaml, verl/workers/rollout/sglang_rollout/sglang_rollout.py
Expose `engine_kwargs` from SGLang to Verl configuration
This PR enables RL users to configure `engine_kwargs` directly through Verl, providing more control and flexibility over inference behavior.
One key motivation is the choice of attention backend, which can significantly affect rollout performance. The SGLang team has observed that different attention backends perform better in different phases:
FA3 tends to be more efficient during the prefill stage.
FlashInfer or Triton generally offer better performance during decode.
Moreover, the optimal backend may change across versions of SGLang. By exposing these parameters, we allow users to tune their setup based on the specific use case and version, ultimately improving performance and adaptability.
> Add one-line overview of what this PR …
=> Expose `engine_kwargs` from SGLang to Verl configuration

verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
> add `engine_kwargs`  in vllm_rollout_spmd to set swap_space in vllm engine. 
> add `engine_kwargs` in vllm_rollout_spmd, which can be set in config file. Same changes has been made in vllm_rollout. As the version of vllm is update to 0.8, the default vllm_rollout worker becomes vllm_rollout_spmd, which does not have `engine_kwargs` as in vllm_rollout, so this RP want to complete it.
> users can set vllm engine param such as `swap_space`, `seed` through the `engine_kwargs` in config file. For example, if  one want to set the swap_space=32 in vllm, he can set the item in config like this
```bash
actor_rollout_ref.rollout.engine_kwargs.swap_space=32
```
=> add `engine_kwargs`  in vllm_rollout_spmd to set params in vllm engine

verl/workers/reward_manager/prime.py
>  Fixes a hang issue during reward scoring where the progress bar reaches 100% but the program does not continue. Adds robust support for asynchronous reward computation with subprocess cleanup.
> This PR refactors the reward scoring pipeline (`PRIMERewardManager`) to: Adds forced cleanup of lingering subprocesses using psutil to avoid deadlocks.
- Replaces `asyncio.run()` inside `verify()` with an external event loop using `new_event_loop()` for better compatibility with Ray and training frameworks.
- Replaces `proc.kill()` with `psutil.terminate()` and `.wait()`, and move from `exception` to `finally` to clean up worker subprocesses safely and avoid zombie processes.
- **Issue Number**: #288(maybe)
=> [PRIME]bug fix: reward scoring hangs after progress reaches 100%

verl/workers/rollout/hf_rollout.py
Added position_ids parameter to the model.generate method call to provide explicit control over token positions during text generation. I don't quite understand why have obtained position ids above but not passed them to generate, so I modified this.😂
```python
```
- **Inference**: …
=> Add explicit position_ids to model.generate in hf rollout

docs/examples/config.rst, docs/perf/perf_tuning.rst, tests/utils/gpu_tests/test_activation_offload.py, verl/trainer/config/ppo_trainer.yaml, verl/utils/activation_offload.py, verl/workers/fsdp_workers.py
This PR supports activation offloading, and currently it's only for FSDP backend. 
Our implementation is based on the [one](https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/pytorch/cpu_offload.py) in TransformerEngine. For efficiency, it groups activations by TransformerLayer and offloads activation groups asynchronously. This means that the offloading of the i-th activation group and the computation of the i+1-th activation group happen at the same time, and there are at most two activation groups in GPU memory. 
1. Add activation offloading support.
``` 
export VLLM_ATTENTION_BACKEND=XFORMERS
python3 -m verl.trainer.main_ppo \
algorithm.adv_estimator=grpo \
data.train_files=./data/gsm8k/train.parquet \
data.val_files=./data/gsm8k/test.parquet \ …
```
=> Activation Offloading

recipe/dapo/main_dapo.py
This PR fixes wrong initialization so that verl only loads reference policy when needed.
- **Issue Number**: none
=> fix: only load reference policy when needed in DAPO

recipe/dapo/dapo_ray_trainer.py
This PR adds entropy computation and logging to DAPO trainer, aligning with other trainers.
- **Issue Number**: #1455
=> fix: entropy in DAPO

verl/workers/rollout/async_server.py
fixes TimeoutError that #1588 reintroduces. see https://github.com/volcengine/verl/pull/1588#issuecomment-2909898886
- add `aiohttp.Timeout` to `ClientSession` for unlimited generation time
```python
```
- **Inference**: [Note which backend this PR will affect: vLLM, SGLang, both, or …
=> fix TimeoutError in aiohttp

tests/ray_cpu/test_ray_utils.py, verl/utils/ray_utils.py, verl/utils/reward_score/__init__.py
Handle comments after #1397 being merged:
1. Add back `_default_compute_score` API and mark it as deprecated;
2. Fix a broken ci test `ray_utils_test` on `parallel_put`;
=> [mics][fix] Deprecate legacy `_default_compute_score` API and fix ray utils test

recipe/dapo/dapo_ray_trainer.py, recipe/sppo/sppo_ray_trainer.py, verl/trainer/ppo/ray_trainer.py, verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
"multi_modal_inputs" is not used in generate_sequences() stage, there's no need to pass this field.
```python
```
=> There's no need to repeat "multi_modal_inputs" in generate_sequences()

verl/utils/megatron_utils.py
This PR fixes the issue of improper memory offloading for Moe. When expert parallelism is enabled in Megatron's MoE, additional expert_parallel_buffers are used to store the buffers, which occupy a significant amount of GPU memory. The current code fails to offload and onload these expert_parallel_buffers, resulting in incomplete memory offloading of the model. This may lead to out-of-memory (OOM) problem.
```python
```
- …
=> fix a bug that Moe's GPU memory offload is not properly handled

docs/faq/faq.rst
> Add linux-arm64 platform tensordict package version problem handle FAQ. 
> Besides me, there are other people in the community who have encountered this problem(issue #919 )
The Linux-arm64 platform does not have a suitable version of the tensordict package. The verl requirement for tensordict is <=0.6.2.0. The version that can be installed on the Linux-arm64 platform is 0.1.2, but the `"key" in tensordict_var ` syntax is not supported by 0.1.2, so error take place. The error message is as follows:
```
File "/home/mnj/models/code/verl/verl/verl/trainer/main_ppo.py", line 191, in run
trainer.fit()
File "/home/mnj/models/code/verl/verl/verl/trainer/ppo/ray_trainer.py", line 1043, in fit
old_log_prob = self.actor_rollout_wg.compute_log_prob(batch)
File …
```
=> [docs] Add linux-arm64 platform tensordict package version problem handle FAQ

.gitignore, recipe/dapo/main_dapo.py, recipe/r1/main_eval.py, recipe/spin/main_spin.py, verl/trainer/main_eval.py, verl/trainer/main_ppo.py
> remove redundant 'get_custom_reward_fn' function. 
> None.
> "from verl.trainer.ppo.reward import get_custom_reward_fn" instead of  'get_custom_reward_fn' function in verl/recipe/dapo/main_dapo.py verl/recipe/r1/main_eval.py verl/recipe/spin/main_spin.py verl/verl/trainer/main_eval.py verl/verl/trainer/main_eval.py
> remove 'get_custom_reward_fn' function in verl/verl/trainer/main_ppo.py
- **[Issue Number](https://github.com/volcengine/verl/issues/1716)**: Fixes issue # or discussion # if any.
=> remove redundant 'get_custom_reward_fn' function

docker/Dockerfile.rocm, docs/amd_tutorial/amd_build_dockerfile_page.rst, verl/single_controller/base/worker.py, verl/utils/ray_utils.py, verl/workers/actor/megatron_actor.py, verl/workers/critic/megatron_critic.py
Add support for RAY_EXPERIMENTAL_NOSET_*_VISIBLE_DEVICES, also Fix AMD support
Current approach for supporting AMD in verl is fundamentally not correct, and is just working out of the luck:
Calls such as `torch.cuda.is_available()` or `torch.cuda.get_device_name()` will initialize the CUDA/ROCm environment:
https://github.com/pytorch/pytorch/blob/c65ee728f069ea9544bdcac815eb0825f45d1633/torch/cuda/__init__.py#L342-L392
Setting CUDA/HIP/ROCR_VISIBLE_DEVICES after CUDA/ROCm is initialized will not take effect (Please check https://github.com/pytorch/pytorch/issues/141678), which means that all current code that wrapped inside `[SUPPORT AMD: torch]` are mostly noops.
CUDA_VISIBLE_DEVICES also works for AMD, but it's because that a lot of AMD migrated software call those `torch.cuda.*` during …
=> [Feat] Add support for RAY_EXPERIMENTAL_NOSET_*_VISIBLE_DEVICES (Fix AMD support)

verl/models/mcore/config_converter.py
- Hardcode moe_router_load_balancing_type to none as it hurts perf in QWen3MoE
- We can provide a config to set it
```python
```
=> [config] feat: Hardcode moe_router_load_balancing_type to none

.github/workflows/e2e_sppo.yml
- [done] Search for similar PR(s).
Fix error in e2e_sppo  CI test
Exception: sgl-kernel is installed with version 0.0.9.post2, which is less than the minimum required version 0.1.1. Please reinstall the latest version with `pip install sgl-kernel --force-reinstall`
For example:
https://github.com/volcengine/verl/actions/runs/15431843178/job/43430980736?pr=1769
=> fix sglang e2e_sppo test

verl/workers/rollout/sglang_rollout/sglang_rollout.py
A method proposed by Congkai Xie to avoid sglang_rollout broadcast_pyobj with nccl timeout error.
- Add dist.barrier() before `broadcast_pyobj` to avoid nccl communication waiting happens at same time TP0 start rollout
- **Issue Number**: close #1420 
- **Inference**: SGLang
- [] New CI unit test(s) are added to cover the code path.
=> [sglang] Fix for broadcast_pyobj nccl timeout in sgl rollout with larger model (e.g. 32B)

.github/workflows/e2e_ppo_trainer_megatron.yml, scripts/init_random_model.py, tests/e2e/ppo_trainer/expert_parallel/qwen2moe_minimal.json, tests/e2e/run_ppo_trainer_megatron.sh, verl/workers/reward_model/megatron/reward_model.py
Fix ep bug and try to add CI with 15B model, finding smaller models which are more convenient to test.
```python
```
=> [BugFix][CI] Megatron: add ep CI

verl/utils/megatron_utils.py
there is a tricky bug in per_tensor_generator with model.named_parameter().
"decoder.layers[n].mlp.router.expert_bias" in GPTModel is not registered in named_parameter, but in state_dict(). Before this fix, the router_bias or `model.layers.{layer_number}.mlp.gate.e_score_correction_bias` is not transfered from m-core to infer engine.
```python
```
- **Issue …
=> [megatron] moonlight fix per_tensor_generator

verl/workers/critic/dp_critic.py, verl/workers/critic/megatron_critic.py
For PPO critic training, the value of EOS tokens should be zero and should not be fitted. However, the current implementation does not mask the EOS token values, resulting in non-zero EOS token values. Although the learning target is zero, when PPO GAE lambda < 1, this affects the advantage calculation for tokens preceding EOS, thereby impacting performance.
```python
```
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by experiment(s) and show results like training curve plots, evaluatuion …
=> [ppo critic] fix EOS token value to zero

docker/Dockerfile.rocm
- [x ] Search for similar PR(s).
Update tensordict version
Resolve PPO training error
+ python3 -m verl.trainer.main_ppo algorithm.adv_estimator=gae data.train_files=/root/data/gsm8k/train.parquet data.val_files=/root/data/gsm8k/test.parquet data.train_batch_size=256 data.max_prompt_length=512 data.max_response_length=512 data.return_raw_chat=True actor_rollout_ref.model.path=/root/models/Qwen/Qwen2.5-0.5B actor_rollout_ref.model.use_liger=True actor_rollout_ref.actor.optim.lr=1e-6 actor_rollout_ref.model.use_remove_padding=True actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.1 actor_rollout_ref.actor.ppo_mini_batch_size=128 actor_rollout_ref.actor.use_dynamic_bsz=False actor_rollout_ref.actor.ppo_max_token_len_per_gpu=32768 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=2 …
=> Dockerfile.rocm update tensordict==0.6.2

verl/trainer/config/ppo_trainer.yaml, verl/trainer/ppo/ray_trainer.py
In scenarios involving multiple validation sets, where the difficulty levels of these sets differ significantly and the generated content lengths vary notably, the order in which the validation sets are processed can have a substantial impact on the validation speed.
add validation shuffle
```python
validation_shuffle: True
```
Validation speed increase of over 10%.
=> [feat] add validation shuffle

README.md
> Integrates Korean TTS fine-tuning using GRPO optimization based on LLASA-1B models, significantly improving synthesis quality by reducing Character Error Rate (CER).
> This PR enhances the existing TTS model training pipeline by introducing a reinforcement learning optimization (GRPO) step using Whisper's NLL and CER metrics.
* Adds GRPO reward calculation based on Character Error Rate (CER) and Negative Log-Likelihood (NLL).
* Implements a Whisper server to compute NLL metrics efficiently.
* Provides scripts for training (`run_llasa_tts_grpo.sh`) and data preprocessing (`tts.py`).
> No changes to existing public APIs. Internal additions only.
```bash
CUDA_VISIBLE_DEVICES=2 python3 tts/whisper_server.py --port 8001 --model large-v3
WHISPER_SERVER=http://localhost:8001 nohup bash …
```
=> [doc] Add TTS model GRPO tuning project with verl on README

tests/workers/rollout/test_sglang_async_rollout_w_tools.py, verl/workers/rollout/sglang_rollout/sglang_rollout.py
SGLang multiturn rollout relies on bos and eos token in the tool parser to retrieve the right tool parser. SGLang==0.4.6.post5 changed those tokens for Qwen2 parser([PR](https://github.com/sgl-project/sglang/pull/6597/files#diff-725eae87b1043c063d85c22b71f415941e2983c60eb52ef1a0d0be89f13b1110)) so it breaks async rollout. This PR updates the logic in Verl to fix the issue.
Error example:
```
Traceback (most recent call last):
File "/home/jobuser/resources/verl/trainer/main_ppo.py", line 28, in main
run_ppo(config)
File "/home/jobuser/resources/verl/trainer/main_ppo.py", line 40, in run_ppo
ray.get(runner.run.remote(config))
File "/home/jobuser/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
return fn(*args, **kwargs)
File …
```
=> [sglang] fix: Fix tool call parser not found error for SGLang==0.4.6.post5

docs/advance/checkpoint.rst, docs/faq/faq.rst
Description:  
This pull request corrects several typographical errors in the documentation:
- In docs/advance/checkpoint.rst, the word "togather" has been corrected to "together".
- In docs/faq/faq.rst, the word "trainning" has been corrected to "training".
These changes improve the clarity and professionalism of the documentation. No functional code changes are included.
=> Fix Typos in Documentation Files

docker/Dockerfile.rocm
- [x ] Searched for similar PR(s).
Fix type in AMD dockerfile
- [x ] Read the [Contribute Guide](https://github.com/volcengine/verl?tab=readme-ov-file#contribution-guide).
- [x ] Apply [pre-commit checks](https://github.com/volcengine/verl?tab=readme-ov-file#code-linting-and-formatting).
=> [hardware] fix typo in dockerfile

docs/start/install.rst
Fix typo in deepseek v3 docker image name.
> Add one-line overview of what this PR aims to achieve or accomplish.
```python
```
=> [misc] doc: fix typo in deepseek v3 docker image name install.rst

verl/workers/rollout/chat_scheduler.py, verl/workers/rollout/vllm_rollout/vllm_async_server.py
- set repetition_penalty=1.0 for AsyncLLM
- add missing timing metrics, close #1926 
```python
```
=> [rollout] fix: set repetition_penalty=1.0 to AsyncLLM

examples/grpo_trainer/run_deepseek671b_math_megatron.sh
> This merge request addresses a potential TypeError that arises when running run_deepseek671b_math_megatron.sh. The parameters `moe_router_bias_update_r` and `moe_aux_loss_coeff` are already present in the `hf_to_mcore_config_dpskv3` function's `_get_mla_transformer_config`. Including them again in the script leads to the error:
`
TypeError: verl.models.mcore.config_converter._get_mla_transformer_config() got multiple values for keyword argument 'moe_router_bias_update_r' and 'moe_aux_loss_coeff'.`
https://github.com/volcengine/verl/blob/13475caaa9bb1b89b1a29f850f0b54253a8c2d38/verl/models/mcore/config_converter.py#L252C19-L252C46
To resolve this issue, this PR removes the duplicate arguments from the script, ensuring that the function is called correctly without any conflicts.
=> Fix TypeError by Removing Duplicate Arguments in run_deepseek671b_math_megatron.sh

verl/trainer/ppo/core_algos.py
- modules are in `fsdp, megatron, sglang, vllm, rollout, trainer, ci, training_utils, recipe, hardware, deployment, ray, worker, single_controller, misc, perf, model, algo, env, tool, ckpt, doc`
- Fix `vf_loss` factor: https://github.com/volcengine/verl/commit/ae528e06e9e2879b517a30bf6da72ebd4c870e0a#diff-af3da2c60785abde478f7bb68c303cd20e044e8af1b1ae93a2698f5b8fd5ed63R646-R647
- Fix `core_algos.__all__`:
```diff
- __all__ = ["register", "get_adv_estimator_fn", "AdvantageEstimator"]
+ __all__ = ["register_adv_est", "get_adv_estimator_fn", "AdvantageEstimator"]
```
=> [algo] fix: `vf_loss` factor

verl/utils/dataset/rl_dataset.py, verl/utils/ulysses.py, verl/workers/actor/megatron_actor.py, verl/workers/fsdp_workers.py, verl/workers/reward_model/megatron/reward_model.py, verl/workers/rollout/sglang_rollout/sglang_rollout.py, verl/workers/rollout/vllm_rollout/fire_vllm_rollout.py, verl/workers/rollout/vllm_rollout/vllm_rollout.py
Fix two issues releated to position_ids for qwen2_VL/qwen2.5_VL:
(1) Create processor with use_fast=True lead to use `Qwen2VLImageProcessorFast`, however, when determining whether to handle 3D position ids, the Qwen2VLImageProcessor was still used. 
(2) And 3D position is not considered in ulysses_pad.
```python
```
- **Training**: [Note which backend this PR will affect: …
=> [fsdp] fix: position_ids in qwen-vl

verl/trainer/fsdp_sft_trainer.py
When we SFT on a dataset of a new max_length, we should set the max_position_embeddings to the new max length.
> Demonstrate how the API …
=> [trainer] fix: fix sft max_position_embeddings

verl/workers/actor/dp_actor.py
> Fix a TensorDict usage problem which happens at the begin of the training. TensorDict does not support membership checks with the `in` keyword.
> List the specific …
=> fix: TensorDict usage error

docs/examples/config.rst
`default_local_dir` is used, not `default_hdfs_dir`: https://github.com/volcengine/verl/blob/7737bf06e5c598a8ff4c05d07b713450d4cf308d/verl/trainer/ppo/ray_trainer.py#L818-L825
=> [doc] fix: Fix typo for `trainer.resume_mode`

verl/protocol.py
> count the size when `self.batch is not None` …
=> [Bug] fix `None` check in DataProto print_size()

verl/workers/rollout/sglang_rollout/async_sglang_server.py
Correctly implement async wake_up and sleep for AsyncSglangServer. They are called in await manner by ActorRolloutRefWorker.
> Add one-line overview of what this PR aims to achieve or accomplish. Reference related github issues and PRs if that help review.
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by experiment(s) and show results like training curve …
=> [sglang] fix: AsyncSglangServer use async wake_up/sleep

recipe/dapo/dapo_ray_trainer.py, verl/trainer/ppo/reward.py
- type is in `feat, fix, refactor, chore, test`
Fix the error message: `Error in reward_fn: reward_extra_info`, as for some reward function implementation, only `reward_tensor` is included in the returned dictionary.
- https://github.com/volcengine/verl/blob/b401382405304436292ca19870d1917a0174d09c/verl/workers/reward_manager/prime.py#L176
- https://github.com/volcengine/verl/blob/b401382405304436292ca19870d1917a0174d09c/examples/split_placement/main_ppo_spli …
=> [trainer] fix: make `reward_extra_info` optional in `reward_result`

examples/split_placement/split_monkey_patch.py
fix timer importance error in split_placement, should use `from verl.trainer.ppo.ray_trainer import marked_timer`, but got `from verl.trainer.ppo.ray_trainer import _timer` now.
Not related.
Not related.
Not …
=> [misc] fix: fix timer importance error in split_placement

verl/model_merger/__main__.py
`verl/model_merger/__main__.py` allows the user to specify either the FSDP backend or the Megatron backend, but it forces the user to have both backends installed. This change moves those imports under the backend conditional, relieving that requirement.
- Example: …
=> [ckpt] fix: conditionally import fsdp/megatron backend

.github/workflows/sgl.yml, docs/sglang_multiturn/interaction_system.rst, examples/data_preprocess/gsm8k_multiturn_w_interaction.py, examples/sglang_multiturn/config/interaction_config/gsm8k_interaction_config.yaml, tests/interactions/test_gsm8k_interaction.py, tests/interactions/test_interaction_registry.py, tests/workers/rollout/test_sglang_async_rollout_w_interaction.py, tests/workers/rollout/test_sglang_multi_interaction.py, verl/interactions/utils/__init__.py, verl/interactions/utils/interaction_registry.py, verl/workers/rollout/sglang_rollout/sglang_rollout.py
This PR implements multi-interaction support in SGLangRollout, enabling sample-level interaction selection similar to the existing tools system. The implementation includes a new interaction registry system that allows multiple named
interactions to be configured and used within a single rollout instance. #1630 
Core Implementation
- New Interaction Registry System: Created verl/interactions/utils/interaction_registry.py with functions to dynamically load and manage multiple interaction instances from configuration files
- Enhanced SGLangRollout:
- Replaced single interaction attribute with interaction_map: dict[str, BaseInteraction]
- Updated …
=> [sglang] feat: Add multi-interaction registry support and testing

verl/workers/rollout/sglang_rollout/sglang_rollout.py
Fix error found in https://github.com/volcengine/verl/issues/2242
In none-hopper gpu, llm can not use tools because sglang use flashinfer in default on this type of hardware. 
Changed backend to flashattn3 to avoid this error
ROLLOUT_NAME=sglang pytest -svvv tests/experimental/agent_loop/test_basic_agent_loop.py
> [!IMPORTANT]
=> [rollout] fix: use flashattn3 backend in sglang to avoid error in tool call

verl/workers/sharding_manager/fsdp_sglang.py
Fix issue #2189.
This bug was introduced in #1911, which relocated `resume_memory_occupation` in resharding phase before calling `get_torch_device().empty_cache()`.
Calling `resume_memory_occupation` without emptying cache before will cause OOM on resharding phase of the first iteration, which prevents the example `run_qwen2.5-3b_gsm8k_multiturn` to run.
Re-adding `get_torch_device().empty_cache()` solves the problem, and allows the example to run again.
- If this PR involves multiple modules, separate them with `,` like `[megatron, fsdp, …
=> [worker] fix: OOM on first iteration in multi-turn RL

.github/workflows/cpu_unit_tests.yml
Previous cpu unit test relies on pulling dataset stored in eric-haibin-lin/verl-data repo which may trigger GIT LFS quota error. Now directly pulling from huggingface instead. 
> [!IMPORTANT]
> Please check …
=> [ci] fix: fix cpu dataset git download error

.github/workflows/check-pr-title.yml, .github/workflows/doc.yml, .github/workflows/e2e_dapo.yml, .github/workflows/e2e_eval_aime24.yml, .github/workflows/e2e_genrm_remote.yml, docs/README.md, docs/sglang_multiturn/sandbox_fusion.rst, tests/special_sanity/check_pr_description.py
- fix sandbox doc 
- enhance CI trigger filter and doc error checking
- add a rule to check PR description
> [!IMPORTANT]
> Please check all the following items before requesting a review, otherwise the …
=> [doc, ci] fix: fix sandbox doc and enhance CI trigger filter and doc error checking

verl/workers/actor/dp_actor.py, verl/workers/critic/dp_critic.py, verl/workers/fsdp_workers.py
This PR fix an issue in dp_actor where `actor/kl_loss` and `actor/kl_coef` were being continuously overwritten during the micro-batch processing loop.
Previously, the long-lived `metrics` dictionary was updated directly, causing the value for these metrics to reflect only the final micro-batch of any given step, rather than an aggregation of all micro-batches within that step.
This change refactors the logic to align the collection of all metrics, now `kl_loss` is collected for each micro-batch, the same as other metrics like `pg_loss`.
> [!IMPORTANT]
=> [algo] fix: correctly aggregate kl metrics in PPO actor

CONTRIBUTING.md, README.md, docs/start/install.rst
add contribution guide 
TODO: add one specific doc for the workflow of adding new models 
=> [doc] chore: add contribution guide

verl/workers/reward_manager/dapo.py
Added a assertion when the overlong buffer configuration is invalid, specifically when `overlong_buffer_len > max_response_length` which causes `expected_len` to be negative.
When `overlong_buffer_len` is greater than `max_response_length`, the calculated `expected_len` becomes negative:
```
expected_len = max_resp_len - overlong_buffer_len  # Results in negative value
```
This causes all reasonable response lengths to be penalized.
Added a `assert self.max_resp_len >= self.overlong_buffer_cfg.len` in DAPORewardManager
1. File: `verl/workers/reward_manager/dapo.py`
=> [cfg] chore: add non-negative expected_len assertion

docs/examples/config.rst, verl/experimental/agent_loop/agent_loop.py, verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/config/ppo_trainer.yaml, verl/utils/import_utils.py, verl/workers/rollout/async_server.py
This PR contains two aspects:
1. Introduction of a new configuration option `actor_rollout_ref.rollout.custom_async_server` to allow users to customize the async server class.
2. Make `load_extern_type` more robust and support prefix like `pkg://` or `file://`, while non-breaking to any existing features and supported paths.
Without this PR, it's impossible to use a customized version of AsyncvLLMServer in customized use case. We are currently using a set of ugly monkey patch to achieve this goal.
Ultimately I believe `rollout.name` and `rollout.custom_async_server` can be combined. But `rollout.name` is currently referenced in too many places. It's quite difficult for me to handle all of them.
- `{modules}` include `fsdp`, `megatron`, `sglang`, `vllm`, `rollout`, `trainer`, `ci`, …
=> [rollout] feat: Allow customization of async server class

verl/workers/actor/dp_actor.py
Support entropy checkpointing without rmpad or sp
> For changes …
=> [perf] feat: support entropy checkpointing without rmpad or sp

verl/trainer/ppo/reward.py
> Fix "Can't pickle local object" error when using custom reward functions in multiprocessing
When I import `compute_score` from my own Python file, the `file_path` is not None and it will call the `wrapped_fn ` method.
You can view the relevant code at the following：
https://github.com/volcengine/verl/blob/e96f0fbf44a50a302ddea0118e76d40cc9aa4fff/verl/trainer/ppo/reward.py#L25-L57
When  I set` reward_model.reward_manager=prime`, it will call the `ProcessPoolExecutor` to use asyncio, leading to the error:
`"Can't pickle local object 'get_custom_reward_fn.<locals>.wrapped_fn'".`
Root Cause:
The nested closure `wrapped_fn` created in `get_custom_reward_fn() `is unpicklable for the following reasons:
- Python's `pickle` cannot serialize local functions (functions defined inside another …
=> [cfg] fix: pickleing error in multiprocessing in the reward_fn

docs/conf.py
Enable API docs with [source code] option
=> [doc] fix: add show source option

verl/utils/dataset/rl_dataset.py
=> Revert "[misc] fix: invalid escape sequence '\*'"

tests/special_sanity/check_pr_title.py
PR title check supports module names with underscore (`training_utils`)
https://github.com/volcengine/verl/actions/runs/16087327930/job/45415231450 …
=> [ci] fix: PR title check supports module names with underscore (`training_utils`)

verl/workers/rollout/sglang_rollout/sglang_rollout.py
This PR updates the documentation for the sglang rollout’s `generate_sequences` by separating single-turn and multi-turn explanations for improved readability.
> [!IMPORTANT]
> Please check all the following …
=> [sglang, rollout, doc] fix: update sglang rollout generate doc

verl/trainer/ppo/ray_trainer.py
Avoids NotImplementedError since TensorDict doesn't support direct 'in' checks.
=> [trainer] fix: use .keys() to check 'response_mask' in TensorDict

recipe/spin/spin_trainer.py
`spin_trainer.py` defines `class Role` which is totally the same as `class Role` defined in `ray_trainer.py`.
* `spin_trainer.py`
https://github.com/volcengine/verl/blob/4aa02fe1663d8048b9c204345b2abe5197870df3/recipe/spin/spin_trainer.py#L55-L66
* `ray_trainer.py`
https://github.com/volcengine/verl/blob/4aa02fe1663d8048b9c204345b2abe5197870df3/verl/trainer/ppo/ray_trainer.py#L67
- If this PR …
=> [recipe] chore: Remove the duplicate definition of `class Role`

verl/workers/actor/dp_actor.py
[BUG] advantages is incorrectly passed as response_mask to policy_loss_fn in dp_actor.py #2506
fix https://github.com/volcengine/verl/issues/2506
=> [BUG] fix bug for #2506, when passing as response_mask to policy_loss_fn

tests/utils/test_temp_env_on_cpu.py, verl/single_controller/ray/base.py, verl/utils/py_functional.py
Fixes a critical issue in the Ray worker initialization where environment variables were not being properly preserved when using `unittest.mock.patch`. This could lead to environment variables being unexpectedly deleted after worker initialization. The fix replaces the `patch` usage with a proper context manager for safer environment variable management.
This change can be tested through the CI system since it affects core worker initialization functionality. The following test scenarios should be covered:
- Worker initialization with pre-existing environment variables
- Worker initialization without pre-existing environment variables
- Multiple worker initializations in sequence
- Error cases during worker initialization
No API changes. Internal implementation change only. The fix uses a …
=> [single_controller] fix: replace unittest.mock.patch with context manager for env var handling

tests/utils/test_seqlen_balancing.py, verl/protocol.py, verl/utils/seqlen_balancing.py, verl/workers/actor/dp_actor.py, verl/workers/critic/dp_critic.py
The use of `len(data)` is incorrect since the data is a **dict** if we enable dynamic batch for VLMs. It will return the number of keys in the dict instead of the number of batch samples.
https://github.com/volcengine/verl/blob/0b508ab803497b1929727abb3cbade28361a600f/verl/workers/actor/dp_actor.py#L540-L542
https://github.com/volcengine/verl/blob/0b508ab803497b1929727abb3cbade28361a600f/verl/workers/actor/dp_actor.py#L432-L434
It can work correctly with pure-text LLMs because the data here is a **tensordict** that has a `len` API.
https://github.com/volcengine/verl/blob/0b508ab803497b1929727abb3cbade28361a600f/verl/workers/actor/dp_actor.py#L441-L443
To solve this problem, we use `response_mask.shape[0]` to get the number of samples in dynamic batch.
Nevertheless, I think the current …
=> [fsdp] fix: vlm dynamic batch & unify dynamic batch api

tests/utils/reward_score/reward_score/test_sandbox_fusion_on_cpu.py, verl/utils/reward_score/sandbox_fusion/utils.py
Currently, `stdin_data` is passed into `_process_single_case` as None in [`sandbox_fusion_tools`](https://github.com/volcengine/verl/blob/main/verl/tools/sandbox_fusion_tools.py#L179).
In [`_process_single_case`](https://github.com/volcengine/verl/blob/main/verl/utils/reward_score/sandbox_fusion/utils.py#L301), we will call `str(None)` which erroneously converts it to `'None'` (a string) when stdin should be empty.
```python
api_response, error_msg = call_sandbox_api(
sandbox_fusion_url=sandbox_fusion_url,
code=current_generation_code,
stdin=str(stdin_data),
compile_timeout=timeout,
run_timeout=timeout,
memory_limit_mb=memory_limit_mb,
language=language,
)
```
This PR adds a check for if `stdin_data` is None so that it doesn't get converted and passed into stdin.
- `{modules}` include …
=> [tool] fix: correctly convert 'None' to null in sandbox fusion _process_single_case

tests/utils/test_seqlen_balancing.py, verl/protocol.py
As discussed in #2524, split should support uneven cases to avoid crash in edge cases.
Unit test added.
This PR avoids crashes like:
```
assert len(self) % split_size == 0, (
```
N/A
> [!IMPORTANT]
> Please …
=> [training_utils] fix: uneven support in split

verl/trainer/ppo/ray_trainer.py
>  fix bug for remax when the rollout mode is async, as metioned in https://github.com/volcengine/verl/issues/2551
=> [rollout] fix: fix bug for remax when the rollout mode is async

.github/CODEOWNERS
add codeowner for role/engine
cc @ZihengJiang
=> [ci] chore: add codeowner for role/engine

verl/utils/dataset/rl_dataset.py
The `filter_out_long_prompts` function incorrectly used the `messages` variable when it should have used `doc`. This led to prompts with images or videos not being filtered correctly based on length.
- If this PR breaks any API (CLI arguments, config, …
=> [trainer] fix: maybe_filter_out_long_prompts on image and video

scripts/generate_trainer_config.sh, verl/trainer/config/_generated_ppo_megatron_trainer.yaml, verl/trainer/config/_generated_ppo_trainer.yaml
- Added CONFIG_SPECS array: "config_name:output_file:config_arg" format
- Now generates both _generated_ppo_trainer.yaml and _generated_ppo_megatron_trainer.yaml
- Maintains identical output format and verification behavior
- Example: `[BREAKING][fsdp, megatron] feat: …
=> [cfg] refactor: add flatten megatron trainer config generation and verification script

examples/sft/gsm8k/run_qwen2_5_05b_sft_peft_sp2_npu.sh, examples/split_placement/main_ppo_split.py, recipe/dapo/main_dapo.py, recipe/prime/main_prime.py, recipe/spin/main_spin.py, recipe/spin/spin_trainer.py, recipe/sppo/main_sppo.py, recipe/sppo/sppo_ray_trainer.py, tests/special_npu/run_qwen2_5_05b_sft_peft_sp2.sh, verl/single_controller/ray/base.py, verl/trainer/config/sft_trainer.yaml, verl/trainer/fsdp_sft_trainer.py, verl/trainer/main_ppo.py, verl/trainer/ppo/ray_trainer.py
In some methods, the get_device() method is redundant, and we plan to replace get_deivce with config.trainer.device …
=> [hardware] refactor: replace device_name with config.trainer.device

docs/sglang_multiturn/interaction_system.rst, verl/interactions/gsm8k_interaction.py
This PR corrects a mistake when calculating rewards during training with the `gsm8k_w_interaction` setting.
- Changed the role check from "user" to "assistant" when extracting the last message content.
- Simplified response assignment by removing unnecessary prefix checks.
- Updated scoring method from "flexible" to "strict" for improved accuracy in GSM8K interactions.
- If this PR breaks any …
=> [sglang] fix: update response handling and scoring method in GSM8K interaction

verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
There is a optional config `+actor_rollout_ref.rollout.seed`, which is used in 
[https://github.com/volcengine/verl/blob/fcb1e191b758cadd3f45bb9d3ee815d979f4a1ec/verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py#L165-L185](https://github.com/volcengine/verl/blob/fcb1e191b758cadd3f45bb9d3ee815d979f4a1ec/verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py#L165-L185)
This config ensures identical initialization of vllm engine in distributed systems.
However in 
[https://github.com/volcengine/verl/blob/fcb1e191b758cadd3f45bb9d3ee815d979f4a1ec/verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py#L202](https://github.com/volcengine/verl/blob/fcb1e191b758cadd3f45bb9d3ee815d979f4a1ec/verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py#L202)
`class SamplingParam` unexpectedly adopts …
=> [rollout,vllm] fix: A major issue in random sampling of vllm engine

verl/utils/dataset/multiturn_sft_dataset.py
> This PR fixes data preprocessing issues in MultiTurnSFTDataset. Specifically, `json.loads` should not be called in `__getitem__`.
After fixing the issue, the results for [ReTool's SFT …
=> [data, recipe] fix: remove redundant json parsing

tests/single_controller/detached_worker/server.py, verl/trainer/constants_ppo.py, verl/trainer/runtime_env.yaml, verl/workers/megatron_workers.py
According to Kunlun Li 's detailed profiling work, envvar `CUDA_DEVICE_MAX_CONNECTIONS=1` was not taking effect, the benefit of this setting described here: https://github.com/NVIDIA/Megatron-LM/issues/533#issuecomment-1760193239
Try put this variable in ray `runtime_env` to take effect. This will make it a default option.
- If this PR breaks any API (CLI arguments, config, function signature, …
=> [megatron] fix: CUDA_DEVICE_MAX_CONNECTIONS not taking effect

tests/test_protocol_on_cpu.py, verl/protocol.py
This PR fixes a bug in `verl.protocol.union_numpy_dict` where it would crash on NumPy arrays with more than 2 dimensions. It replaces the underlying comparison logic with a robust, recursive function that can handle N-D arrays, nested objects, `NaN` values, and circular references.
This resolves issue #2766.
- If this PR breaks any API (CLI arguments, config, function signature, etc.), add …
=> [misc] fix: Handle N-D arrays and complex objects in union_numpy_dict

recipe/retool/retool_sft_preprocess.py
- Fix retool data preprocessing (now tools requires to be a list)
- Use more common path to save dataset
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), …
=> [recipe] fix: fix retool SFT dataset

.github/workflows/cpu_unit_tests.yml, .github/workflows/model.yml, tests/trainer/config/test_legacy_config_on_cpu.py, verl/workers/actor/dp_actor.py
The cpu unit test is broken when https://github.com/volcengine/verl/pull/2757/files is merged.
=> [cfg] fix: fix failing rollout config test on main

recipe/genrm_remote/README.md, recipe/genrm_remote/reward_function.py
Add sleep/wakeup mode for gen rm vllm service and add tqdm  showing process.
This capability is particularly beneficial when the model server shares resources with a training workload on the same machine. It allows the reward model service to be temporarily offloaded (to free up GPU memory) during intensive training sessions and reloaded when the service is required again.
=> [recipe] feat:  Add sleep/wakeup mode for gen rm vllm service and add tqdm  showing process

verl/experimental/agent_loop/agent_loop.py
From issue here:
https://github.com/volcengine/verl/issues/2677
Try to pad the `prompt`, `response` & `mask` before batch post-processing to save time
Main idea:
```python
```
Environment setup: follow this [tutorial](https://github.com/zhaochenyang20/Awesome-ML-SYS-Tutorial/blob/main/rlhf/verl/multi-turn/tool_examples/agent_loop.md)
Test config in 4 * H100
```bash
#!/bin/bash
set -x
ulimit -n 65535
export CUDA_HOME=/usr/local/cuda
export CUDA_VISIBLE_DEVICES=4,5,6,7
PROJECT_DIR="$(pwd)"
CONFIG_PATH="$PROJECT_DIR/examples/sglang_multiturn/config"
python3 -m verl.trainer.main_ppo \
--config-path="$CONFIG_PATH" \
--config-name='gsm8k_multiturn_grpo' \
algorithm.adv_estimator=grpo \
data.train_batch_size=256 \
data.max_prompt_length=1024 \
data.max_response_length=1024 \ …
```
=> [perf] feat: Padding before batch post-process in agent-loop to save time

recipe/spin/fsdp_workers.py, tests/utils/dataset/test_rl_collate_fn_on_cpu.py, verl/experimental/agent_loop/agent_loop.py, verl/utils/dataset/rl_dataset.py, verl/workers/fsdp_workers.py, verl/workers/rollout/sglang_rollout/sglang_rollout.py, verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
This PR updates the `collate_fn` logic inside `verl.utils.dataset.rl_dataset` to consistently handle non-tensor fields as 1D object arrays, preventing runtime errors during concatenation in downstream code such as `recipe/dapo/dapo_ray_trainer.py`.
- Example: …
=> [training_utils] fix: enforce 1D object array shape for non-tensor data in collate_fn

docs/advance/agent_loop.rst, recipe/langgraph_agent/react_agent_loop.py, recipe/langgraph_agent/test_react_agent_loop.py, verl/experimental/agent_loop/agent_loop.py, verl/experimental/agent_loop/single_turn_agent_loop.py, verl/experimental/agent_loop/tool_agent_loop.py
Pass all dataset fields from `RLHFDataset` to agent loop run, including:
- raw_prompt
- tools_kwargs
- multi_modal_data
- ...
=> [rollout] feat: pass all dataset fields to agent loop run

tests/utils/reward_score/reward_score/test_sandbox_fusion_on_cpu.py, verl/utils/reward_score/sandbox_fusion/__init__.py, verl/utils/reward_score/sandbox_fusion/utils.py
Support `assert_case` for sandbox fusion
Added unit test for this one
It can be useful to support `assert_case` in addition to `inputs` and `outputs`, which is seen in some datasets such as: …
=> [training_utils] feat: Support `assert_case` for sandbox fusion

.github/workflows/e2e_ascend.yml, docs/ascend_tutorial/ascend_quick_start.rst, scripts/converter_hf_to_mcore.py, tests/special_npu/run_qwen2_5_05b_grpo_mindspeed.sh, verl/utils/kernel/kernels.py, verl/workers/megatron_workers.py
Add MindSpeed(Megatron) support on the NPU device. 
First, import the Megatron adapter to avoid import errors, and reapply the patch according to the configuration. …
=> [megatron] feat: Add MindSpeed support on the NPU device

verl/trainer/ppo/core_algos.py
This PR delivers significant performance improvements to GRPO and related advantage estimation algorithms through
comprehensive tensor operation optimizations.
- **GPU**: **6.5x speedup** by fixing device placement issues
- **CPU**: **40% faster** tensor creation operations
- **Memory**: Reduced redundant allocations in training loops
- **Replace** `torch.tensor()` with `torch.stack()` for scalar tensor lists
- **Fixes** device placement bugs where `torch.tensor()` forces CPU placement
- **Preserves** GPU tensors on GPU, eliminating costly CPU-GPU transfers
- **Remove** duplicate tensor creation in statistical computation loops
- **Optimize** tensor reuse for both mean and standard deviation calculations
- **Standardize** tensor creation patterns across all algorithms
- …
=> [misc] feat: optimize GRPO-family algorithms with torch.stack and improve tensor creation consistency

tests/special_distributed/test_fsdp_ckpt.py
When we upgrade to transformers 4.54.1, the fsdp checkpoint manager test breaks, and here are some observations:
- If we switch the "attn_implementation" to "eager" or "sdpa", everything works fine. So, it suggests that the issue lies within the flash_attention_2 backend of transformers.
- Previously, this test passes in input_ids and attention_mask. However, workers in verl passes in input_ids and position_ids to utilize rmpad. After we switch the input to `input_ids` and `position_ids`, all the tests passed.
- If we do not call loss.backward, everything works fine
- So, FSDP works fine, checkpoint manager works fine. The problem must lie in how transformers handles different type of input combinations in flash_attention_2 backend.
- In this PR, we modify the input to pass the test. …
=> [ci] fix: fix fsdp test in transformers 4.54.1

verl/trainer/fsdp_sft_trainer.py
To use pin_cemory, we need to set pin_memory_name="npu".
About pin_memory, see: [torchdata/stateful_dataloader/stateful_dataloader.py](https://github.com/pytorch/data/blob/main/torchdata/stateful_dataloader/stateful_dataloader.py)
```
if self._pin_memory:
self._pin_memory_thread_done_event = threading.Event()
self._data_queue = queue.Queue()  # type: ignore[var-annotated]
if self._pin_memory_device == "xpu":
current_device = torch.xpu.current_device()  # type: ignore[attr-defined]
elif self._pin_memory_device == torch._C._get_privateuse1_backend_name():
custom_device_mod = getattr(torch, torch._C._get_privateuse1_backend_name())
current_device = custom_device_mod.current_device()
else:
current_device = torch.cuda.current_device()  # choose cuda for default
pin_memory_thread = …
```
=> [trainer, hardware] chore: add pin_memory_device when pin_memory is enabled

verl/trainer/ppo/ray_trainer.py
Moves UID generation to the beginning of batch processing, before any `pop` operations or generation steps. This change:
1. **Fixes timing for future conditioning**: Enables UID generation to condition on original batch data (e.g., prompt content) before any data is removed via `pop` operations
The change is backward-compatible and doesn't affect current functionality, but enables future enhancements where UID generation might need access to the complete original batch data.
- If this PR involves multiple modules, separate them with `,` like …
=> [trainer] fix: move UID generation before batch processing for future conditioning support

verl/trainer/fsdp_sft_trainer.py
This PR adds support for logging Config parameters to Weights & Biases (wandb) when running SFT training via fsdp_sft_trainer.py.
Previously, wandb overview panel did not include configuration details, making it harder to trace experiment setups, as shown below:
This PR ensures that all relevant config parameters are recorded, improving reproducibility and experiment tracking:
- If this PR …
=> [fsdp, trainer] fix: save config parameters to wandb in SFT

tests/single_controller/test_device_mesh_register.py, verl/single_controller/base/decorator.py, verl/single_controller/base/worker.py, verl/single_controller/base/worker_group.py
A better solution than https://github.com/volcengine/verl/pull/1260
The current dispatch methods are quite limited:
In hybrid engine, we would like to dispatch infer_tp x infer_dp for generation and train_tp x train_dp x train_pp for training. However, currently implementation can only dispatch train_tp x train_dp x train_pp for training and dp for generation and perform allgather inside the workergroup.
When two megatron models colocate, their device mesh has to be identical.
We have to subclass RayWorkerGroup in order to implement various distributed strategies. This makes create_colocated_worker hacky to implement in the future.
The difference in this implementation:
- We register directly inside the worker of the dp_rank and whether the output of this rank will be collected.
- By …
=> [ray] feat: support directly register dispatch device mesh

verl/workers/rollout/schemas.py
Fix the `input_ids` encoding logic bug. This bug appears when we have tool to init and tool init return some text or images. The output will be `<im_start>assistant\ntool\nXX` but we want just `<im_start>tool\nXX`. …
=> [rollout, sglang] fix: fix encoding logic bug

recipe/one_step_off_policy/fsdp_workers.py, recipe/spin/fsdp_workers.py, verl/single_controller/base/worker.py, verl/workers/actor/dp_actor.py, verl/workers/critic/dp_critic.py, verl/workers/fsdp_workers.py, verl/workers/megatron_workers.py
- Since we introduce register device_mesh inside the worker, there is no need to use sharding manager any longer. We will remove the usage of sharding manager gradually in the main branch. 
- This PR removes the sharding manager usage inside fsdp_workers
- Example: …
=> [misc] refactor: deprecate sharding manager (part 1)

verl/protocol.py
- Fix a severe bug in DataProto that cause modification to be incorrect
- We should not use consolidated tensordict to perform any operation other than save and data transfer
```python
import torch
from tensordict import TensorDict
a = TensorDict({"a": torch.zeros(1, 1)}, device='cuda', batch_size=[1])
a_consolidate = a.consolidate()
a['b'] = torch.ones(1, 1)
a = a.to('cpu')
a_consolidate['b'] = torch.ones(1, 1)
a_consolidate = a_consolidate.to('cpu')
print(a['a'], a['b'])  # 0, 1
print(a_consolidate['a'], a_consolidate['b'])  # 0, 0
```
- If …
=> [misc] fix: fix DataProto __getstate__ bug

examples/sglang_multiturn/run_qwen2_3b_dapo_multiturn.sh
> Fix No command 'hf' found for dapo multi-turn as alternative baseline 
> [!IMPORTANT]
=> [sglang] fix: Fix No command 'hf' found for dapo multi-turn as alternative baseline 

tests/workers/rollout/rollout_vllm/test_vllm_model_rope_scaling.py, verl/workers/rollout/vllm_rollout/vllm_async_server.py, verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
`max_num_seqs` not take effect, vllm's default value 256 sometimes is too small.
=> [rollout,vllm] fix: max_num_seqs not take effect

verl/workers/sharding_manager/fsdp_sglang.py, verl/workers/sharding_manager/fsdp_vllm.py
Move the parameter offloading step before waking up the inference engine to reduce GPU memory cap.
Changed vllm and sglang with fsdp. 
Leaving megatron unchanged because it may result illegal access with similar change.
- Example: `[BREAKING][fsdp, megatron] feat: …
=> [rollout,trainer] feat: offload param before wake up inference engine

verl/workers/rollout/sglang_rollout/sglang_rollout.py, verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
Change vLLM method to async to unify with SGLang.
=> [rollout,vllm] feat: unify vllm and sglang method to async

recipe/langgraph_agent/chat_model.py, recipe/langgraph_agent/example/README.md, recipe/langgraph_agent/example/create_dataset.py, recipe/langgraph_agent/example/run_qwen2.5_3b.sh
Fixes the LangGraph agent recipe so it runs out-of-the-box across different environments. The original example had undefined variables and brittle error handling that caused failures. This PR makes it portable, robust, and self-contained. No breaking API changes.
* `{modules}`: recipe
* `{type}`: fix
* No breaking API changes
**✅ End-to-end validation:**
```bash
python recipe/langgraph_agent/example/create_dataset.py --train_size 1000 --test_size 100
bash recipe/langgraph_agent/example/run_qwen2.5_3b.sh
sbatch recipe/langgraph_agent/example/run_qwen2.5_3b.sh
```
**Note on `GPUS_PER_NODE` and `NNODES`:**
- `GPUS_PER_NODE`: GPUs per node.  
Detection order: `SLURM_GPUS_ON_NODE` (if set) → `GPUS_PER_NODE` → `2`.
- `NNODES`: number of nodes.  
Detection order: `SLURM_JOB_NUM_NODES` (if set) → …
=> [recipe] fix: make LangGraph agent example runnable out-of-the-box

verl/utils/device.py, verl/workers/sharding_manager/fsdp_sglang.py, verl/workers/sharding_manager/fsdp_vllm.py
Enable expandable_segments to avoid the increasing memory fragmentation caused by temporary variables during the training process of fsdp2, which may trigger probabilistic out-of-memory (OOM) errors.
Since both sglang and vllm can not work with expandable_segments:True, it has to be turn off during rollout.
- If this PR breaks any API (CLI arguments, config, function signature, etc.), add …
=> [fsdp] fix: set _set_allocator_settings to True to avoid fsdp2 oom

verl/utils/flops_counter.py
add flops count support for A3 device
Not related.
Not related. …
=> [hardware] add flops count support for A3 device

verl/tools/utils/search_r1_like_utils.py
A small change from `json.dumps({"result": final_result})` to `json.dumps({"result": final_result}, ensure_ascii=False)`, supporting customized search engines that return docs containing non-ascii characters (e.g., CJK characters).
- Example: `[BREAKING][fsdp, megatron] …
=> [tool] fix: support non-ascii characters in search results

examples/split_placement/config/ppo_trainer_split.yaml, examples/split_placement/main_ppo_split.py, recipe/dapo/main_dapo.py, recipe/entropy/main_entropy.py, recipe/one_step_off_policy/main_ppo.py, recipe/prime/main_prime.py, recipe/r1/config/evaluation.yaml, recipe/r1/main_eval.py, recipe/sppo/main_sppo.py, tests/trainer/config/legacy_ppo_megatron_trainer.yaml, tests/trainer/config/legacy_ppo_trainer.yaml, verl/trainer/config/_generated_ppo_megatron_trainer.yaml, verl/trainer/config/_generated_ppo_trainer.yaml, verl/trainer/config/evaluation.yaml, verl/trainer/config/generation.yaml, verl/trainer/config/ppo_megatron_trainer.yaml, verl/trainer/config/ppo_trainer.yaml, verl/trainer/main_eval.py, verl/trainer/main_generation.py, verl/trainer/main_ppo.py
This PR adds support for passing parameters to `ray.init`.
Users can now dynamically configure settings such as `address`, `port`, `_temp_dir`, and more based on their specific needs.
```bash
bash …
```
=> [ray] feat: add support for ray init kwargs

docs/perf/dpsk.md, verl/third_party/vllm/__init__.py, verl/workers/rollout/vllm_rollout/vllm_async_server.py, verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py, verl/workers/sharding_manager/fsdp_vllm.py, verl/workers/sharding_manager/megatron_vllm.py
1. vllm sleep level=2 has bug and has been fixed: https://github.com/vllm-project/vllm/pull/16889 and the bug fixed is released in version 0.8.5: https://github.com/vllm-project/vllm/releases/tag/v0.8.5
2. fix a typo in deepseek benchmark doc.
=> [rollout] fix: vllm sleep level=2 bug

verl/utils/fsdp_utils.py
@ETOgaosion found that fsdp2 cannot work with GenericForTokenClassification in transformer==4.54.0+ https://github.com/pytorch/pytorch/issues/160068
https://github.com/volcengine/verl/pull/2947
FSDP2 complains about object layerout mismatch when constructing FSDPGenericForTokenClassification. The solution is to let FSDPModule inherit ABC as well
this should unblock @vermouth1992 on deprecating fsdp1
- If …
=> [fsdp] fix: patch fsdp2 to support hf transformer==4.54.0 and above

verl/workers/actor/dp_actor.py
Since training backend (FSDP/Megatron)'s recompute of log probs are not accurate, so given an exact batch forwarding twice, the `old_log_probs` vs `log_probs` are not the same even in on policy training. This PR quickly fix this issue.
- If this PR breaks …
=> [trainer, worker] fix: setting old log probs equal to log probs for on policy training

verl/trainer/ppo/ray_trainer.py
=> [trainer] fix: move `testing` out of `step` timings

verl/models/mcore/model_forward_fused.py, verl/workers/actor/megatron_actor.py
> This PR fixes the handling of the temperature parameter in Megatron by explicitly propagating it through the forward path. Logits are now scaled by dividing with temperature during processing, aligning Megatron with the FSDP logits handling implemented in [dp_actor.py#L192](https://github.com/volcengine/verl/blob/main/verl/workers/actor/dp_actor.py#L192). The issue became apparent when running Megatron training with temperature=0.9.
- `{type}` is in …
=> [megatron] fix: add temperature parameter for logits scaling

verl/workers/rollout/sglang_rollout/sglang_rollout.py
vllm async engine receives the  `max_num_seqs` option from yaml, 
but sglang ignore it, 
this PR patches this issue. …
=> [sglang] feat: make sglang properly handle the `max_num_seqs` configuration

docs/start/multinode.rst
Added two Ray CLI commands to the documentation for better job monitoring:
1. **Job ID Retrieval Command**  
`ray job list | grep submission_id | grep JobStatus | grep RUNNING | grep -oP 'raysubmit_[^'\''"]+' | head -n 1`  
This pipeline fetches the latest running job's submission ID by:
- Filtering active jobs (`RUNNING` status)
- Extracting `raysubmit_*` IDs
- Returning the first match
2. **Continuous Log Streaming**  
`ray job logs <Submission ID> --follow`  
Added the `--follow` parameter to enable real-time log streaming, allowing users to:
- Continuously monitor job output
- Debug long-running processes interactively
- Maintain persistent log connection until job completion
These additions enhance operational visibility for Ray job management workflows.
=> [doc] feat: documentation Update, Ray Job Management Commands

verl/workers/rollout/sglang_rollout/sglang_rollout.py
What does this PR do?
There are some unused padding talked in this issue: 
https://github.com/zhaochenyang20/Awesome-ML-SYS-Tutorial/issues/193
- There are just 5 key fields which need to return back after rollout(example in `agent_loop`):
```python
batch = TensorDict(
{
"prompts": prompt_ids,  # [bsz, prompt_length]
"responses": response_ids,  # [bsz, response_length]
"response_mask": response_mask,  # [bsz, response_length]
"input_ids": input_ids,  # [bsz, prompt_length + response_length]
"attention_mask": attention_mask,  # [bsz, prompt_length + response_length]
"position_ids": position_ids, 
},
batch_size=len(inputs),
)
``` 
- Remove some unused variable like `prompt_loss_mask`
- Make `response_position_id` all zero tensor
- Copy class to avoid constructing a new class
`over_sample = …
=> [sglang] fix: remove unused padding in SGLang rollout

verl/workers/rollout/sglang_rollout/sglang_rollout.py
Fix https://github.com/volcengine/verl/issues/3195
Changes:  
1. 🔒 Replace all direct dict[key] access with .get(key, {}) pattern for tool kwargs  
2. ✅ Add validation in _preprocess_prompt_to_async_rollout_requests  
3. 🧪 New test cases covering:  
• Missing tool configs  
• Partial execute_kwargs  
• Empty tool schemas  
Impact:  
• Prevents KeyError crashes when tools/kwargs are missing  
• Maintains existing flexible tool parameter system  
• Zero breaking changes to valid configurations
=> [Optimize]Safe tool parameter access standardization in SGLang rollout

tests/experimental/agent_loop/test_basic_agent_loop.py, verl/experimental/agent_loop/agent_loop.py, verl/workers/reward_manager/batch.py, verl/workers/reward_manager/dapo.py, verl/workers/reward_manager/naive.py, verl/workers/reward_manager/prime.py
Fix https://github.com/volcengine/verl/pull/3055, add missing `extra_reward_info` to AgentLoopOuput, which is needed by metrics calculation.
=> [rollout] fix: add missing extra_reward_info to AgentLoopOuput

verl/workers/rollout/vllm_rollout/vllm_async_server.py
=> Revert "[rollout] feat: use dummy load_format when init AsyncServer"

verl/utils/dataset/multiturn_sft_dataset.py
When using xargs to perform SFT training on multiple datasets, the …
=> [data] fix: update parquet_files type check to support multi-file input

recipe/one_step_off_policy/main_ppo.py, recipe/one_step_off_policy/ray_trainer.py, recipe/one_step_off_policy/utils.py, recipe/prime/main_prime.py, recipe/prime/prime_ray_trainer.py, recipe/spin/main_spin.py, recipe/spin/spin_trainer.py, recipe/spin/utils.py, recipe/sppo/main_sppo.py, recipe/sppo/sppo_ray_trainer.py, verl/trainer/main_ppo.py, verl/trainer/ppo/ray_trainer.py, verl/trainer/ppo/utils.py, verl/utils/config.py
Make main ppo script validate config as soon as all needed info is available. this enables the script to fail as fast as possible in case of bug in config.
New changes would avoid downloading and loading tokenizer and loading data before validating config
solve #3182 
Isolated config validation in utils (out of PpoRayTrainer) and call it from main_ppo as soon as possible.
=> [trainer] refactor: PPO config validation fast fail

README.md
The original slack link seems to be restricted to certain email domains. This one does not.
=> [doc] fix: fix slack invitation link

verl/__init__.py
In verl, the driver process aggregates the computation results of workers via Ray. Therefore, after a worker completes its computation job, it will package the output using tensordict and transfer it to the CPU. Since the `to` operation of tensordict is non-blocking, when transferring data from a device to the CPU, it is necessary to ensure that a batch of data has been completely transferred before being used on the host; otherwise, unexpected precision issues may arise. Tensordict has already noticed this problem and fixed it. Ref: https://github.com/pytorch/tensordict/issues/725
However, the relevant modifications only cover CUDA and MPS devices and do not take effect for third-party devices such as NPUs. This patch fixes this issue, and the relevant modifications can be removed once …
=> [hardware] fix: Call synchronization when using the td.to("cpu") operation on NPU to avoid potential precision issues

verl/trainer/ppo/core_algos.py
In the recent PR:
- https://github.com/volcengine/verl/pull/2953,
the file `workers/actor/dp_actor.py` was updated so that `rollout_log_probs` is passed to `policy_loss_fn`:
https://github.com/volcengine/verl/blob/38d23914ee512a125e00763fe3ddcc8df4319346/verl/workers/actor/dp_actor.py#L448-L456
In that PR, the "vanilla" policy loss function was modified to accept `rollout_log_probs` as an argument. However, other policy loss functions (e.g., "gspo") were not updated accordingly, which leads to an error such as:
```
TypeError: compute_policy_loss_gspo() got an unexpected keyword argument 'rollout_log_probs'
```
when setting `config.policy_loss.loss_mode` to one of these alternatives.
Therefore, in this PR, `rollout_log_probs` is also added as an argument to the other policy loss functions. …
=> [worker] fix: Fix missing `rollout_log_probs` argument in policy loss functions

verl/trainer/ppo/metric_utils.py, verl/trainer/ppo/ray_trainer.py
Fix #3238. Follow #2815. 
#2815 seems to have no follow-up process. This PR switched from text prompt to grouping by uid when calculating validation metrics.   
=> [misc] fix: use uid for grouping in validation to avoid prompt confusion in multimodal tasks

recipe/deepeyes/deepeyes.py, verl/utils/dataset/rl_dataset.py
Related to:
- #2447
- #2204
This PR adds support when we mix multi-modal with pure text data in the dataset, where we can set the value for the image_key or video_key to None. Most importantly, if an empty list is passed, for `Qwen2VLImageProcessorFast`, when we handle the pure text data, we should keep the `images`/`videos` parameters as None instead of an empty list, otherwise, currently, the bug in transformers will make things end up in an error:
```log
File "torchdata/stateful_dataloader/worker.py", line 242, in _worker_loop
data = fetcher.fetch(index)  # type: ignore[union-attr]
File "torch/utils/data/_utils/fetch.py", line 52, in fetch
data = …
```
=> [training_utils] fix: allow empty image_key/video_key in rl dataset

verl/models/transformers/npu_patch.py
This PR adds following  NPU fusion kernels to Qwen3 MoE model in Transformers: GroupedMatMul, SwiGLU, RMSNorm and RoPE. …
=> [fsdp] feat: add NPU fusion kernels for Qwen3 MoE

recipe/dapo/main_dapo.py
> Add concise overview of what this PR aims to achieve or accomplish. Reference related GitHub issues and PRs that help with the review.
To prevent Ascend NPU TBE errors caused by resource leakage, ensure that ray.shutdown()is explicitly called after initializing Ray with ray.init(). 
Address the first issue in https://github.com/volcengine/verl/issues/3316
- If this PR breaks any API (CLI …
=> [single_controller, ray] fix: shut ray down after initializes it

verl/trainer/fsdp_sft_trainer.py
This PR fixes the SFT loss mask, which always masked the first generated token and would lead to the SFTed model behaving as **generating the wrong first token**.
No similar PRs found
N/A for automated …
=> [trainer] fix: Correct off-by-one error in SFT loss mask slicing

recipe/dapo/dapo_ray_trainer.py
- When resuming from a checkpoint, gen_steps is not correctly restored, causing is_last_step to be misdetected.
- Switch is_last_step logic from gen_steps to self.global_steps to remove the dependency on gen_steps. …
=> [recipe] fix: (dapo_ray_trainer) use global_steps to determine is_last_step when resuming (gen_steps not restored)

tests/special_e2e/sft/test_sft_engine_all.sh, verl/utils/seqlen_balancing.py, verl/workers/engine/fsdp/engine_impl.py, verl/workers/engine/fsdp/utils.py, verl/workers/engine/utils.py, verl/workers/roles/__init__.py
- Extract a separate prepare_micro_batches
- Fix prepare_dynamic_batch
- Make `forward_step` more modular 
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), …
=> [model] refactor: polishing FSDP model engine

verl/third_party/vllm/__init__.py
Since the current vllm-ascend does not yet support sleep level = 2 - causing rewards to always be -1 - please set sleep level to 1 when using the NPU.
- If this PR breaks any API (CLI arguments, config, function signature, etc.), add `[BREAKING]` to the …
=> [vllm] fix: use VLLM_SLEEP_LEVEL=1 on ASCEND NPU

tests/experimental/agent_loop/test_agent_loop_reward.py, tests/experimental/agent_loop/test_agent_loop_reward_model.py, tests/experimental/agent_loop/test_basic_agent_loop.py, tests/experimental/agent_loop/test_multi_modal.py, tests/special_e2e/ppo_trainer/run_function_reward.sh, tests/workers/rollout/test_sglang_async_rollout_w_tools_token_out.py, tests/workers/rollout/utils_sglang.py, verl/trainer/config/_generated_ppo_megatron_trainer.yaml, verl/trainer/config/_generated_ppo_trainer.yaml, verl/trainer/config/rollout/rollout.yaml, verl/workers/config/rollout.py, verl/workers/rollout/schemas.py, verl/workers/rollout/sglang_rollout/sglang_rollout.py
This PR enables token-in-token-out functionality for the SGLang engine, improving performance by avoiding unnecessary tokenization/detokenization steps during rollout. The engine can now work directly with token IDs, and the rollout system passes pre-computed token IDs to avoid recomputation.
- If this PR breaks any API (CLI arguments, config, function signature, etc.), add `[BREAKING]` to the …
=> [sglang, rollout] feat: enable token-in-token-out for SGLang engine

tests/test_protocol_on_cpu.py, verl/protocol.py
For a data size of 6400x20480, the average serialization duration was reduced from 3.32s to 1.32s following this optimization, resulting in a ~151% improvement.
```
average  serialize：2.58s  deserialize：0.74s  total：3.32s
TaskRunner pid=1904793) baymax debug serialize time=2.5947s
(TaskRunner pid=1904793) baymax debug serialize time=2.593357s
(TaskRunner pid=1904793) baymax debug serialize time=2.580081s
(TaskRunner pid=1904793) baymax debug serialize time=2.582321s
(WorkerDict pid=1905183) baymax debug deserialize time=0.475745s
(WorkerDict pid=1905184) baymax debug deserialize time=0.538223s
(WorkerDict pid=1905181) baymax debug deserialize time=0.609146s
(WorkerDict pid=1905182) baymax debug deserialize time=0.61064s
(WorkerDict pid=1905189) baymax debug deserialize time=0.597746s …
```
=> [ray] refactor: Accelerate Tensor serialization by converting to np.ndarray

verl/models/mcore/config_converter.py, verl/trainer/config/_generated_ppo_megatron_trainer.yaml, verl/trainer/config/engine/megatron.yaml, verl/workers/megatron_workers.py
1. add mapping from string to megatron's enum for attention_backend choice.
2. use flash attention as default attention_backend, for consistency to FSDP
=> [megatron] feat: use flash as default attention_backend

docs/examples/config.rst, examples/ppo_trainer/README.md, tests/trainer/ppo/test_core_algos_on_cpu.py, verl/trainer/ppo/core_algos.py
Vectorize RLOO advantage estimator
130ms -> 6ms
Similar method can be done for other advantage estimators, I just don't have time
Implements
$$r_i - \frac{\sum_{j\ne i} r_j}{G-1} = \frac{(G-1)r_i - \sum_{j\ne i} r_j}{G-1} = \frac{G r_i - \sum_{j\in g} r_j}{G-1}$$
=> [algo, perf] feat: Vectorize RLOO Advantage Estimator - 20x Speedup

docs/examples/config.rst, tests/trainer/ppo/test_core_algos_on_cpu.py, tests/utils/test_groupwise.py, verl/trainer/ppo/core_algos.py, verl/utils/__init__.py, verl/utils/groupwise.py
Implements a vectorized GRPO advantage path for outcome-only RL in core_algos.py, keeping the original implementation intact and selectable. This yields large speedups at medium–large batch sizes by replacing Python-side grouping loops with segment reductions and one-pass gathers.
Results (CPU, Apple M-series example; float32):
```shell
[CPU] bs=  512 T= 512 G= 10 | orig=5.47ms vec=0.21ms speedup=26.16x
[CPU] bs= 1024 T=1024 G= 16 | orig=11.05ms vec=0.54ms speedup=20.60x
[CPU] bs= 2048 T=2048 G= 32 | orig=23.20ms vec=1.74ms speedup=13.32x
```
```shell
[GRPO] seed=0 groups=5 shape=torch.Size([64, 128]) mask_tokens=4147 adv_max_diff=2.384e-07 ret_max_diff=2.384e-07
[GRPO] seed=1 groups=8 shape=torch.Size([128, 256]) mask_tokens=16364 adv_max_diff=2.384e-07 ret_max_diff=2.384e-07
[GRPO] …
```
=> [algo, perf] feat: Vectorize GRPO Advantage Estimator - 13～26x Speedup 

verl/workers/actor/megatron_actor.py
Follow up for #3553
Without those changes in #3315, the error when we train the mixture modal dataset will remain unresolved, so it would be a good idea to add them back.
```logs
File "verl/workers/actor/megatron_actor.py", line 639, in update_policy
metric_micro_batch = self.forward_backward_batch(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "verl/workers/actor/megatron_actor.py", line 587, in forward_backward_batch
losses_reduced = forward_backward_func(
^^^^^^^^^^^^^^^^^^^^^^
File "megatron/core/pipeline_parallel/schedules.py", line 595, in forward_backward_no_pipelining
output_tensor, num_tokens = forward_step(
^^^^^^^^^^^^^
File …
```
=> [megatron, worker] fix: use `extract_multi_modal_inputs` method for handling `multi_modal_inputs`

verl/models/transformers/glm4v.py, verl/models/transformers/qwen2_vl.py
On top of #3496
Possibly resolve #3665
This PR continue addressing the hanging issue as mentioned here: https://github.com/volcengine/verl/pull/3315#issuecomment-3315362541
It should be pretty safe and optional to do `model.training` checks even the model is in inference mode, as the value of `inputs_embeds` won't get modified anyway.
- If this PR involves multiple modules, separate them with `,` like …
=> [model] fix: stuck issue with mixed text-image data

verl/experimental/agent_loop/agent_loop.py
> Fix qwen2_vl position_id shape mismatch: `verl/models/transformers/qwen2_vl.py:process_position_ids` expects `position_ids` to have a shape of `(4, batch_size, seq_length)` but `verl/experimental/agent_loop/agent_loop.py:generate_sequences` returns `(batch_size, 3, seq_length)` (which will be transposed to `(3, batch_size, seq_length)`), ignoring the text dimension. This PR follows the relevant code in `verl/utils/dataset/rl_dataset.py` to fix the issue.
- If this PR involves multiple modules, separate them with `,` like `[megatron, fsdp, …
=> [rollout] fix: qwen2_vl position_ids shape mismatch

verl/models/transformers/qwen2_vl.py, verl/models/transformers/qwen3_vl.py
Fix qwen3vl patch for pure text training
https://github.com/volcengine/verl/pull/3681#issuecomment-3370051513
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), …
=> [model] fix: qwen3vl patch

verl/trainer/fsdp_sft_trainer.py
Enable fused adamw which should be generally faster and more memory efficient. 
Also provide the config parameter to set eps.
In our internal code base, we always set fused adamw to True and works fine. …
=> [trainer] feat: Enabled fused adamw
