volcengine/verl

- tests/ray/check_worker_alive/main.py
- tests/ray/detached_worker/README.md
- tests/ray/detached_worker/client.py
- tests/ray/detached_worker/run.sh
- tests/ray/detached_worker/server.py
- tests/ray/test_check_worker_alive.py
- tests/ray/test_colocated_workers.py
- tests/ray/test_data_transfer.py
- tests/ray/test_driverfunc_to_worker.py
- tests/ray/test_high_level_scheduling_api.py
- tests/ray/test_ray_local_envs.py
- tests/ray/test_remote_api.py
- tests/ray/test_rvdz.py
- tests/ray/test_worker_group_basics.py
- tests/ray/test_worker_group_torch.py
- Upload several test files for ray single-controller directory
- [TODO] build up CI procedure on Github
> [ci] feat: add test files for ray hybrid programming model

- .github/workflows/yapf_format.yml
- docs/preparation/prepare_data.rst
- tests/ray/detached_worker/client.py
- tests/ray/detached_worker/server.py
- verl/third_party/vllm/vllm_v_0_5_4/hf_weight_loader.py
- verl/trainer/ppo/hybrid_engine/fsdp_vllm.py
- verl/trainer/ppo/rollout/vllm_rollout/vllm_rollout.py
> [misc] fix issue in hf_weight_loader and fix typo in doc

- README.md
- docs/preparation/install.rst
- requirements.txt
- setup.py
- verl/third_party/vllm/__init__.py
- verl/third_party/vllm/vllm_v_0_6_3/__init__.py
- verl/third_party/vllm/vllm_v_0_6_3/arg_utils.py
- verl/third_party/vllm/vllm_v_0_6_3/config.py
- verl/third_party/vllm/vllm_v_0_6_3/dtensor_weight_loaders.py
- verl/third_party/vllm/vllm_v_0_6_3/hf_weight_loader.py
- verl/third_party/vllm/vllm_v_0_6_3/llm.py
- verl/third_party/vllm/vllm_v_0_6_3/llm_engine_sp.py
- verl/third_party/vllm/vllm_v_0_6_3/megatron_weight_loaders.py
- verl/third_party/vllm/vllm_v_0_6_3/model_loader.py
- verl/third_party/vllm/vllm_v_0_6_3/model_runner.py
- verl/third_party/vllm/vllm_v_0_6_3/parallel_state.py
- verl/third_party/vllm/vllm_v_0_6_3/spmd_gpu_executor.py
- verl/third_party/vllm/vllm_v_0_6_3/tokenizer.py
- verl/third_party/vllm/vllm_v_0_6_3/worker.py
- verl/trainer/ppo/hybrid_engine/__init__.py
- verl/trainer/ppo/rollout/vllm_rollout/vllm_rollout.py
- The SPMD version of vLLM 0.6.3
- Test and change the installation issue in README.
```bash
pip3 install vllm==0.6.3 # will install ray==2.40
pip3 install ray==2.10 # seems it's not necessary. Will test this in later pr
```
> [rollout] feat: support vLLM v0.6.3 and fix hf rollout import issue

- README.md
- docker/Dockerfile.ngc.vllm
- docker/Dockerfile.vemlp.vllm
- docker/Dockerfile.vemlp.vllm.te
Below are the steps to install veRL in your environment.
- **Python**: Version >= 3.9
- **CUDA**: Version >= 12.1
veRL supports various backends. Currently, the following configurations are available:
- **FSDP** and **Megatron-LM** for training.
- **vLLM** for rollout generation.
**Training backends**
We recommend using **FSDP** backend to investigate, research and prototype different models, datasets and RL algorithms. The guide for using FSDP backend can be found in [PyTorch FSDP Backend](https://verl.readthedocs.io/en/latest/workers/fsdp_workers.html)
For users who pursue better scalability, we recommend using **Megatron-LM** backend. Currently, we support Megatron-LM@core_v0.4.0 and we fix some internal issues of Megatron-LM. Here's the additional installation guide. The guide for …
> [distro] feat: add docker support

- docs/advance/fsdp_extension.rst
- docs/experiment/ppo.rst
- As titled
- From https://github.com/volcengine/verl/issues/66
Preview: <img width="767" alt="截屏2024-12-31 下午1 20 40" src="https://github.com/user-attachments/assets/1319ef06-07dc-4915-81c0-288d3785d4c7" />
> [doc] fix: experiment section url

- examples/split_placement/config/ppo_trainer_split.yaml
- verl/trainer/config/ppo_megatron_trainer.yaml
- verl/trainer/config/ppo_trainer.yaml
- verl/trainer/ppo/ray_trainer.py
- verl/workers/fsdp_workers.py
- verl/workers/rollout/vllm_rollout/vllm_rollout.py
> [rollout] feat: support best-of-n generation in vLLM

- tests/utility/test_tensor_dict_utilities.py
- verl/protocol.py
- Fixed the missing repeat function reported in https://github.com/volcengine/verl/pull/81
- Add several data protocol functions that will be beneficial for future features
> [misc] feat: add several useful functions in protocol

- docker/Dockerfile.ngc.vllm
- examples/ppo_trainer/run_deepseek_megatron.sh
Image:
`verlai/verl:ngc-th2.4.0-cu124-vllm0.6.3-te1.7-v0.0.4`
> [docker] megatron: add TE to ngc dockerfile

- verl/trainer/ppo/ray_trainer.py
- Deprecate argument `data.val_batch_size`. By default, the batch size of validation is len(self.val_dataset).
- Add pad and unpad logic to make `test_gen_batch_padded` be divisible by self.actor_rollout_wg.world_size
fix #78 close #78
> [misc] fix: fix validation dp_size. fix #78

- README.md
> [doc] fix readme link issue and add citation

- tests/utility/test_tensor_dict_utilities.py
- verl/protocol.py
- forbid uneven chunk for DataProto
> [dataproto] fix: add assertion for uneven chunk

- .github/workflows/e2e_sft.yml
- tests/sft/run_sft.sh
- verl/trainer/config/sft_trainer.yaml
- verl/trainer/fsdp_sft_trainer.py
- Support training several iters in SFT trainer
- Add CI for SFT trainer to train one iter.
> [ci] feat: add ci for sft trainer

- verl/workers/fsdp_workers.py
> [misc] fix: only return old_log_prob and temp to fix union problem in old_log_prob

- docs/index.rst
- docs/perf/perf_tuning.rst
> [doc] perf: add performance tuning guide for FSDP backend

- examples/ppo_trainer/run_qwen2-7b_rm.sh
- verl/trainer/config/ppo_trainer.yaml
- As titled
- Setting enable_chunked_prefill: True could lead to 3-5% rollout generation throughput benefit
> [misc] feat: enable grad ckpt as default and enable chunk prefill as default

- verl/workers/fsdp_workers.py
> fix bug：无法保存checkpoint，报错

- verl/workers/actor/dp_actor.py
> [misc] fix: grpo kl loss should be add when do minimization

- .github/workflows/e2e_gsm8k_megatron.yml
- docs/start/install.rst
- tests/e2e/run_deepseek_megatron.sh
- verl/single_controller/ray/megatron.py
- verl/trainer/ppo/ray_trainer.py
- verl/utils/config.py
- verl/workers/actor/megatron_actor.py
- verl/workers/critic/megatron_critic.py
- verl/workers/megatron_workers.py
fixes https://github.com/volcengine/verl/issues/157
> megatron: fix config error and add compute log prob interface

- docs/workers/ray_trainer.rst
> docs: update ray_trainer.rst

- docs/examples/gsm8k_example.rst
sry missed this last one, should be it 
cc @vermouth1992
> fixed link in gsm8k_example.rst

- verl/workers/fsdp_workers.py
This PR is similar to PR https://github.com/volcengine/verl/pull/174 but fix the critic save error
I move the old PR to this one due to some redundant commit
> fix critic save error

- verl/workers/fsdp_workers.py
- As titled
- Relevant: https://github.com/volcengine/verl/issues/181
> [misc] fix: load and offload in compute log prob

- .github/workflows/scorecard.yml
Install the scorecard workflow
> Create scorecard.yml for security scan

- .github/workflows/model.yml
- .gitignore
- tests/checkpoint/test_fsdp_ckpt.py
- verl/utils/checkpoint/__init__.py
- verl/utils/checkpoint/checkpoint_manager.py
- verl/utils/checkpoint/fsdp_checkpoint_manager.py
- verl/utils/dataset/rm_dataset.py
- verl/utils/fs.py
- Support FSDPCheckpointManager
- Support hdfs_io import if installed
- Add CI for FSDPCheckpointManager
TODO:
- Will integrate in the next PR
> [misc] feat: add ckpt manager in utils

- tests/sft/run_sft_qwen05_peft.sh
- tests/sft/run_sft_qwen05_sp2_liger.sh
> Fix typo tips in bash sft.

- requirements.txt
- verl/workers/fsdp_workers.py
- verl/workers/sharding_manager/fsdp_ulysses.py
add requirements to make some CI tests work
> add requirements

- docs/examples/ppo_code_architecture.rst
- docs/hybrid_flow.rst
- docs/perf/perf_tuning.rst
- docs/workers/fsdp_workers.rst
> [doc] fix document deprecated link

- verl/workers/actor/megatron_actor.py
> delete redundant append_to_dict

- .github/workflows/sandbox.yml
- docs/examples/config.rst
- pyproject.toml
- requirements.txt
- tests/sandbox/test_sandbox.py
- tests/sanity/check_license.py
- verl/trainer/config/ppo_trainer.yaml
- verl/trainer/main_ppo.py
- verl/utils/reward_score/__init__.py
- verl/utils/reward_score/prime_code/__init__.py
- verl/utils/reward_score/prime_code/testing_util.py
- verl/utils/reward_score/prime_code/utils.py
- verl/utils/reward_score/prime_math/__init__.py
- verl/utils/reward_score/prime_math/grader.py
- verl/utils/reward_score/prime_math/math_normalize.py
- verl/workers/reward_manager/__init__.py
- verl/workers/reward_manager/naive.py
- verl/workers/reward_manager/prime.py
Add stronger verification support as is used in https://github.com/PRIME-RL/PRIME
Re-opening https://github.com/volcengine/verl/pull/207 to trigger automatic workflows
> Add stronger reward verification sandbox

- verl/trainer/main_ppo.py
give main_task num_cpus=1 and make sure that main_task should not be scheduled on head
> [misc] feat: give main_task num_cpus=1

- .github/workflows/e2e_gsm8k.yml
- .github/workflows/e2e_lora.yml
- .github/workflows/e2e_sft.yml
- tests/e2e/run_qwen_gsm8k_function_rm.sh
- verl/workers/megatron_workers.py
> [ci] fix: delete ckpts after saving in github runner

- verl/single_controller/base/worker.py
1  i see `WG_BACKEND` will == 'ray'
2 i can not found the pkg about ' from verl.single_controller.torchrpc.k8s_client import get_ip_addr'
would these changes is ok for that?
> clean 'WG_BACKEND' unused code.

- .github/workflows/dataset.yml
- .github/workflows/e2e_digit_completion.yml
- .github/workflows/e2e_gsm8k.yml
- .github/workflows/e2e_gsm8k_megatron.yml
- .github/workflows/e2e_lora.yml
- .github/workflows/e2e_sft.yml
- .github/workflows/model.yml
- .github/workflows/ray_test.yml
- .github/workflows/sandbox.yml
- .github/workflows/sanity.yml
- .github/workflows/vllm.yml
- .github/workflows/yapf_format.yml
We need to specify the minimum  permission in the workflow.
> Added content permissions of the workflow

- docs/faq/faq.rst
- examples/slurm/ray_on_slurm.slurm
A working Slurm example adapted from https://docs.ray.io/en/latest/ray-core/starting-ray.html
> docs: add an example for Ray on Slurm

- verl/utils/megatron/optimizer_config.py
> chore: update optimizer_config.py

- verl/utils/tracking.py
Tracking backend support vemlp wandb
> feat: tracking support vemlp

- verl/workers/actor/dp_actor.py
- verl/workers/critic/dp_critic.py
See issue: https://github.com/volcengine/verl/issues/342
> [fix] Passing ppo_epochs to dp_actor.py

- verl/utils/tracking.py
Add tensorboard in Tracking backends.
The user can set the environment variable TENSORBOARD_DIR to specify the TensorBoard log path.
> [feat] tracking support tensorboard

- verl/trainer/ppo/ray_trainer.py
This is an enhancement for the single batch strategy for `val_dataloader`, making https://github.com/volcengine/verl/pull/353 more robust.
> [Feature] Assert Single Batch for `val_dataloader`

- verl/trainer/fsdp_sft_trainer.py
- verl/trainer/ppo/ray_trainer.py
Validation should not have shuffling.
> [Fix] No Shuffling for `val_dataloader`

- README.md
> [doc] add Code-R1 to readme awesome work

- docs/README_vllm0.7.md
fix https://github.com/volcengine/verl/issues/438
> vllm: fix issue #438

- verl/single_controller/base/worker.py
> Revert "fix: bind the port with IP address"

- verl/trainer/config/generation.yaml
forget to update params in generation.yaml #259
> [fix] update yaml file for generation

- README.md
- examples/data_preprocess/geo3k.py
- examples/grpo_trainer/run_qwen2_5_vl-7b.sh
- verl/utils/reward_score/geo3k.py
- verl/workers/reward_manager/naive.py
- verl/workers/reward_manager/prime.py
1. Separate the prompt part and the response part in reward manager to avoid the reward leakage of format reward.
2. Update the reward score function for Geometry3k dataset.
3. Update the content in the readme file.
@vermouth1992 @PeterSH6
> [fix] separate prompt and response in reward manager

- .github/workflows/e2e_ascend.yml
This PR is a continuing work of #448 , in order to support e2e CI for Ascend NPU.
> [CI] Add e2e_ascend CI

- docs/examples/config.rst
This pull request includes updates to the `docs/examples/config.rst` file to enhance the documentation for the `Trainer` configuration. The most important changes involve expanding the support for various logging platforms.
Documentation updates:
* [`docs/examples/config.rst`](diffhunk://#diff-f051f6df5187cb4805be686b3d10c480877a01e9a35ed98cd63cf8da6af03772L352-R354): Updated the descriptions for `trainer.project_name`, `trainer.experiment_name`, and `trainer.logger` to include support for additional logging platforms such as swanlab, mlflow, and tensorboard.
> [docs] update logger

- .github/workflows/e2e_ascend.yml
- .github/workflows/e2e_digit_completion.yml
- .github/workflows/e2e_digit_completion_fire.yml
- .github/workflows/e2e_gsm8k.yml
- .github/workflows/e2e_gsm8k_megatron.yml
- .github/workflows/e2e_lora.yml
- .github/workflows/e2e_sft.yml
- .github/workflows/e2e_vlm_geo3k.yml
- .github/workflows/model.yml
- .github/workflows/ray_test.yml
- .github/workflows/sandbox.yml
- .github/workflows/sanity.yml
- .github/workflows/vllm.yml
Set timeout in CI to avoid infinite hang.
close #468
> [ci] feat: add ci timeout

- verl/trainer/ppo/ray_trainer.py
> misc: precheck resource pool available to prevent pg hang

- verl/third_party/vllm/vllm_spmd/hf_weight_loaders.py
This commit adds compatibility with vLLM 0.7.3 by enhancing the 
load_hf_weights function to dynamically handle different layer requirements. https://github.com/volcengine/verl/issues/521
> [bugfix] Fix compatibility with vLLM 0.7.3 in load_hf_weights function

- .github/workflows/vllm.yml
- tests/generation/run_gen_qwen05.sh
- verl/third_party/vllm/__init__.py
- verl/third_party/vllm/vllm_spmd/hf_weight_loaders.py
- verl/workers/sharding_manager/fsdp_vllm.py
- Support HF_Loader in vllm > 0.7 to support world_size = 1 generation
Credit to: @GeLee-Q
> [misc] feat: support vllm>0.7 world size 1 generation

- verl/workers/fsdp_workers.py
This PR removes several unnecessary `empty_cache` to improve efficiency.
Credit to @PeterSH6
> [Efficiency] feat: remove unnecessary empty_cache

- docs/start/install.rst
- docs/workers/megatron_workers.rst
Urgently update megatron core_r0.11.0 documentation.
> [doc] update megatron core_r0.11.0 documentation

- verl/trainer/main_generation.py
- Corrected dummy size to avoid faulty communication.
- Fixed batch number calculation.
- Adjusted worker group role to alleviate memory overhead.
- Add ray.init() to prevent failing to register worker.
> [bugfix] fix: generation script

- verl/trainer/ppo/ray_trainer.py
https://github.com/volcengine/verl/pull/549
> fix bug #544 that 'left' and 'right' config for truncation don't work

- docs/faq/faq.rst
- examples/slurm/ray_on_slurm.slurm
Follow-up to https://github.com/volcengine/verl/pull/309
> docs: fix hardcoded parameters in the Slurm example

- docs/index.rst
- docs/start/multinode.rst
- requirements.txt
> doc: add multinode training and debug tutorial

- docs/examples/config.rst
- examples/split_placement/config/ppo_trainer_split.yaml
- recipe/prime/config/prime_trainer.yaml
- recipe/prime/prime_fsdp_workers.py
- verl/trainer/config/ppo_megatron_trainer.yaml
- verl/trainer/config/ppo_trainer.yaml
- verl/workers/fsdp_workers.py
This PR adds the `lr_warmup_steps` configuration.
Note the `num_warmup_steps` is prior to `lr_warmup_steps_ratio`.
> [config] feat: lr_warmup_steps

- verl/trainer/config/ppo_megatron_trainer.yaml
- verl/trainer/config/ppo_trainer.yaml
- verl/trainer/ppo/core_algos.py
- verl/workers/actor/dp_actor.py
> [misc] feat: support token_level_loss and support different clip range for low and high

- docs/start/install.rst
Fix issue mentioned #598 by resetting python to `3.10`
> [fix] fix python env issue in install

- README.md
add MetaSpatial in Awesome Work using EasyR1
> readme: add MetaSpatial project

- README.md
This PR adds **DeepEnlighten** to the "Awesome Work Using Verl" section.
> Added DeepEnlighten to Awesome Work Using Verl section

- verl/trainer/ppo/ray_trainer.py
Commit c342069 Rebase caused error. Try to revert and add an assertion check.
> [Bug Fix] Revert the RLHFDataset truncation config

- verl/trainer/main_ppo.py
Use ray actor instead of task to run main_task
- Ray task is retried in system error(oom/segmentfault), which may cause unexpectedly behavior
- Actor is more trackable in ray dashboard, e.g logging/stacktrace/profile
close #539
> misc: change main_task to TaskRunner actor

- README.md
We propose a more accurate description of DeepRetrieval.
Thanks for your awesome work!
> Update the description of DeepRetrieval

- README.md
Adding Openmanus-RL: a llm agent rl tunning repo with verl
> Adding Openmanus-RL to the Awesome work

- README.md
- docker/Dockfile.ngc.vllm0.8
- docs/README_vllm0.8.md
- docs/index.rst
Add document for using vLLM 0.8 in verl
@eric-haibin-lin
> docs: add vllm 0.8 page

- verl/trainer/main_ppo.py
- verl/workers/rollout/sglang_rollout/sglang_rollout.py
As per the title. Thanks @zhc7
> [Bug Fix] Fix SGLang rollout error under multi node

- .github/workflows/model.yml
- verl/models/transformers/llama.py
- verl/models/transformers/monkey_patch.py
- verl/models/transformers/qwen2.py
https://github.com/volcengine/verl/issues/703
> fix: support transformers==4.50.0

- verl/trainer/ppo/ray_trainer.py
Add tqdm progress bar to RayPPOTrainer for training visualization
This PR enhances the RayPPOTrainer class by implementing a progress bar that visualizes the training process:
- Imported tqdm module in verl/trainer/ppo/ray_trainer.py (line 27)
- Added progress bar initialization in the fit() method (line 781)
- Implemented progress updates during training iterations (line 931)
- Added proper cleanup by closing the progress bar at the end of training (line 928)
This improvement provides real-time feedback on training progress, making it easier to monitor long-running training sessions.
> Add tqdm progress bar to RayPPOTrainer to visualize training progress

- docs/start/install.rst
> docs: fix sglang installation rendering

- recipe/prime/prime_fsdp_workers.py
- verl/trainer/config/ppo_megatron_trainer.yaml
- verl/trainer/config/ppo_trainer.yaml
- verl/trainer/config/sft_trainer.yaml
- verl/trainer/ppo/ray_trainer.py
- verl/utils/checkpoint/checkpoint_manager.py
- verl/utils/checkpoint/fsdp_checkpoint_manager.py
- verl/utils/checkpoint/megatron_checkpoint_manager.py
- verl/workers/fsdp_workers.py
- verl/workers/megatron_workers.py
Sometimes its space consuming to save too many old checkpoints
> [Feat] add max_ckpt_to_keep for old ckpt removal

- examples/data_preprocess/math_dataset.py
The dataset name is MATH-lighteval instead of GSM8k
> Update math_dataset.py to fix typo in the annotation

- docs/examples/config.rst
update the config doc per https://github.com/volcengine/verl/pull/822
> [doc] add log_val_generations in trainer

- verl/trainer/config/ppo_megatron_trainer.yaml
- verl/trainer/config/ppo_trainer.yaml
- verl/workers/fsdp_workers.py
- verl/workers/megatron_workers.py
To keep consistent with
https://github.com/volcengine/verl/blob/816dacc7da4d90c19e04b6d503486cc08b5a574a/verl/workers/fsdp_workers.py#L117
> [critic] fix: normalize mini batch size for critic

- recipe/prime/prime_core_algos.py
- recipe/prime/prime_dp_rm.py
- recipe/prime/prime_fsdp_workers.py
- verl/trainer/ppo/core_algos.py
- verl/trainer/ppo/ray_trainer.py
- verl/utils/megatron/tensor_parallel.py
- verl/utils/torch_functional.py
- verl/workers/actor/dp_actor.py
- verl/workers/actor/megatron_actor.py
- verl/workers/critic/dp_critic.py
- verl/workers/critic/megatron_critic.py
- verl/workers/rollout/hf_rollout.py
- verl/workers/rollout/sglang_rollout/sglang_rollout.py
- verl/workers/rollout/vllm_rollout/fire_vllm_rollout.py
- verl/workers/rollout/vllm_rollout/vllm_rollout.py
- verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
https://github.com/volcengine/verl/pull/868#discussion_r2024416560
> fix: misleading eos_mask->response_mask

- docs/examples/config.rst
https://github.com/volcengine/verl/pull/777#discussion_r2024195591
> docs: add config docs for evaluation.yaml

- verl/trainer/ppo/core_algos.py
> [algo] misc: remove redundant tile([1, response_length]), efficient broadcast instead

- scripts/diagnose.py
- scripts/format.sh
- scripts/model_merger.py
add dependency detector for vllm/sglang, as well as cuda info
usage: `python3 scripts/diagnose.py`
> tool: add diagnosis script

- docker/Dockerfile.sglang
As stated in #915 , add the dockerfile for building verl-sglang image
> add verl-sglang dockerfile

- verl/trainer/ppo/core_algos.py
> fix: seq-mean-token-sum loss

- verl/workers/fsdp_workers.py
Fix issue when not switching the chat template, `rm_data` is undefined
> Fix computer_score in fsdp_workers.py

- verl/trainer/ppo/core_algos.py
- verl/trainer/ppo/ray_trainer.py
[fix] misleading eos_mask->response_mask for reinforce_plus_plus_baseline.
> [fix] eos_mask to response_mask for reinforce++-baseline method

- verl/trainer/ppo/metric_utils.py
- verl/trainer/ppo/ray_trainer.py
This PR:
1. calculate metrics for "reward" by default if "acc"s are not avaiblable
2. don't calculate majority voting metrics if "pred"s are not available
> [log] fix: validation metrics

- verl/workers/fsdp_workers.py
Support to set warmup_style=='cosine'.
> fix: optim.warmup_style do not take effect (#418)

- verl/trainer/ppo/metric_utils.py
> fix: return list from bootstrap_metric

- scripts/model_merger.py
Currently the model merger does not support HSDP (the `ddp` mesh dim is not considered). This PR fixes this.
> Add support to HSDP model merging.

- .github/workflows/model.yml
- scripts/model_merger.py
- tests/distributed/test_tensor_dict.py
- verl/utils/megatron/tensor_parallel.py
Reduce entropy loss computation in megatron that supports tensor parallelism. Reduce the peak memory during forward and backward to only 2 * logits
> [megatron] feat: optimize entropy loss

- verl/trainer/config/ppo_megatron_trainer.yaml
> reset default tp size

- verl/models/mcore/readme.md
> mcore readme

- scripts/diagnose.py
> chore: update diagnose.py

- .github/workflows/e2e_ppo_trainer.yml
> CI: add vlm CI for sglang rollout

- .github/workflows/vllm.yml
- tests/generation/run_gen_qwen05.sh
Trying to fix network errors like
```
huggingface_hub.errors.HfHubHTTPError: 429 Client Error: Too Many Requests for url: ...
```
> [CI] feat: try HF_HUB_OFFLINE to fix network errors

- .github/workflows/e2e_ppo_trainer.yml
- .github/workflows/vllm.yml
- docker/Dockerfile.ngc.vllm0.8
- docs/README_vllm0.8.md
- verl/workers/sharding_manager/fsdp_vllm.py
- verl/workers/sharding_manager/megatron_vllm.py
- Upgrade docker image to vllm 0.8.3 to avoid memory leakage
- Add wake up tags to megatron rollout worker
@vermouth1992 @BearBiscuit05 @ETOgaosion
> doc: upgrade to vllm 0.8.3

- docs/start/install.rst
> Update install.rst to fix a typo

- verl/workers/actor/dp_actor.py
> fix: missed loss_agg_mode in dp_actor

- verl/trainer/main_generation.py
The main generation should use the padding/unpad from verl.protocol to align with ray_trainer, instead of a seperate padding/unpad logic.
Also make small improvements to make code looks better.
> refactor: main generation should also use pad/unpad from verl.protocol

- docs/start/install.rst
- docs/start/multinode.rst
The way to use ray has changed.
Ray related issue: https://github.com/ray-project/ray/issues/52454
> rewrite multi-node doc

- recipe/dapo/test_dapo_7b.sh
Seems like there's an extra argument here that's causing an error when running
> Update test_dapo_7b.sh to remove extra line

- docs/start/multinode.rst
> revert multinode first

- setup.py
We have upgrade vllm to 0.8.3 in our docker file: https://github.com/volcengine/verl/blob/main/docker/Dockerfile.ngc.vllm0.8
> fix vllm version in setup.py

- docker/Dockerfile.sglang
Install ray[default] to include missing components
> docker: update Dockerfile.sglang

- verl/trainer/ppo/ray_trainer.py
Solves #1251
Right now the current global step and current epoch are not being logged. This would be a useful feature.
> [FEAT] Add step and epoch metrics

- .github/workflows/e2e_ppo_trainer.yml
- docker/Dockerfile.sglang
- docs/start/install.rst
- setup.py
- tests/e2e/ppo_trainer/run_function_reward.sh
- verl/utils/net_utils.py
- verl/workers/rollout/sglang_rollout/sglang_rollout.py
The ipv6 part is picked from https://github.com/volcengine/verl/pull/1184 cc @BearBiscuit05
> [SGLang] upgrade to 0.4.5.post3 & fix ipv6

- docs/amd_tutorial/amd_vllm_page.rst
Update AMD performance tuning documentation according to @yushengsu-thu's suggestion.
1. fix git branch and link
2. fix tab
> [AMD] Update AMD performance tuning documentation

- recipe/dapo/src/dapo_ray_trainer.py
- recipe/prime/prime_ray_trainer.py
> [bugfix] fix: add `await` for  `_validate()`

- recipe/dapo/src/dapo_ray_trainer.py
- recipe/dapo/src/main_dapo.py
- recipe/prime/main_prime.py
- recipe/prime/prime_ray_trainer.py
- tests/rollout/test_vllm_multi_turn.py
- verl/trainer/main_ppo.py
- verl/trainer/ppo/ray_trainer.py
- verl/workers/rollout/async_server.py
Move AsyncLLM ChatCompletionScheduler to separate thread to avoid making PPOTrainer async class.
> feat: move AsyncLLM ChatCompletionScheduler to separate thread

- verl/utils/checkpoint/fsdp_checkpoint_manager.py
fix a minor typo of printing optim saving path in fsdp_checkpoint_manager.py
> fix: typo of fsdp_checkpoint_manager saving optim path

- docs/examples/multi_modal_example.rst
- docs/index.rst
- scripts/model_merger.py
There is currently no docs support for multimodal task on verl, so I think we need to add a related document.
> [doc] add the multi modal doc

- README.md
- docs/faq/faq.rst
Add one-line overview of what this PR aims to achieve or accomplish. 
- Add two reference blogs to README
None
- [] Did you write any test cases if neccessary? No tests needed
> docs: add community blogs and fix link rendering

- .github/PULL_REQUEST_TEMPLATE.md
This PR tries to imporve the PR template itself.
> [dev] feat: improve PR template

- docs/_static/js/runllm-widget.js
- docs/conf.py
- verl/utils/fsdp_utils.py
Add runllm widget for https://app.readthedocs.org/projects/verl/ 
```python
```
> Add runllm widget for VeRL Doc sites

- recipe/dapo/src/dapo_ray_trainer.py
- recipe/prime/prime_ray_trainer.py
- verl/trainer/ppo/metric_utils.py
- verl/trainer/ppo/ray_trainer.py
1. Fix the error that `metric` is not added when `n == 1`.
2. Remove `std@1`.
3. Add assertation for doing initial validation but `val_metrics` is empty. 
- **Issue Number**: none
> [dev] fix: validation metrics

- .github/workflows/dataset.yml
- .github/workflows/e2e_dapo.yml
- .github/workflows/e2e_eval_aime24.yml
- .github/workflows/e2e_ppo_trainer.yml
- .github/workflows/e2e_ppo_trainer_megatron.yml
- .github/workflows/e2e_prime.yml
- .github/workflows/e2e_sft.yml
- .github/workflows/model.yml
- .github/workflows/ray_cpu_test.yml
- .github/workflows/ray_gpu_test.yml
- .github/workflows/sgl.yml
- .github/workflows/verl_unit_test.yml
- .github/workflows/vllm.yml
- tests/checkpoint/test_fsdp_ckpt.py
1. Separate the FSDP2 test to avoid blocking other tests.
2. Fix the CI trigger rule to avoid redundant runs (since I find the original PR triggers unrelated tests, so I fix the rule based on [the doc](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore))
For 2, I test by commenting out the matching path for workflow `.yml`, and see only related workflows are triggered:
Before: <img width="870" alt="image" src="https://github.com/user-attachments/assets/2f7dbe0c-f638-4a75-8cbc-a364081271fc" />
After: <img width="869" alt="image" src="https://github.com/user-attachments/assets/f5a35d85-f03c-452e-abed-3ca3ce22d699" />
- **Issue Number**: https://github.com/volcengine/verl/issues/1388
- **Training**: …
> [CI] feat: separate FSDP2 test & fix: CI trigger

- recipe/sppo/README.md
Just add a line of code to git clone verl. I do not know why this is missed. lol
```python
```
> Update guidance of sppo

- verl/utils/dataset/rm_dataset.py
[BUG] This issue addresses the bug related to the RM data attention mask, which was also mentioned in a previous [issue](https://github.com/volcengine/verl/issues/1341). The fix has been implemented to ensure proper functionality.
> Fix for RM Data Attention Mask Bug

- examples/sglang_multiturn/README.md
Fix format issue and data_preprocess file path in sglang multiturn example README.md
```python
```
> [sglang] fix format issue and data_preprocess file path issue in sglang multiturn example README.md

- examples/grpo_trainer/run_qwen3-8b.sh
Tested successfully on the hiyouga/verl:ngc-th2.6.0-cu126-vllm0.8.4-flashinfer0.2.2-cxx11abi0 image.
It outperforms the Qwen2 7B base model by two percentage points on the test set of GSM8K.
```python
```
- …
> feat: add qwen3 grpo example

- examples/data_preprocess/gsm8k_multiturn_w_tool.py
Fix data preprocess mismatch issue between current main branch and wandb log
> [sglang] Fix data preprocess mismatch in sgl_multiturn example

- requirements.txt
Add 2 pip dependances to install correctly.
> add pip dependances

- README.md
None
Add Seed Paper Explore Data Scale in ReadMe
Add Seed Paper Explore Data Scale in ReadMe
Add Seed Paper Explore Data Scale in ReadMe
None
None
None
> [ReadMe] Add  Seed Paper Explore Paper Data Scale in ReadMe

- docs/examples/config.rst
- docs/perf/perf_tuning.rst
Fix the outdated description of `gpu_memory_utilization`. 
Clarify its definition for different engines( vLLM<v0.7.0, vLLM>=v0.7.0, SGLang)
- **Reference**: 
- for vLLM v0.5.4 and v0.6.3: https://github.com/volcengine/verl/blob/cb1adda924e11583deef8c42b0f43ffea582952a/verl/third_party/vllm/vllm_v_0_5_4/worker.py#L208 and https://github.com/volcengine/verl/blob/cb1adda924e11583deef8c42b0f43ffea582952a/verl/third_party/vllm/vllm_v_0_6_3/worker.py#L205
- for vLLM v0.7.0 and later: https://github.com/vllm-project/vllm/blob/d6484ef3c3a01dc89176ed49874a327303356bee/vllm/worker/worker.py#L247-L257, and https://docs.vllm.ai/en/latest/api/vllm/vllm.config.html#vllm.config.CacheConfig.gpu_memory_utilization
- SGLang: https://github.com/volcengine/verl/blob/6b8706cd4ff01a4b72f5a1aeb28058b296973dab/ve …
> [doc] Clarifying `gpu_memory_utilization` for different engines

- README.md
> Just adding Absolute Zero work to the README as a list of work that used veRL
> just information
> only changed README.md, added Absolute Zero
```python
```
> Add Absolute Zero to awesome work list

- docs/sglang_multiturn/multiturn.rst
Update the docs for Custom Tool Configuration, fixing one broken link and providing more instructions.
N/A
- fix broken link to gsm8k_tool_config.yaml
- update docs about custom tool config
N/A
N/A
N/A
- **Issue Number**: #1511
> [doc] update docs for custom tool config

- README.md
Update README to add Seed-Coder as an example project using verl. 
N/A
Add one line in README about the Seed-Coder project.
N/A
N/A
N/A
N/A
> Add Seed-Coder project in README

- verl/workers/fsdp_workers.py
> fix #1534, sglang_async missing offload_param config

- verl/trainer/ppo/core_algos.py
> Fix reinforce_plus_plus_baseline advantage mask

- .github/workflows/checkpoint_converter.yml
- .github/workflows/dataset.yml
- .github/workflows/e2e_dapo.yml
- .github/workflows/e2e_eval_aime24.yml
- .github/workflows/e2e_ppo_trainer.yml
- .github/workflows/e2e_ppo_trainer_megatron.yml
- .github/workflows/e2e_prime.yml
- .github/workflows/e2e_sft.yml
- .github/workflows/kernels.yml
- .github/workflows/model.yml
- .github/workflows/ray_gpu_test.yml
- .github/workflows/sandbox.yml
- .github/workflows/utils_gpu_test.yml
- docker/Dockerfile.vllm.sglang.megatron
- docs/start/install.rst
- scripts/install_vllm_sglang_mcore.sh
Update to latest vLLM to fully support Qwen3 moe
- vLLM: 0.8.5
- SGLang: 0.4.6post4
- megatron: core_0.12.0rc3
```python
```
- **Training**: Both
- **Inference**: Both
> [Docker Image] use latest vLLM (0.8.5) to fully support Qwen3 moe

- scripts/install_vllm_sglang_mcore.sh
Signed-off-by: Edward Z. Yang <ezyang@meta.com>
Fixes some bash syntax errors in the install script
> Add missing fi to install script

- .github/PULL_REQUEST_TEMPLATE.md
fix a typo 'neccessary' in 'PULL_REQUEST_TEMPLATE.md'
NA
'neccessary' -> 'necessary'
```python
```
> [misc] ci: fix typo in PULL_REQUEST_TEMPLATE.md

- docs/examples/config.rst
- verl/models/mcore/config_converter.py
- verl/models/mcore/model_initializer.py
- verl/single_controller/base/megatron/worker.py
- verl/trainer/config/ppo_megatron_trainer.yaml
- verl/workers/megatron_workers.py
fix mcore qwen3 moe config `moe_router_pre_softmax`, no need for patching now, and offer option to freeze moe router
Moe models initialization:
```py
def initialize(self, **kwargs):
```
```python
moe_router_pre_softmax=False,
```
```yaml
override_config:
moe_config:
freeze_moe_router: False
```
- **Inference**: [Note which backend this PR will affect: vLLM, SGLang, both, …
> [Megatron] Qwen3moe-part3: fix mcore qwen3 moe config, no need for patching now, offer option to freeze moe router

- .github/workflows/sgl.yml
Fix sglang CI, use stable way to download Qwen 7B model
```python
```
> [BugFix] fix sglang CI, use stable way to download Qwen 7B model

- verl/utils/checkpoint/megatron_checkpoint_manager.py
Megatron: fix checkpoint manager, some states only rank 0 need to save to avoid errors
```python
```
> [BugFix] Megatron: fix checkpoint manager, some states only rank 0 need to save to avoid errors

- verl/utils/tracking.py
Support logging to [ClearML](https://clear.ml/) system
> [feat] support logging to ClearML

- verl/workers/sharding_manager/fsdp_sglang.py
Remove unnecessary broadcast
Removed one line
```python
```
```bash
(WorkerDict pid=1099764) Before broadcast: TensorDict(
(WorkerDict pid=1099764)     fields={
(WorkerDict pid=1099764)         attention_mask: Tensor(shape=torch.Size([330, 2048]), device=cuda:0, dtype=torch.int64, is_shared=True),
(WorkerDict pid=1099764)         input_ids: Tensor(shape=torch.Size([330, 2048]), device=cuda:0, dtype=torch.int64, is_shared=True),
(WorkerDict pid=1099764)         position_ids: Tensor(shape=torch.Size([330, 2048]), device=cuda:0, dtype=torch.int64, …
```
> Remove unnecessary broadcast

- .github/workflows/checkpoint_converter.yml
- .github/workflows/dataset.yml
- .github/workflows/e2e_dapo.yml
- .github/workflows/e2e_eval_aime24.yml
- .github/workflows/e2e_ppo_trainer.yml
- .github/workflows/e2e_ppo_trainer_megatron.yml
- .github/workflows/e2e_prime.yml
- .github/workflows/e2e_sft.yml
- .github/workflows/kernels.yml
- .github/workflows/model.yml
- .github/workflows/ray_gpu_test.yml
- .github/workflows/sandbox.yml
- .github/workflows/utils_gpu_test.yml
- docker/Dockerfile.vllm.sglang.megatron
- docs/start/install.rst
- scripts/install_vllm_sglang_mcore.sh
update images and fix sglang installation, the latest image: `whatcanyousee/verl:ngc-cu124-vllm0.8.5-sglang0.4.6-mcore0.12.0-te2.3`
- vLLM: 0.8.5.post1
- SGLang: 0.4.6.post4, fix installation
- Megatron: core_v0.12.0 announcement
- TransformerEngine: 2.3
```python
```
- **Inference**: [Note which backend this PR …
> [Docker Image] update images and fix sglang installation

- verl/workers/sharding_manager/fsdp_sglang.py
Suggested by @BearBiscuit05, we can follow fsdp_vllm to simplify the device mesh and tp rank logic.
```python
```
```
Training Progress:   7%|▋         | 15/210 [25:27<5:27:08, 100.66s/it]
(WorkerDict pid=1408128) update_weights_from_tensor time: 0.8615233898162842 seconds
(WorkerDict pid=1408128) self.sampling_params={'n': 5, 'max_new_tokens': 1024, 'presence_penalty': 0.0, 'frequency_penalty': 0.0, 'repetition_penalty': 1.0, 'temperature': 1.0, 'top_k': -1, 'top_p': 1, 'ignore_eos': False}
(TaskRunner pid=1406018) …
```
> Simplify FSDP SGLang pre and post process

- docs/index.rst
- docs/single_controller.rst
fix the img missing in single controller doc
NA
- add `?raw=true` to img link in single_controller doc
- move the single_controller doc along with hybridflow programming guide in index
```python
```
> [fix] img not displaying on single controller doc

- README.md
> Adding RM-R1 to the README as a list of work that used veRL
> 1-line update
> only changed the readme.md (1-line update)
```python
```
> Add RM-R1 to awesome work list

- docker/Dockerfile.awsefa
- docs/start/install.rst
Add sample dockerfile to support aws efa driver. Otherwise NCCL raise system error on such aws instances (like sagemaker ai pod).
> [New] aws efa driver dockerfile

- recipe/spin/README.md
> [docs] recipe: fix spin README

- .github/workflows/e2e_ppo_trainer.yml
- tests/e2e/run_gsm8k_fsdp_sgl_multiturn_w_tool.sh
Add CI for FSDP2 in SGLang multi-turn tasks. 
- **Issue Number**: https://github.com/zhaochenyang20/Awesome-ML-SYS-Tutorial/issues/131#issue-3058658560
> chore(ci): support FSDP2 for multi-turn SGLangRollout with tool calling

- docs/ascend/ascend_vllm073.rst
modify the instructions for using verl on ASCEND NPU
1、Modify table format
2、Modify the installation method of vllm and vllm-ascend
```python
```
> modify the instructions for using verl on ASCEND NPU

- README.md
> Adding verl-agent and GiGPO to the README as a list of work that used veRL
> 1-line update
> only changed the readme.md (line 217)
> N/A
> N/A
N/A
> Add verl-agent and GiGPO to the awesome work list

- scripts/model_merger.py
Resolve issue #1680 
Modify the variable config_path to hf_model_config_path for correct model saving
> [fix] use correct variable for saving hf model

- .github/workflows/checkpoint_converter.yml
- .github/workflows/kernels.yml
Refactor and reduce some tests scope to reduce unrelated tests.
```python
```
> [CI] fix some tests scope

- docs/examples/config.rst
- docs/faq/faq.rst
Add a visual explanation of the configuration to the documentation
> [Doc] Add a visual explanation of the configuration to the documentation

- verl/workers/megatron_workers.py
Fix freeze_moe_router typo to enable the config option as @duomicoding in #1540 and @vermouth1992  pointed out.
Maybe **freeze** is better than **fix** to describe this function.
```python
```
> [BugFix] fix freeze_moe_router typo to enable the config option

- docker/Dockerfile.vllm.sglang.megatron
hot fix moonlight tokenizer request
```python
```
> [Docker Image] hot fix moonlight tokenizer request

- README.md
> [docs] readme: add lora and move social icons

- verl/trainer/config/sft_trainer.yaml
- verl/trainer/fsdp_sft_trainer.py
Add fsdp2 to fsdp_sft_trainer. Resolve issue #1504.
Refer to the implementation of #1026.
```python
model.strategy=fsdp2
```
- **Issue Number**: #1504 
- **Training**: [Note which backend this PR will affect: FSDP]
> [feat] add fsdp2 to fsdp_sft_trainer

- .github/workflows/e2e_eval_aime24.yml
- recipe/r1/main_eval.py
- Fix the CI problem in main
- Fix the CI problem that e2e_eval_aime24 is not triggered.
```python
```
> [eval] fix: fix main_eval

- docs/amd_tutorial/amd_build_dockerfile_page.rst
- docs/hybrid_flow.rst
- docs/preparation/reward_function.rst
- docs/requirements-docs.txt
- docs/start/install.rst
- docs/start/multinode.rst
- recipe/sppo/sppo_ray_trainer.py
- scripts/install_vllm_sglang_mcore.sh
- verl/workers/rollout/vllm_rollout/fire_vllm_rollout.py
> chore: fix typos across codebase

- verl/workers/megatron_workers.py
- verl/workers/sharding_manager/megatron_vllm.py
Details are in the comments inside the code.
```python
```
> [optimization] feat: move kv cache wakeup after model weights release

- README.md
> Adding LUFFY to the README as a list of work that used veRL
> 1-line update. 
> only changed the readme.md (1-line update).
> No.
```python
```
> Add LUFFY to awesome work list #1608

- recipe/README.md
ProRL is a novel training methodology that incorporates KL divergence control, reference policy resetting, and a diverse suite of tasks. The empirical analysis reveals that RL-trained models consistently outperform base models across a wide range of pass@k evaluations, including scenarios where base models fail entirely regardless of the number of attempts. 
It is developed based on Verl. 
Link: https://arxiv.org/abs/2505.24864
> Add ProRL to README.md

- .github/workflows/e2e_ppo_trainer.yml
- docs/advance/ppo_lora.rst
- tests/e2e/ppo_trainer/run_function_reward.sh
- verl/utils/fsdp_utils.py
- verl/workers/fsdp_workers.py
- verl/workers/sharding_manager/fsdp_vllm.py
1. Add: Add support for FSDP2 in GRPO-LoRa
2. Format: Automatic code formatting changes initiated by the pre-commit tool
3. Add: Integrate the end-to-end (e2e) testing of GRPO-LoRA + fsdp2 into the CI pipeline.
> [feat] Add support for FSDP2 in GRPO-LoRA

- examples/grpo_trainer/run_deepseek671b_math_megatron.sh
- Run on 512 GPUs with TP1PP16EP32, 2k input + 4k output
- Add some tips on memory saving
```python
```
> Make DeepSeek 671B GRPO example more GPU memory friendly

- verl/single_controller/base/decorator.py
ray put all the args in advance to avoid duplicate serialization cost for megatron dispatch.
```python
```
> [single controller] feat: mitigate pickle cost

- verl/utils/flops_counter.py
> [misc] fix: fix flops for H200

- docs/workers/megatron_workers.rst
- verl/models/mcore/readme.md
- verl/third_party/sglang/parallel_state.py
- verl/third_party/vllm/vllm_v_0_5_4/parallel_state.py
- verl/third_party/vllm/vllm_v_0_6_3/parallel_state.py
- verl/workers/rollout/async_server.py
- verl/workers/rollout/hf_rollout.py
- verl/workers/rollout/vllm_rollout/vllm_async_server.py
- verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
- verl/workers/sharding_manager/fsdp_vllm.py
> fix: typos

- README.md
Updated readme for rollout related ppcoming features and changes.
> Add rollout Module Development Progress & Roadmap

- recipe/dapo/dapo_ray_trainer.py
> [misc] fix: fix indent

- tests/sanity/test_config_docs.py
- verl/trainer/config/ppo_trainer.yaml
Force documentation for the trainer yaml file
Added a test to enforce it.
> [trainer] doc: enforce documentation for config fields

- verl/single_controller/base/worker.py
set CUDA and HIP VISIBLE DEVICES to avoid the inconsistent assert. https://github.com/ray-project/ray/pull/53531/files#diff-fd4b20003907a27e8d3f08a397c1dafea67f34239ebf464408ac8353e7bc1a67R46-R50 
https://github.com/volcengine/verl/pull/1465
```python
```
- **Training**: [Note which backend this PR …
> set CUDA and HIP VISIBLE DEVICES

- verl/workers/critic/dp_critic.py
> [worker] fix: do not break dynamic bsz in dp critic

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/e2e_ascend.yml
- tests/sanity/check_pr_title.py
hint PR title in template
```python
```
> [CI] feat: hint PR title in template

- examples/split_placement/config/ppo_trainer_split.yaml
- tests/npu/run_qwen2_5_05b_dapo.sh
- verl/trainer/config/generation.yaml
- verl/trainer/config/ppo_trainer.yaml
- verl/utils/debug/performance.py
- verl/utils/torch_functional.py
- verl/workers/actor/dp_actor.py
- verl/workers/fsdp_workers.py
1. Add fsdp1 forward pefetch configuration.
2. Add chunk entropy computation.
3. Add torch.checkpoint to entropy computation.
4. Move data to device from `ActorRolloutRefWorker.update_actor` to `DataParallelPPOActor.update_policy`.
5. Add `npu_cross_entropy_loss` fusion kernel.
1. More detail see [FSDP forward_pefetch](https://docs.pytorch.org/docs/stable/fsdp.html#module-torch.distributed.fsdp)
2. `logits` usually is a large tensor [bsz\*seq_len, voc], on `compute_entropy_from_logits` will use [bsz\*seq_len, voc] * (4(float32) + 2(autocast of softmax+logsumexp) + 1(output of softmax)) memory. To reduce this memory peak, we can use chunk calculation, changing [bsz*seq_len, voc] to [chunk_size(2048), voc].
3. During the training phase, `enable_gradient_checkpointing=True` is not applicable …
> [FSDP] feat: Add FSDP forward pefetch and recompute chunking entropy

- README.md
> RL-Factory decouples the environment from RL post-training, enabling training with just a tool config and reward function while supporting async tool-calling to make RL post-training 2x faster.
> No changes to existing public APIs. Internal additions only.
```python
bash main_grpo.sh
```
> [doc] feat: Add RL-Factory agentic learning project with verl on README

- docs/start/multinode.rst
[doc] fix: revert previous ray cluster description
```python
```
> [doc] fix: revert previous ray cluster description

- .github/workflows/e2e_ascend.yml
[done] Search for similar PR(s).
Version of vLLM-ascend upgraded to v0.7.3.post1 to support multimodal PRs.
Change .github/workflows/e2e_ascend.yml
[ done ] Read the [Contribute Guide](https://github.com/volcengine/verl?tab=readme-ov-file#contribution-guide).
[ done ] Apply [pre-commit checks](https://github.com/volcengine/verl?tab=readme-ov-file#code-linting-and-formatting).
> [CI] feat: update npu image to vLLM-ascend-v0.7.3.post1

- verl/trainer/ppo/ray_trainer.py
Search for similar PR(s).
All entries are first concatenated into a single large string, then written to the file in one operation
Hardware Overview:
Model Name: MacBook Pro
Model Identifier: MacBookPro15,2
Processor Name: Quad-Core Intel Core i5
Processor Speed: 2.3 GHz
Number of Processors: 1
Total Number of Cores: 4
L2 Cache (per Core): 256 KB
L3 Cache: 6 MB
Hyper-Threading Technology: Enabled
Memory: 16 GB
System Firmware Version: 2022.100.22.0.0 (iBridge: 21.16.4222.0.0,0)
OS Loader Version: 580~1678
Activation Lock Status: Disabled
> [trainer] chore: Reducing the number of calls to the write

- docs/algo/dapo.md
- recipe/dapo/README.md
- recipe/dapo/runtime_env.yaml
- type is in `feat, fix, refactor, chore, test`
This PR fixes the broken link for DAPO branch and add some details to the doc.
> [doc] fix: DAPO branch & doc

- verl/trainer/config/ppo_trainer.yaml
- verl/utils/distributed.py
- verl/workers/fsdp_workers.py
- verl/workers/megatron_workers.py
Allow torch.distributed.init_process_group to fetch "DIST_INIT_METHOD" from os.environ to accelerate single node initialization.
Before using shared file-system initialization
After export …
> [worker] feat: allow dist shared file-system initialization

- verl/utils/flops_counter.py
Add missing qwen2_moe flops counter, shall be the same as original qwen3-moe counter.
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by experiment(s) …
> [trainer] fix: add missing qwen2_moe flops counter

- verl/models/transformers/monkey_patch.py
Fixes #2213
> For changes that can not be tested by CI (e.g., …
> [model] fix: make vlm patch forward compatible

- examples/grpo_trainer/run_minicpmo2_6.sh
- recipe/minicpmo/rl_dataset.py
- verl/utils/dataset/rl_dataset.py
- verl/utils/dataset/vision_utils.py
- verl/workers/actor/dp_actor.py
- verl/workers/fsdp_workers.py
This PR moves the data process code of minicpm-o to recipes to avoid breaking the current function
Fixes #2178
- Example: …
> [model] fix: separate minicpmo data

- requirements.txt
- verl/models/transformers/monkey_patch.py
Transformers 4.53 does not work with the current vLLM for Qwen2-VL models: https://github.com/vllm-project/vllm/issues/19833#issuecomment-3011175952
- If this PR breaks any API (CLI arguments, config, function signature, etc.), add `[BREAKING]` to the …
> [misc] chore: pin transformers under 4.53

- examples/split_placement/split_monkey_patch.py
> [trainer] fix: fix split placement

- tests/experimental/agent_loop/agent_utils.py
- tests/workers/rollout/perf/vllm_async_rollout.py
- verl/workers/fsdp_workers.py
- verl/workers/megatron_workers.py
- verl/workers/rollout/vllm_rollout/vllm_async_server.py
- verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
> [rollout] feat: add zeromq vllm distributed executor

- verl/workers/megatron_workers.py
Log memory footprints in wandb during running like FSDP does. …
> [megatron] feat: add megatron memory log

- docs/index.rst
- docs/start/more_resources.rst
Add some resources about verl to the documentation.
> [!IMPORTANT]
> [doc] feat: more resources

- docs/ascend_tutorial/ascend_quick_start.rst
- requirements-npu.txt
Flash Attention2 in `transformers==4.53.0` is not work on Ascend NPU due to [PR line here](https://github.com/huggingface/transformers/blob/3457e8e73e4f5532cc69059682b1ba4484d7e7e8/src/transformers/modeling_flash_attention_utils.py#L109C5-L109C23) in `transformers`.
In order to not affect `e2e_ascend` CI, we have to set `transformers==4.52.4` for Ascend NPU situation by force now.
Corresponding bugfix in `transformers` will be conducted as soon as possible, after newer transformers version containing bugfix released, we will update the transformers version dependency in verl again.
- `{modules}` include `fsdp`, `megatron`, `sglang`, `vllm`, `rollout`, `trainer`, `ci`, `training_utils`, `recipe`, `hardware`, `deployment`, `ray`, `worker`, `single_controller`, `misc`, `perf`, `model`, …
> [ci, doc] fix: fix transformers version dependency on Ascend NPU

- docs/ascend_tutorial/ascend_quick_start.rst
> [doc] fix: Update ascend_quick_start.rst

- recipe/genrm_remote/README.md
- recipe/genrm_remote/run_genrm_remote.sh
- tests/special_e2e/run_genrm_remote.sh
The CI test remote GenRM uses a private model `dyyyyyyyy/Qwen2.5-1.5B-GenRM-QueryOnly`.
For the stability of the CI, this model has been uploaded to the official HF repository, i.e., `verl-team/GenRM-CI-Test-1.5B`, and the model invocation in the CI test has been updated accordingly.
- If this PR breaks any API (CLI arguments, config, function signature, etc.), add `[BREAKING]` to the beginning …
> [CI] fix: replace private model in CI test

- .gemini/config.yaml
add gemini code assistant config. The example code reviews are in https://github.com/eric-haibin-lin/verl/pull/17#pullrequestreview-2977403886. The threshold is set to high to avoid too many review comments.  …
> [ci] chore: add gemini code assistant config

- tests/trainer/ppo/test_core_algos_on_cpu.py
- verl/experimental/agent_loop/tool_agent_loop.py
- verl/trainer/ppo/core_algos.py
- verl/trainer/ppo/ray_trainer.py
- verl/utils/import_utils.py
- verl/workers/rollout/chat_scheduler.py
Mask out observation tokens in GAE for multi turn training. …
> [algo] feat: mask out observation token in GAE

- recipe/retool/retool.py
- verl/tools/sandbox_fusion_tools.py
result.strip() may raise exception when it is None. Fixed by return None for metrics and score, because they are not available yet for code sandbox.
> For changes that can not be tested by CI (e.g., …
> [tool] fix: avoid exception when sandbox return None

- verl/trainer/config/ppo_trainer.yaml
- verl/trainer/ppo/ray_trainer.py
This PR addresses the "ESI" comprehension issue left by the previous PR (https://github.com/volcengine/verl/pull/2192).
This PR refines `ppo_trainer.yaml` by expanding the esi_redundant_time comment to define ESI (Elastic Server Instance) and draw a parallel to a training plan. In `ray_trainer.py`, it clarifies ESI-related checkpoint-saving conditions. These edits boost code readability and maintainability.
- `{modules}` include `fsdp`, `megatron`, `sglang`, `vllm`, `rollout`, `trainer`, `ci`, `training_utils`, `recipe`, `hardware`, `deployment`, `ray`, `worker`, `single_controller`, `misc`, `perf`, `model`, `algo`, `env`, `tool`, `ckpt`, `doc`, …
> [ckpt] fix: edit esi doc

- verl/utils/dataset/rl_dataset.py
```log
verl/utils/dataset/rl_dataset.py:38: SyntaxWarning: invalid escape sequence '\*'
```
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by …
> [misc] fix: invalid escape sequence '\*'

- docs/examples/config.rst
- examples/ppo_trainer/README.md
> Fix document config.rst: the parameter“gemma” -> “gamma”. …
> [doc] fix: Fix document config.rst

- .github/workflows/README.md
- .github/workflows/e2e_eval_aime24.yml
- .github/workflows/e2e_ppo_trainer_megatron_sglang.yml
- .github/workflows/e2e_ppo_trainer_megatron_vllm.yml
- .github/workflows/e2e_sft.yml
In https://github.com/volcengine/verl/pull/1979, this PR migrates CI tasks to the vemlp. However, the early version's setup and cleanup steps exposed too much procedural code, which we have encapsulated in https://github.com/volcengine/vemlp-github-runner. For specific usage, refer to the documentation in `.github/workflows/README.md`of this pr.
- If this PR breaks any API (CLI arguments, …
> [ci] feat: use action

- docs/sglang_multiturn/multiturn.rst
- examples/sglang_multiturn/config/tool_config/mcp_tool_config.yaml
> This PR add a MCP usage documentation in `sglang_multiturn/multiturn.rst`
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by experiment(s) and show …
> [tool] fix: Add MCP usage documentation

- docs/examples/config.rst
- verl/trainer/config/data/legacy_data.yaml
- verl/utils/torch_functional.py
RLHF dataset has gotten a middle option of truncation without annotation and this option is not mentioned in the docs (See PR #1488 ). The annotations are added in this pull request.
- If this PR breaks any API (CLI arguments, config, function signature, …
> [doc] chore: add documentation for truncation: middle option

- docker/verl0.4-cu124-torch2.6-fa2.7.4/Dockerfile.app.sglang.vllm.mcore0.12.deepep
- docker/verl0.4-cu124-torch2.6-fa2.7.4/Dockerfile.app.vllm.mcore0.12.deepep
- docker/verl0.4-cu124-torch2.6-fa2.7.4/Dockerfile.app.vllm.mcore0.13.preview
- docker/verl0.4-cu124-torch2.6-fa2.7.4/README.md
- docker/verl0.5-cu126-torch2.7.1-fa2.8.0/Dockerfile.app.sglang.mcore0.12
- docker/verl0.5-cu126-torch2.7.1-fa2.8.0/Dockerfile.app.sglang.mcore0.13.preview
- docker/verl0.5-cu126-torch2.7.1-fa2.8.0/Dockerfile.base
- docker/verl0.5-cu126-torch2.7.1-fa2.8.0/README.md
- docs/start/install.rst
Provide images with deep-ep.
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by experiment(s) and show results like training curve plots, evaluation …
> [docker] feat: provide images with deepep

- verl/utils/tracking.py
Enhance the model output logging section in the `log_generations_to_swanlab` function to improve visualization.
demo link: https://swanlab.cn/@ZeyiLin/verl_examples/runs/e9hgu4yx78ra74bh1346v/chart#YWh6djBw-MloyeE8ybkk=
- Example: `[BREAKING][fsdp, megatron] feat: …
> [training_utils] feat: log_generations_to_swanlab use table

- verl/workers/rollout/sglang_rollout/sglang_rollout.py
>  We should call `flush_cache` in the same way it's done in the `_req_level_generate_sequences` function; otherwise, it will cause an error when TP16 is enabled. …
> [sglang] fix: Only flush cache on TP rank=0.

- docs/examples/ppo_code_architecture.rst
- examples/split_placement/main_ppo_split.py
- recipe/dapo/main_dapo.py
- recipe/entropy/main_entropy.py
- recipe/prime/main_prime.py
- recipe/spin/main_spin.py
- recipe/spin/spin_trainer.py
- recipe/sppo/main_sppo.py
- verl/trainer/ppo/ray_trainer.py
Allow FSDP2 when doing strategy check
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by experiment(s) and show results like training curve plots, …
> [trainer] fix: Allow FSDP2 when doing strategy check

- recipe/dapo/main_dapo.py
- verl/workers/reward_manager/dapo.py
Fix some bugs/outdated code so that we can use sandbox fusion for DAPO.
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by experiment(s) and show …
> [recipe] fix: DAPO rewards using sandbox fusion

- verl/trainer/config/_generated_ppo_trainer.yaml
- Run scripts/generate_trainer_config.sh to update auto-generated config
- Adds missing trace configuration fields (backend, token2text)
- Fixes pre-commit hook failure
> For changes that can not be tested …
> [cfg] fix: fix _generated_ppo_trainer.yaml pre-commit error on main

- verl/single_controller/base/worker.py
Strip square brackets of ipv6 address `[::1]`, torch `MASTER_ADDRESS` doesn't need it.
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by …
> [ray] fix: strip [] for ipv6 address

- examples/sglang_multiturn/geo3k/run_qwen2.5-3b_geo3k_multiturn.sh
- examples/sglang_multiturn/geo3k/run_qwen2.5-3b_geo3k_multiturn_4xgpu.sh
- examples/sglang_multiturn/geo3k/run_qwen2.5-3b_megatron_geo3k_multiturn.sh
Fix geo3k script `model_name` from non vl model to vl model …
> [fsdp] fix: change geo3k model name from non-vl to vl

- .github/CODEOWNERS
add single-controller reviewer so changes are automatically notified. 
cc @hongpeng-guo
> [ci] chore: add single-controller reviewer

- verl/utils/reward_score/gsm8k.py
Huapeng: For regular expression matching, sometimes it cost too long for reward calculation, so clip the last 300 chars to speed up.
Similar code(DAPO): https://github.com/BytedTsinghua-SIA/DAPO/blob/main/eval/math_dapo.py#L278
> [!IMPORTANT]
> [perf] feat: Clip gsm8k solution string to optimize reward calculation

- docs/advance/agent_loop.rst
- docs/index.rst
- docs/start/agentic_rl.rst
- verl/experimental/agent_loop/agent_loop.py
- verl/workers/rollout/async_server.py
> [doc] chore: add agent loop design doc

- tests/utils/test_flops_counter.py
- verl/utils/flops_counter.py
Add mistral and gemma3_text mfu compute support
> [perf] feat: mistral and gemma3_text mfu compute support

- docs/examples/config.rst
- examples/gpg_trainer/run_qwen2-7b_math_megatron.sh
- examples/grpo_trainer/run_moonlight16b_math_megatron.sh
- examples/grpo_trainer/run_qwen2-7b_math_megatron.sh
- examples/grpo_trainer/run_qwen2-7b_seq_balance_math_megatron.sh
- examples/grpo_trainer/run_qwen2-7b_sgl_megatron.sh
- examples/grpo_trainer/run_qwen2_5-7b_math_megatron_diff_tp.sh
- examples/grpo_trainer/run_qwen3-236b_megatron.sh
- examples/grpo_trainer/run_qwen3moe-30b_megatron.sh
- examples/ppo_trainer/run_deepseek_math_gsm8k_megatron.sh
- examples/ppo_trainer/run_deepseek_math_gsm8k_megatron_nsys.sh
- examples/ppo_trainer/run_moonlight16b_a3b_gsm8k_megatron.sh
- examples/sglang_multiturn/run_qwen2.5-3b_megatron_gsm8k_multiturn.sh
- recipe/dapo/test_dapo_7b_math_megatron.sh
- recipe/dapo/test_dapo_dspk_671b_megatron.sh
- recipe/one_step_off_policy/dapo_7b_math_megatron_4_12.sh
- recipe/one_step_off_policy/dapo_7b_math_megatron_colocate.sh
- tests/special_e2e/run_ppo_trainer_megatron.sh
- verl/trainer/config/_generated_ppo_megatron_trainer.yaml
- verl/trainer/config/_generated_ppo_trainer.yaml
- verl/trainer/config/actor/megatron_actor.yaml
- verl/trainer/config/critic/critic.yaml
- verl/trainer/config/critic/dp_critic.yaml
- verl/trainer/config/critic/megatron_critic.yaml
- verl/trainer/config/ppo_megatron_trainer.yaml
- verl/trainer/config/reward_model/megatron_reward_model.yaml
Since we directly offer `override_transformer_config` option, we directly use it to recompute activations. Default settings are the same with `megatron.training`. …
> [BREAKING][megatron] refactor: activation checkpointing APIs

- examples/grpo_trainer/run_deepseek7b_llm_math_megatron.sh
- examples/ppo_trainer/run_qwen2-7b_math_gsm8k_megatron.sh
- examples/sglang_multiturn/geo3k/run_qwen2.5-3b_megatron_geo3k_multiturn.sh
- examples/tuning/32b/qwen2_32B_grpo_8_h20_megatron_vllm.sh
- recipe/one_step_off_policy/dapo_7b_math_fsdp2_4_12.sh
They were removed in https://github.com/volcengine/verl/pull/2651 ... 
@ETOgaosion 
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by experiment(s) …
> [megatron] fix: remove the demising model.enable_gradient_checkpointing flags in the script

- verl/utils/checkpoint/fsdp_checkpoint_manager.py
Wrapping `GenerationConfig.from_pretrained` in a try-except block to prevent crashes during checkpoint saving.
[Issue](https://github.com/volcengine/verl/issues/2658)
- If this PR breaks any API (CLI arguments, config, function signature, etc.), add …
> [fsdp, ckpt] fix: Wrap `GenerationConfig.from_pretrained` with try-except to avoid crashes.

- verl/trainer/ppo/ray_trainer.py
- verl/workers/sharding_manager/fsdp_sglang.py
- verl/workers/sharding_manager/megatron_sglang.py
**Speed up QWen3 MOE update weights from 110s to 37s**
Related to : https://github.com/sgl-project/sglang/pull/8267
Co-authored-by: CuiBo <82354186+SuperCB@users.noreply.github.com>
Co-authored-by: GeLee <865038696@qq.com>
- If this PR breaks any API (CLI …
> [fsdp,megatron,sglang] fix: Fix torch reduce to speed up update weights

- verl/trainer/ppo/ray_trainer.py
- verl/utils/tracking.py
align tensorboard default dir for val_log_generation
> [training_utils] fix: align tensorboard default dir for val_log_generation

- .github/PULL_REQUEST_TEMPLATE.md
Add CI request via Feishu.
n/a
n/a
n/a
> [ci] feat: CI request via Feishu

- verl/workers/rollout/sglang_rollout/sglang_rollout.py
> [sglang] fix: fix is_vlm issue (issue #2639)

- verl/tools/geo3k_tool.py
change tool.create return from `instance_id, None` to `instance_id`
> [!IMPORTANT]
> Please check all the following items before requesting a review, otherwise the reviewer might deprioritize this PR for …
> [tool] fix: geo3k create return

- docs/_static/custom.css
- docs/_static/js/resizable-sidebar.js
- docs/conf.py
This PR adds a resizable sidebar feature and improves the documentation layout for better user experience.
- **Resizable sidebar**: Users can drag to resize the sidebar, with preference saved in localStorage
- **Full-width layout**: Documentation now uses full screen width for better readability
- **Responsive design**: Better layout adaptation for different screen sizes
- **Navigation improvements**: Attempts to improve table of contents navigation behavior
- Drag handle on sidebar for resizing
- Double-click to reset sidebar to default width
- localStorage persistence for user preferences
- Improved CSS for better visual experience
- Added `_static/custom.css` for styling improvements
- Added `_static/js/resizable-sidebar.js` for functionality
- Updated `conf.py` to include new CSS and …
> [doc] feat: add resizable sidebar and improve layout

- verl/trainer/ppo/ray_trainer.py
Some codes in the `ppo/ray_trainer.py` fails static type checking (i.e. `invalid type hints` or `function call with nullable variables`).
This PR fixes these issues to keep the static type checkers of IDE to track the code syntax properly.
> [!IMPORTANT]
> refactor: Make sure to keep the type checking

- README.md
- recipe/README.md
> [doc] feat: add retool blog

- examples/split_placement/config/ppo_trainer_split.yaml
- examples/split_placement/split_monkey_patch.py
- verl/workers/critic/dp_critic.py
When I ran split ppo according to readme, I encountered the following issues:
1. In 'ppo_trainer_split': could not load 'ppo_trainer'
2. KeyError: 'key "response_mask" not found in TensorDict with keys'
3. AttributeError: 'NoneType' object has no attribute 'get'
To fix these issues, I made the following modifications.
- If this PR breaks any API (CLI arguments, config, function signature, …
> [recipe] fix: fix issue when running split ppo

- verl/tools/base_tool.py
- verl/tools/geo3k_tool.py
- verl/tools/gsm8k_tool.py
- verl/tools/sandbox_fusion_tools.py
Fixes a typo in the docstring of some tools. `to_openai_function_tool_schema()` does not exist.
N/A
N/A
N/A
> [!IMPORTANT]
> Please check all the following items before requesting a review, otherwise the …
> [tool] fix: Typo fix -- Rename `to_openai_function_tool_schema` to `get_openai_tool_schema`

- verl/workers/fsdp_workers.py
- verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
This is an naive solution for [issue 2781](https://github.com/volcengine/verl/issues/2781). While it is not an elegant implementation, it works fine for me.
> Why use `getpass.getuser()` instead of `os.getlogin()`? 
>  The latter causes errors while running by ray actor/task. [Here is an related issue](https://github.com/python/cpython/issues/84998).
- If this PR breaks any API (CLI arguments, …
> [vllm,rollout] fix: vllm rollout lock file permission

- .github/workflows/e2e_ascend.yml
[done] Search for similar PR(s).
Change .github/workflows/e2e_ascend.yml
[ done ] Read the [Contribute Guide](https://github.com/volcengine/verl?tab=readme-ov-file#contribution-guide).
[ done ] Apply [pre-commit checks](https://github.com/volcengine/verl?tab=readme-ov-file#code-linting-and-formatting).
> [CI] feat: update npu image to vLLM-ascend-v0.7.3.post1+mindspeed0.12.1

- recipe/dapo/test_dapo_dspk_671b_megatron.sh
> [recipe] feat: modify dapo deepseek megatron script

- examples/ppo_trainer/run_deepseek_full_hh_rlhf.sh
- examples/ppo_trainer/run_qwen1.5_moe_a2.7b-gsm8k_megatron.sh
They were removed in #2651, but #2691 overlooked some of them. …
> [megatron] fix: remove the demising critic.model.enable_gradient_checkpointing flags in the scripts

- verl/trainer/config/_generated_ppo_trainer.yaml
- verl/trainer/config/ppo_trainer.yaml
- verl/workers/fsdp_workers.py
add nccl timeout config for fsdp backend
> [misc] feat: add nccl timeout configuration to fsdp workers

- verl/trainer/ppo/ray_trainer.py
Removed a deprecated parameter comment
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by experiment(s) and show results like training curve plots, …
> [doc] fix: multi turn argument is not available

- docs/sglang_multiturn/multiturn.rst
- tests/experimental/agent_loop/test_basic_agent_loop.py
- tests/workers/rollout/test_sglang_async_rollout_mcp_tools.py
- tests/workers/rollout/test_sglang_async_rollout_multimodal_delta.py
- tests/workers/rollout/test_sglang_async_rollout_search_tools.py
- tests/workers/rollout/test_sglang_async_rollout_sf_tools.py
- verl/experimental/agent_loop/tool_agent_loop.py
- verl/tools/base_tool.py
- verl/tools/geo3k_tool.py
- verl/tools/gsm8k_tool.py
- verl/tools/mcp_base_tool.py
- verl/tools/sandbox_fusion_tools.py
- verl/tools/schemas.py
- verl/tools/search_tool.py
- verl/workers/rollout/schemas.py
- verl/workers/rollout/sglang_rollout/sglang_rollout.py
Support taking tool creation result. Although currently no tool creates env itself, this PR is mainly making tool creation more general where tool itself can return the env/instruction/feedback from creation. …
> [tool, sglang] feat: add tool create info

- .github/workflows/type-coverage-check.yml
CI: retry type check on cpu
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by experiment(s) and show results like training curve plots, evaluation …
> [ci] fix: retry type check on cpu

- docs/start/quickstart.rst
Update the quickstart script to include `actor_rollout_ref.rollout.name`.
Otherwise the following error will be shown:
```
(TaskRunner pid=...) omegaconf.errors.MissingMandatoryValue: Missing mandatory value: actor_rollout_ref.rollout.name
(TaskRunner pid=...)     full_key: actor_rollout_ref.rollout.name
(TaskRunner pid=...)     object_type=dict
```
- If this PR breaks any API (CLI arguments, …
> [doc] fix: Specify rollout engine in quickstart.rst

- verl/utils/flops_counter.py
- verl/utils/megatron_utils.py
- verl/workers/megatron_workers.py
[megatron] refactor: simplify module init in megatron_workers, absorb common operations
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by …
> [megatron] refactor: simplify module init in megatron_workers, extract common operations

- docs/preparation/prepare_data.rst
I fixed the typo from RewardModule to RewardModel in docs/preparation/prepare_data.rst
- Example: `[BREAKING][fsdp, megatron] …
> [doc] fix: fix typo in docs/preparation/prepare_data.rst

- docs/perf/perf_tuning.rst
- tests/trainer/config/legacy_ppo_megatron_trainer.yaml
- tests/trainer/config/legacy_ppo_trainer.yaml
- verl/trainer/config/_generated_ppo_megatron_trainer.yaml
- verl/trainer/config/_generated_ppo_trainer.yaml
- verl/trainer/config/rollout/rollout.yaml
- verl/workers/rollout/vllm_rollout/vllm_async_server.py
- verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
1. enable vllm cuda graph in default
2. add a `cudagraph_capture_sizes` option to customize cuda graph memory
vllm cuda graph can improve performance in every case I have tested. It is better to enable in default as sglang.
The default cudagraph_capture_sizes has best performance, but also come with larger memory occuption.
If oom occurred during update policy, `cudagraph_capture_sizes ` option can help to reduce memory.
Additional memory\latency\batch size testing data from NV:
- If this PR involves multiple modules, separate them with `,` …
> [rollout] feat: add cudagraph_capture_sizes option to customize cuda graph memory

- docker/Dockerfile.ngc.vllm
- docker/Dockerfile.ngc.vllm0.8
- docker/Dockerfile.ngc.vllm0.8.sagemaker
- requirements.txt
- scripts/install_vllm_sglang_mcore.sh
- setup.py
> This PR adds tensorboard as a dependency to requirements.txt file, across several Dockerfiles (Dockerfile.ngc.vllm, Dockerfile.ngc.vllm0.8, Dockerfile.ngc.vllm0.8.sagemaker), a setup script (install_vllm_sglang_mcore.sh), and the main setup.py file. This change ensures that the tensorboard package is consistently installed, enabling visualization of training metrics for various configurations and deployment environments. This is a maintenance task that enhances the project's observability without altering core functionality.
> This change is a dependency update and doesn't require specific testing beyond confirming the installation is successful.
> No API changes are introduced. The usage of TensorBoard would be initiated by the user after installing the requirements.
```python
> [misc] feat: Added: "tensorboard" to the requirements.txt

- README.md
> [doc] feat: update contact and news

- recipe/minicpmo/rl_dataset.py
- tests/trainer/config/legacy_ppo_trainer.yaml
- verl/experimental/agent_loop/single_turn_agent_loop.py
- verl/experimental/agent_loop/tool_agent_loop.py
- verl/trainer/config/_generated_ppo_megatron_trainer.yaml
- verl/trainer/config/_generated_ppo_trainer.yaml
- verl/trainer/config/data/legacy_data.yaml
- verl/trainer/config/sft_trainer.yaml
- verl/trainer/main_generation.py
- verl/utils/dataset/multiturn_sft_dataset.py
- verl/utils/dataset/rl_dataset.py
- verl/utils/dataset/sft_dataset.py
Now we support specifying apply_chat_template_kwargs from config
> …
> [trainer] feat: Specify apply_chat_template_kwargs from config

- verl/workers/megatron_workers.py
Reduce peak memory usage during update_actor/critic by moving data to the device only in mini batch.
Same operation can be seen in [fsdp_workers.py](https://github.com/volcengine/verl/blob/main/verl/workers/fsdp_workers.py#L729)
- Example: `[BREAKING][fsdp, megatron] …
> [trainer] fix: reduce memory footprint by moving data to the device only in mini batch

- tests/special_sanity/check_api_docs.py
> [ci] fix: add `flash_attn_supports_top_left_mask` to ignore list

- docs/examples/config.rst
- verl/utils/tracking.py
Support Trackio, a lightweight experiment tracking library from Hugging Face.
Features are listed in https://huggingface.co/blog/trackio …
> [misc] feat: Support trackio

- verl/utils/profiler/performance.py
- verl/workers/fsdp_workers.py
- verl/workers/megatron_workers.py
[perf] feat: Add rollout longtail observation metrics, show max and min rollout timing and top 10% rollout take-up ratio. …
> [perf] feat: Add rollout longtail observation metrics

- verl/experimental/agent_loop/agent_loop.py
This adds (soft) node affinity such that AgentLoopWorkers get scheduled in the same node if possible.
- Example: …
> [rollout] fix: Add soft node affinity to the agent loop workers

- .github/workflows/vllm.yml
- tests/experimental/agent_loop/test_basic_agent_loop.py
- tests/experimental/agent_loop/test_multi_modal.py
- verl/experimental/agent_loop/agent_loop.py
- verl/workers/rollout/vllm_rollout/vllm_async_server.py
Follow https://github.com/volcengine/verl/pull/2398, support vLLM multi-modal.
> [rollout,vllm] feat: support multi-modal in agent loop

- verl/workers/actor/megatron_actor.py
- verl/workers/critic/megatron_critic.py
Modified data loading logic to transfer only micro-batches to GPU memory during training instead of the entire batch for saving memory for megatron backend. Like the pr https://github.com/volcengine/verl/commit/12c83e8ada17baa0e963faad32252ba591ea099e https://github.com/volcengine/verl/pull/2908, and https://github.com/volcengine/verl/pull/3094
> [trainer] fix: only load memory in micro batch for megatron backend

- .github/workflows/e2e_ppo_trainer_megatron_vllm.yml
- verl/utils/checkpoint/megatron_checkpoint_manager.py
Currently mbridge will not save optimizers. Fix mbridge save and load path. Add CI test.
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by …
> [megatron] fix: mbridge save/load

- examples/split_placement/split_monkey_patch.py
- recipe/dapo/dapo_ray_trainer.py
- recipe/one_step_off_policy/ray_trainer.py
> [recipe] fix: make compute of `step` consistent across all trainers

- .github/workflows/model.yml
[ci] fix: model tests, transformers 4.55 has troubles with backward
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by experiment(s) and show results …
> [ci] fix: model tests, transformers 4.55 has troubles with backward

- verl/workers/actor/megatron_actor.py
- fix megatron micro_batch_size assertion. When using `use_dynamic_bsz`, we don't need to set `micro_batch_size` …
> [megatron] fix: fix megatron micro_batch_size assertion

- verl/experimental/agent_loop/agent_loop.py
Fix #3137. Take into consideration the ray nodes set to `num_cpus=0`. …
> [rollout] fix: KeyError "CPU" init agent loop workers

- recipe/langgraph_agent/chat_model.py
- recipe/langgraph_agent/test_react_agent_loop.py
- tests/experimental/agent_loop/test_basic_agent_loop.py
- verl/experimental/agent_loop/agent_loop.py
- verl/experimental/agent_loop/single_turn_agent_loop.py
- verl/experimental/agent_loop/tool_agent_loop.py
- verl/workers/rollout/async_server.py
- verl/workers/rollout/sglang_rollout/async_sglang_server.py
- verl/workers/rollout/sglang_rollout/sglang_rollout.py
- verl/workers/rollout/vllm_rollout/vllm_async_server.py
Add response token logprobs in agent loop output
> [rollout] feat: add response token logprobs in agent loop output

- verl/models/mcore/config_converter.py
- verl/workers/actor/megatron_actor.py
- Make megatron related print only print on rank zero
- Remove unused code in megatron actor
- Modularize megatron loss computation so that it can be used for SFT as well
> For changes that can not be tested …
> [megatron] refactor: refactor MegatronPPOActor

- verl/utils/__init__.py
[ci] fix: fix type convergence check
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by experiment(s) and show results like training curve plots, …
> [ci] fix: fix type convergence check

- verl/workers/config/rollout.py
- This PR adds the parameter `limit_images` in RolloutConfig. Users can specify the image limit in vllm by setting  `+actor_rollout_ref.rollout.limit_images=xxx` …
> [rollout] fix: Restore the parameter 'limit_images' in RolloutConfig

- examples/grpo_trainer/run_gptoss_20b.sh
Adding a script to run gpt-oss 20B model with VeRL. 
> For changes …
> add gptoss grpo example script

- docker/Dockerfile.rocm
- docker/Dockerfile.rocm_verl-0.4.1
- docs/amd_tutorial/amd_build_dockerfile_page.rst
> Update the resource in `Dockerfile.rocm`
> docker build -f Dockerfile.rocm -t verl-rocm:local .
```
docker run --rm -it verl-rocm:local python -c "import torch; print('ok')"
```
> Update the resource in …
> [hardware] fix: update source in dockerfile.rocm

- README.md
> [doc] fix: add rStar2-Agent as work using verl

- README.md
Update README.md, add related works.
> [doc]Update README.md, add related works

- docs/examples/skypilot_examples.rst
> [doc] fix: Update skypilot_examples.rst

- docs/examples/skypilot_examples.rst
fixes typo in the ssh command in `skypilot_examples.rst` …
>   [doc] fix: fix typo in skypilot_examples.rst 

- recipe/one_step_off_policy/README.md
Updates the readme for the one-step off-policy async trainer with the original reference paper
I introduced async RL training for LLMs in my paper https://arxiv.org/abs/2410.18252. My method is exactly the one step off-policy async replicated here and was on arxiv 7 months before AReal and published at ICLR. AReal's method is different (fully async replay buffer) but it includes a nice graphic of my setup!
Love to see you're getting similar speedups to my results and this is a great recipe!
Figure 2 from my paper
- If this PR involves multiple …
> [doc] fix: edit one step off policy readme with original work

- verl/trainer/config/_generated_ppo_megatron_trainer.yaml
- verl/trainer/config/_generated_ppo_trainer.yaml
- verl/trainer/config/ppo_megatron_trainer.yaml
- verl/trainer/config/ppo_trainer.yaml
- verl/workers/config/rollout.py
- verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
Added enable_prefix_caching to the RolloutConfig. This feature provides no significant performance benefit in short-input-long-output scenarios (e.g., 2k input to 34k output) and occupies a certain amount of device memory.
- Example: `[BREAKING][fsdp, megatron] feat: …
> [rollout] chore: Add enable_prefix_caching into config

- recipe/one_step_off_policy/ray_trainer.py
- recipe/spin/spin_trainer.py
- recipe/sppo/sppo_ray_trainer.py
PR https://github.com/volcengine/verl/pull/2353 forgot to update all `_dump_generations` in recipe codes
- Example: …
> [recipe] fix: Add gts argument for recipe _dump_generations

- .github/workflows/.deprecate/e2e_ppo_trainer.yml
- docs/algo/spin.md
- docs/amd_tutorial/amd_build_dockerfile_page.rst
- docs/ascend_tutorial/ascend_quick_start.rst
- docs/examples/gsm8k_example.rst
- docs/start/multinode.rst
- docs/start/quickstart.rst
- examples/data_preprocess/gsm8k.py
- examples/data_preprocess/gsm8k_multiturn_w_interaction.py
- examples/data_preprocess/gsm8k_multiturn_w_tool.py
- examples/data_preprocess/gsm8k_tool_agent_loop.py
- examples/ppo_trainer/run_qwen2-7b_rm.sh
- recipe/gspo/test_gspo_3b_math.sh
- recipe/gspo/test_gspo_3b_math_slurm.sh
- recipe/spin/README.md
- recipe/sppo/run_qwen2.5-7b_rm.sh
Support the local GSM8K dataset preprocessing
Local loading: It's designed for network environments where huggingface downloads are unavailable
Paramenter renaming: This is to help distinguish between the original path of the raw dataset (local_dataset_path) and the save directory of the processed dataset(local_dir->local_save_dir)
- If this PR involves multiple modules, separate them with `,` like …
> [tool] feat: support local gsm8k dataset in example/data_preprocess

- README.md
> [doc] feat: add SimpleVLA-RL link in readme

- .github/CODEOWNERS
add codeowner in npu folder
/recipe/dapo and /examples/grpo_trainer: model scripts of npu
/verl/models/transformers: npu_patch for transformers …
> [ci] chore: add codeowner

- verl/single_controller/base/decorator.py
For a data size of 6400x20480, the time of `ray.put` was reduced from 28.85s to 19.86s following this optimization, resulting in a ~45% improvement.
> For changes that can not be tested by CI (e.g., …
> [ray, single_controller] refactor: Accelerate ray.put with thread

- .github/CODEOWNERS
Update owners for ascend_tutorial documents
Not related.
Not related.
Not related.
> [!IMPORTANT]
> Please check all the following items before requesting a review, otherwise the reviewer might deprioritize …
> [doc] chore: Update owners for ascend_tutorial documents

- recipe/spin/main_spin.py
> [recipe] fix: Fix main_spin.py bugs

- .github/workflows/sgl.yml
- .github/workflows/vllm.yml
> [ci] feat: update ci

- recipe/spin/fsdp_workers.py
Fix TypeError: cannot unpack non-iterable NoneType object
> For …
> [recipe] fix: spin fsdp_workers.py bugs

- docker/Dockerfile.rocm7
Dockerfile for rocm7.0
- [x ] Search for similar PRs. Paste at least one query link here: ...
```bash
DOCKER_BUILDKIT=1 docker build -f Dockerfile.rocm -t verl-rocm7.0 .
```
> [docker] feat: dockerfile rocm7 initial commit

- docker/Dockerfile.rocm7
Dockerfile for rocm7.0 for 0.5.x release
- [ x] Search for similar PRs. Paste at least one query link here: ...
```bash
DOCKER_BUILDKIT=1 docker build -f Dockerfile.rocm -t verl-0.5.0_rocm7.0 .
```
> dockerfile for rocm7

- .github/CODEOWNERS
> [misc] chore: Update CODEOWNERS

- verl/experimental/agent_loop/tool_agent_loop.py
> The `_handle_processing_tools_state` added the same tool response twice when using interactions. See [here](https://github.com/volcengine/verl/blob/ba8555120af6a1f8dba8f09e60e4663ac5176efc/verl/experimental/agent_loop/tool_agent_loop.py#L273) and [here](https://github.com/volcengine/verl/blob/ba8555120af6a1f8dba8f09e60e4663ac5176efc/verl/experimental/agent_loop/tool_agent_loop.py#L297).
- If …
> [rollout] fix: remove code responsible for tool response duplication

- .github/workflows/.deprecate/e2e_ppo_trainer.yml
- .github/workflows/.deprecate/e2e_ppo_trainer_megatron_sglang.yml
- .github/workflows/.deprecate/e2e_spin.yml
- .github/workflows/.deprecate/e2e_sppo.yml
- .github/workflows/checkpoint_converter.yml
- .github/workflows/e2e_ppo_trainer_megatron_sglang.yml
- .github/workflows/e2e_ppo_trainer_megatron_sglang_2.yml
- .github/workflows/e2e_sft.yml
- .github/workflows/gpu_unit_tests.yml
- .github/workflows/reward_model.yml
- .github/workflows/sgl.yml
- docker/verl0.6-cu128-torch2.8.0-fa2.7.4/Dockerfile.app.sglang
- docker/verl0.6-cu128-torch2.8.0-fa2.7.4/Dockerfile.base
- requirements_sglang.txt
- setup.py
- verl/workers/rollout/sglang_rollout/async_sglang_server.py
Solve https://github.com/volcengine/verl/pull/3530#issuecomment-3332840437
> [ci] feat: upgrade sglang to 0.5.2

- examples/data_preprocess/aime2024_multiturn_w_tool.py
- examples/data_preprocess/dapo_multiturn_w_tool.py
- examples/data_preprocess/full_hh_rlhf.py
- examples/data_preprocess/geo3k_multiturn_w_tool.py
- examples/data_preprocess/hellaswag.py
This is a follow-up PR to https://github.com/volcengine/verl/pull/3362
> For changes that can not be tested by CI (e.g., algorithm implementation, new model support), validate by experiment(s) and show …
> [tool] feat: support load local datasets when preparing datasets

- tests/special_npu/run_qwen3_06b_ppo.sh
As per title.
This PR is a temporary workaround for the following issues：
https://github.com/volcengine/verl/actions/runs/18013408026/job/51251922982?pr=3625
> For changes that can not be tested by CI (e.g., …
> [CI] fix: changed the model used in the PPO test case to Qwen2.5-0.5B to avoid the huggingface download error

- verl/utils/megatron_utils.py
Implementation refers to https://github.com/NVIDIA/Megatron-LM/commit/b600e38d7b2a5b31d8d90e35bcf0cad18977a99c#diff-ff40c5dfa6c8106a478517375d98bc4e548ff71bcc3e5b25a4c1cc540f31ed3a
Use `hasattr(parallel_state, "is_inside_encoder")` for backward compatibility.
- `{type}` is in `feat`, `fix`, `refactor`, `chore`, …
> [megatron, training_utils] fix: encoder pp is removed in mcore >= 0.14

- .github/workflows/checkpoint_converter.yml
> [ci] fix: fix checkpoint converter ci
